// DrumEndorsementLandscapeStudyPage — /studies/drum-endorsement-landscape
// Issue #4765 (phase 2/3 of epic #4763): which brands endorse the most drummers
// in the roster, signature-model counts, and brand x genre patterns, computed
// from data/studies/drumEndorsementLandscape.js (generated by
// scripts/compute-studies.cjs). Nothing on this page is hand-written.

import React, { useEffect, useContext } from 'react';
import { View, Text, ScrollView, StyleSheet, Platform } from 'react-native';
import { ThemeContext } from '../ThemeContext';
import { DRUM_ENDORSEMENT_LANDSCAPE } from '../data/studies/drumEndorsementLandscape';
import { getStudyBySlug } from '../data/studies';

const BASE_URL = 'https://metalforge.io';
const STUDY_SLUG = 'drum-endorsement-landscape';

// Brands with a dedicated /brands/:slug landing page (packages/frontend/data/brands.js).
const BRAND_SLUGS = {
  Tama: 'tama',
  Pearl: 'pearl',
  DW: 'dw',
  Ludwig: 'ludwig',
  Mapex: 'mapex',
  Sonor: 'sonor',
  Zildjian: 'zildjian',
  Sabian: 'sabian',
  Paiste: 'paiste',
  Meinl: 'meinl',
  'Vic Firth': 'vic-firth',
  Promark: 'pro-mark',
  Vater: 'vater',
  Ahead: 'ahead',
  Wincent: 'wincent',
  Axis: 'axis',
};

// Genres with a dedicated /genre/:slug landing page whose slug unambiguously
// matches this study's Title Case genre bucket — see TempoBySubgenreStudyPage's
// equivalent map for why the rest render as plain text instead of a guessed link.
const GENRE_SLUGS = {
  'Thrash Metal': 'thrash',
  'Death Metal': 'death',
  'Technical Death Metal': 'technical-death',
  'Black Metal': 'black',
  'Progressive Metal': 'progressive',
  'Nu Metal': 'nu-metal',
  'Groove Metal': 'groove',
  Metalcore: 'metalcore',
};

const CATEGORY_LABELS = { kits: 'Kits', snares: 'Snares', cymbals: 'Cymbals', sticks: 'Sticks', pedals: 'Pedals' };

function drummerHref(slug) {
  return `/drummer/${slug}`;
}

function navigate(path) {
  if (Platform.OS === 'web' && typeof window !== 'undefined') {
    window.history.pushState({}, '', path);
    window.dispatchEvent(new PopStateEvent('popstate'));
  }
}

function WebLink({ href, children, style }) {
  return (
    <a
      href={href}
      onClick={(e) => {
        e.preventDefault();
        navigate(href);
      }}
      style={{ textDecoration: 'none', ...style }}
    >
      {children}
    </a>
  );
}

function BrandLink({ brand, theme }) {
  const slug = BRAND_SLUGS[brand];
  if (!slug) return <strong>{brand}</strong>;
  return (
    <WebLink href={`/brands/${slug}`} style={{ color: theme.primary, fontWeight: 600 }}>
      {brand}
    </WebLink>
  );
}

function GenreLink({ genre, theme }) {
  const slug = GENRE_SLUGS[genre];
  if (!slug) return <strong>{genre}</strong>;
  return (
    <WebLink href={`/genre/${slug}`} style={{ color: theme.primary, fontWeight: 600 }}>
      {genre}
    </WebLink>
  );
}

function buildArticleSchema(study) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: study.seoTitle,
    description: study.description,
    datePublished: study.dateModified,
    dateModified: study.dateModified,
    about: DRUM_ENDORSEMENT_LANDSCAPE.brandReach.slice(0, 8).map((b) => ({
      '@type': 'Thing',
      name: `${b.brand} drummer endorsements`,
    })),
    author: { '@type': 'Organization', name: 'MetalForge', url: BASE_URL },
    publisher: { '@type': 'Organization', name: 'MetalForge', url: BASE_URL },
    mainEntityOfPage: { '@type': 'WebPage', '@id': `${BASE_URL}/studies/${STUDY_SLUG}` },
  };
}

function injectSchema(study) {
  if (typeof document === 'undefined') return;
  const existing = document.querySelector('script[type="application/ld+json"][data-page="study-endorsement-landscape"]');
  if (existing) existing.remove();
  const script = document.createElement('script');
  script.type = 'application/ld+json';
  script.setAttribute('data-page', 'study-endorsement-landscape');
  script.textContent = JSON.stringify(buildArticleSchema(study));
  document.head.appendChild(script);
}

function removeSchema() {
  if (typeof document === 'undefined') return;
  const el = document.querySelector('script[type="application/ld+json"][data-page="study-endorsement-landscape"]');
  if (el) el.remove();
}

function BrandReachBarChart({ brands, theme, maxBars = 10 }) {
  const top = brands.slice(0, maxBars);
  if (top.length === 0) return null;
  const maxPercent = Math.max(...top.map((b) => b.percent), 1);
  const barHeight = 24;
  const gap = 10;
  const labelWidth = 110;
  const chartWidth = 480;
  const barMaxWidth = chartWidth - labelWidth - 70;
  const svgHeight = top.length * (barHeight + gap);

  if (Platform.OS !== 'web') {
    return (
      <View>
        {top.map((b) => (
          <View key={b.brand} style={styles.nativeBarRow}>
            <Text style={{ color: theme.text }}>{b.brand}</Text>
            <Text style={{ color: theme.secondaryText }}>{b.count} ({b.percent}%)</Text>
          </View>
        ))}
      </View>
    );
  }

  return (
    <svg
      width="100%"
      viewBox={`0 0 ${chartWidth} ${svgHeight}`}
      style={{ maxWidth: chartWidth, display: 'block' }}
      role="img"
      aria-label={`Bar chart: brand reach — ${top.map((b) => `${b.brand} ${b.percent}%`).join(', ')}`}
    >
      {top.map((b, i) => {
        const y = i * (barHeight + gap);
        const w = Math.max((b.percent / maxPercent) * barMaxWidth, 2);
        return (
          <g key={b.brand}>
            <text x={0} y={y + barHeight / 2 + 4} fontSize={13} fill={theme.text}>
              {b.brand}
            </text>
            <rect x={labelWidth} y={y} width={barMaxWidth} height={barHeight} fill={theme.border} rx={4} />
            <rect x={labelWidth} y={y} width={w} height={barHeight} fill={theme.primary} rx={4} />
            <text x={labelWidth + w + 8} y={y + barHeight / 2 + 4} fontSize={12} fill={theme.secondaryText}>
              {b.count} ({b.percent}%)
            </text>
          </g>
        );
      })}
    </svg>
  );
}

function tableHeadStyle(theme) {
  return { textAlign: 'left', padding: '8px 10px', color: theme.secondaryText, fontWeight: 700, whiteSpace: 'nowrap' };
}
function tableCellStyle(theme) {
  return { padding: '8px 10px', color: theme.text, verticalAlign: 'top' };
}

function BrandReachTable({ brands, totalDrummers, theme }) {
  if (Platform.OS !== 'web') {
    return (
      <View>
        {brands.map((b, i) => (
          <View key={b.brand} style={[styles.nativeTableRow, { borderTopColor: theme.border }]}>
            <Text style={{ color: theme.text, fontWeight: '600' }}>#{i + 1} {b.brand}</Text>
            <Text style={{ color: theme.secondaryText }}>{b.count} drummers ({b.percent}%)</Text>
          </View>
        ))}
      </View>
    );
  }
  return (
    <div style={{ overflowX: 'auto', WebkitOverflowScrolling: 'touch' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}>
        <thead>
          <tr>
            <th scope="col" style={tableHeadStyle(theme)}>Rank</th>
            <th scope="col" style={tableHeadStyle(theme)}>Brand</th>
            <th scope="col" style={tableHeadStyle(theme)}>Drummers</th>
            <th scope="col" style={tableHeadStyle(theme)}>% of {totalDrummers}</th>
            <th scope="col" style={tableHeadStyle(theme)}>Categories</th>
          </tr>
        </thead>
        <tbody>
          {brands.map((b, i) => (
            <tr key={b.brand} style={{ borderTop: `1px solid ${theme.border}` }}>
              <td style={tableCellStyle(theme)}>{i + 1}</td>
              <td style={tableCellStyle(theme)}><BrandLink brand={b.brand} theme={theme} /></td>
              <td style={tableCellStyle(theme)}>{b.count}</td>
              <td style={tableCellStyle(theme)}>{b.percent}%</td>
              <td style={tableCellStyle(theme)}>{b.categories.map((c) => CATEGORY_LABELS[c]).join(', ')}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function SignatureModelTable({ byBrand, theme, unitLabel }) {
  if (byBrand.length === 0) return null;
  if (Platform.OS !== 'web') {
    return (
      <View>
        {byBrand.map((b) => (
          <View key={b.brand} style={[styles.nativeTableRow, { borderTopColor: theme.border }]}>
            <Text style={{ color: theme.text, fontWeight: '600' }}>{b.brand}</Text>
            <Text style={{ color: theme.secondaryText }}>{b.modelCount} {unitLabel}</Text>
          </View>
        ))}
      </View>
    );
  }
  return (
    <div style={{ overflowX: 'auto', WebkitOverflowScrolling: 'touch' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}>
        <thead>
          <tr>
            <th scope="col" style={tableHeadStyle(theme)}>Brand</th>
            <th scope="col" style={tableHeadStyle(theme)}>{unitLabel}</th>
            <th scope="col" style={tableHeadStyle(theme)}>Drummers</th>
          </tr>
        </thead>
        <tbody>
          {byBrand.map((b) => (
            <tr key={b.brand} style={{ borderTop: `1px solid ${theme.border}` }}>
              <td style={tableCellStyle(theme)}><BrandLink brand={b.brand} theme={theme} /></td>
              <td style={tableCellStyle(theme)}>{b.modelCount}</td>
              <td style={tableCellStyle(theme)}>
                {b.drummers.map((d, di) => (
                  <React.Fragment key={d.slug || di}>
                    {di > 0 ? ', ' : ''}
                    {d.slug ? (
                      <WebLink href={drummerHref(d.slug)} style={{ color: theme.secondaryText }}>{d.name}</WebLink>
                    ) : (
                      d.name
                    )}
                  </React.Fragment>
                ))}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function GenreMatrixTable({ buckets, theme }) {
  if (Platform.OS !== 'web') {
    return (
      <View>
        {buckets.map((g) => (
          <View key={g.genre} style={[styles.nativeTableRow, { borderTopColor: theme.border }]}>
            <Text style={{ color: theme.text, fontWeight: '600' }}>{g.genre}</Text>
            <Text style={{ color: theme.secondaryText }}>
              Top brand: {g.topBrand} ({g.topBrandCount}/{g.totalDrummers})
            </Text>
          </View>
        ))}
      </View>
    );
  }
  return (
    <div style={{ overflowX: 'auto', WebkitOverflowScrolling: 'touch' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}>
        <thead>
          <tr>
            <th scope="col" style={tableHeadStyle(theme)}>Genre</th>
            <th scope="col" style={tableHeadStyle(theme)}>Drummers</th>
            <th scope="col" style={tableHeadStyle(theme)}>Top Kit Brand</th>
            <th scope="col" style={tableHeadStyle(theme)}>Full breakdown</th>
          </tr>
        </thead>
        <tbody>
          {buckets.map((g) => (
            <tr key={g.genre} style={{ borderTop: `1px solid ${theme.border}` }}>
              <td style={tableCellStyle(theme)}><GenreLink genre={g.genre} theme={theme} /></td>
              <td style={tableCellStyle(theme)}>{g.totalDrummers}</td>
              <td style={tableCellStyle(theme)}>
                <BrandLink brand={g.topBrand} theme={theme} /> ({g.topBrandCount})
              </td>
              <td style={tableCellStyle(theme)}>
                {g.brands.map((b) => `${b.brand} ${b.count}`).join(', ')}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function DrumEndorsementLandscapeStudyPage() {
  const theme = useContext(ThemeContext);
  const study = getStudyBySlug(STUDY_SLUG);
  const { brandReach, signatureModels, genreBrandMatrix, totalDrummers, generatedAt } = DRUM_ENDORSEMENT_LANDSCAPE;

  useEffect(() => {
    if (Platform.OS === 'web' && study) {
      document.title = `${study.seoTitle} | MetalForge`;
      injectSchema(study);
    }
    return () => removeSchema();
  }, []);

  if (!study) return null;

  const totalSignatureModels = signatureModels.sticks.signature.endorsedModelCount + signatureModels.snares.signature.endorsedModelCount;

  return (
    <ScrollView
      style={[styles.container, { backgroundColor: theme.background }]}
      contentContainerStyle={styles.scrollContent}
    >
      <View style={styles.header}>
        <Text style={[styles.pageTitle, { color: theme.text }]}>{study.seoTitle}</Text>
        <Text style={[styles.subtitle, { color: theme.secondaryText }]}>{study.description}</Text>
      </View>

      <View style={[styles.section, styles.headlineGrid]}>
        <View style={[styles.headlineCard, { backgroundColor: theme.card, borderColor: theme.border }]}>
          <Text style={[styles.headlineLabel, { color: theme.secondaryText }]}>Widest Reach</Text>
          <Text style={[styles.headlineBrand, { color: theme.text }]}>{brandReach[0].brand}</Text>
          <Text style={[styles.headlineStat, { color: theme.primary }]}>
            {brandReach[0].count} of {totalDrummers} ({brandReach[0].percent}%)
          </Text>
        </View>
        <View style={[styles.headlineCard, { backgroundColor: theme.card, borderColor: theme.border }]}>
          <Text style={[styles.headlineLabel, { color: theme.secondaryText }]}>Signature Models</Text>
          <Text style={[styles.headlineBrand, { color: theme.text }]}>{totalSignatureModels}</Text>
          <Text style={[styles.headlineStat, { color: theme.primary }]}>sticks + snares tracked</Text>
        </View>
        <View style={[styles.headlineCard, { backgroundColor: theme.card, borderColor: theme.border }]}>
          <Text style={[styles.headlineLabel, { color: theme.secondaryText }]}>Top Signature Stick Brand</Text>
          <Text style={[styles.headlineBrand, { color: theme.text }]}>{signatureModels.sticks.signature.byBrand[0]?.brand}</Text>
          <Text style={[styles.headlineStat, { color: theme.primary }]}>
            {signatureModels.sticks.signature.byBrand[0]?.modelCount} models
          </Text>
        </View>
        <View style={[styles.headlineCard, { backgroundColor: theme.card, borderColor: theme.border }]}>
          <Text style={[styles.headlineLabel, { color: theme.secondaryText }]}>Genre Buckets Analyzed</Text>
          <Text style={[styles.headlineBrand, { color: theme.text }]}>{genreBrandMatrix.buckets.length}</Text>
          <Text style={[styles.headlineStat, { color: theme.primary }]}>≥{genreBrandMatrix.bucketMinDrummers} drummers each</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={[styles.sectionTitle, { color: theme.text }]}>Brand Reach — Roster-Wide</Text>
        <Text style={[styles.sectionSubtitle, { color: theme.secondaryText }]}>
          Every roster drummer a brand appears for, across kits, snares, cymbals, sticks, and pedals combined.
        </Text>
        <View style={[styles.chartBox, { backgroundColor: theme.card, borderColor: theme.border }]}>
          <BrandReachBarChart brands={brandReach} theme={theme} />
        </View>
        <BrandReachTable brands={brandReach} totalDrummers={totalDrummers} theme={theme} />
      </View>

      <View style={styles.section}>
        <Text style={[styles.sectionTitle, { color: theme.text }]}>Signature Drumsticks by Brand</Text>
        <SignatureModelTable byBrand={signatureModels.sticks.signature.byBrand} theme={theme} unitLabel="signature models" />
      </View>

      <View style={styles.section}>
        <Text style={[styles.sectionTitle, { color: theme.text }]}>Signature Snares by Brand</Text>
        <SignatureModelTable byBrand={signatureModels.snares.signature.byBrand} theme={theme} unitLabel="signature models" />
      </View>

      <View style={styles.section}>
        <Text style={[styles.sectionTitle, { color: theme.text }]}>Kit Brand by Genre</Text>
        <Text style={[styles.sectionSubtitle, { color: theme.secondaryText }]}>
          Drum-kit brand preference within each genre bucket that has at least {genreBrandMatrix.bucketMinDrummers}{' '}
          roster drummers.
        </Text>
        <GenreMatrixTable buckets={genreBrandMatrix.buckets} theme={theme} />
      </View>

      <View style={[styles.section, styles.methodologyBox, { backgroundColor: theme.card, borderColor: theme.border }]}>
        <Text style={[styles.sectionTitle, { color: theme.text }]}>Methodology</Text>
        <Text style={[styles.methodologyText, { color: theme.secondaryText }]}>
          Dataset: all {totalDrummers} drummers documented on MetalForge as of {generatedAt}. "Brand reach"
          counts a drummer once per brand regardless of how many of the five gear categories (kits, snares,
          cymbals, sticks, pedals) that brand appears in for them — it is a broader, cross-category version of
          the per-category brand counts in MetalForge's companion "Most-Used Gear Brands" study, not a new
          measurement.
        </Text>
        <Text style={[styles.methodologyText, { color: theme.secondaryText }]}>
          Signature-model counts are separate from brand reach: they count named product models in
          MetalForge's drumsticks and snares data modules, not drummers, so a drummer with two signature
          products from the same brand counts twice there. {signatureModels.cymbalsCaveat}
        </Text>
        <Text style={[styles.methodologyText, { color: theme.secondaryText }]}>
          The genre x brand table only breaks out genre buckets (a drummer's first-listed genre tag) with at
          least {genreBrandMatrix.bucketMinDrummers} roster drummers — {genreBrandMatrix.otherGenreDrummerCount}{' '}
          additional drummers fall into single-drummer genre buckets, too thin to support a brand "pattern"
          claim, and are omitted from this table rather than implied.
        </Text>
        <Text style={[styles.methodologyText, { color: theme.secondaryText, fontStyle: 'italic' }]}>
          Roster bias: this counts MetalForge's own documented roster, not a scientific survey of the endorsement
          deals every metal drummer holds. "Endorsement" here means the brand relationship documented on each
          drummer's public gear listing (source links on each drummer's profile) — not every such relationship is
          necessarily a paid endorsement deal.
        </Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, padding: 16 },
  scrollContent: { paddingBottom: 40 },
  header: { marginBottom: 24 },
  pageTitle: { fontSize: 26, fontWeight: '700', marginBottom: 8, lineHeight: 32 },
  subtitle: { fontSize: 16, lineHeight: 22 },
  section: { marginBottom: 32 },
  sectionTitle: { fontSize: 20, fontWeight: '700', marginBottom: 12 },
  sectionSubtitle: { fontSize: 14, lineHeight: 20, marginBottom: 12 },
  headlineGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 8 },
  headlineCard: { flexGrow: 1, minWidth: 140, padding: 14, borderRadius: 8, borderWidth: 1 },
  headlineLabel: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase', marginBottom: 4 },
  headlineBrand: { fontSize: 18, fontWeight: '700', marginBottom: 4 },
  headlineStat: { fontSize: 13, fontWeight: '600' },
  chartBox: { padding: 16, borderRadius: 8, borderWidth: 1, marginBottom: 16 },
  nativeBarRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4 },
  nativeTableRow: { paddingVertical: 8, borderTopWidth: 1 },
  methodologyBox: { padding: 20, borderRadius: 8, borderWidth: 1 },
  methodologyText: { fontSize: 14, lineHeight: 21, marginBottom: 12 },
});

export default DrumEndorsementLandscapeStudyPage;
