// MetalKitConfigurationsStudyPage — /studies/metal-kit-configurations
// Issue #4765 (phase 2/3 of epic #4763): bass-pedal setup split and cymbal-setup
// size by genre, computed from data/studies/kitConfigurations.js (generated by
// scripts/compute-studies.cjs). Nothing on this page is hand-written.

import React, { useEffect, useContext } from 'react';
import { View, Text, ScrollView, StyleSheet, Platform } from 'react-native';
import { ThemeContext } from '../ThemeContext';
import { KIT_CONFIGURATIONS } from '../data/studies/kitConfigurations';
import { getStudyBySlug } from '../data/studies';

const BASE_URL = 'https://metalforge.io';
const STUDY_SLUG = 'metal-kit-configurations';

const GENRE_SLUGS = {
  'Thrash Metal': 'thrash',
  'Death Metal': 'death',
  'Technical Death Metal': 'technical-death',
  'Black Metal': 'black',
  'Progressive Metal': 'progressive',
  'Nu Metal': 'nu-metal',
  'Groove Metal': 'groove',
  Metalcore: 'metalcore',
};

const PEDAL_CONFIG_LABELS = {
  doubleBass: 'Double Bass (twin kicks)',
  twinSinglePedals: 'Twin Single Pedals',
  doublePedal: 'Double Pedal',
  singlePedal: 'Single Pedal',
  unspecified: 'Unspecified',
};
const PEDAL_CONFIG_ORDER = ['doublePedal', 'doubleBass', 'twinSinglePedals', 'singlePedal', 'unspecified'];

const PIECE_TYPE_LABELS = {
  'hi-hat': 'Hi-Hats',
  crash: 'Crashes',
  ride: 'Rides',
  china: 'Chinas',
  splash: 'Splashes',
  stack: 'Stacks',
  other: 'Other',
};

function drummerHref(slug) {
  return `/drummer/${slug}`;
}

function navigate(path) {
  if (Platform.OS === 'web' && typeof window !== 'undefined') {
    window.history.pushState({}, '', path);
    window.dispatchEvent(new PopStateEvent('popstate'));
  }
}

function WebLink({ href, children, style }) {
  return (
    <a
      href={href}
      onClick={(e) => {
        e.preventDefault();
        navigate(href);
      }}
      style={{ textDecoration: 'none', ...style }}
    >
      {children}
    </a>
  );
}

function GenreLink({ genre, theme }) {
  const slug = GENRE_SLUGS[genre];
  if (!slug) return <strong>{genre}</strong>;
  return (
    <WebLink href={`/genre/${slug}`} style={{ color: theme.primary, fontWeight: 600 }}>
      {genre}
    </WebLink>
  );
}

function buildArticleSchema(study) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: study.seoTitle,
    description: study.description,
    datePublished: study.dateModified,
    dateModified: study.dateModified,
    about: [
      { '@type': 'Thing', name: 'Double bass vs double pedal drum kit configurations' },
      { '@type': 'Thing', name: 'Metal drum cymbal setup size' },
    ],
    author: { '@type': 'Organization', name: 'MetalForge', url: BASE_URL },
    publisher: { '@type': 'Organization', name: 'MetalForge', url: BASE_URL },
    mainEntityOfPage: { '@type': 'WebPage', '@id': `${BASE_URL}/studies/${STUDY_SLUG}` },
  };
}

function injectSchema(study) {
  if (typeof document === 'undefined') return;
  const existing = document.querySelector('script[type="application/ld+json"][data-page="study-kit-configurations"]');
  if (existing) existing.remove();
  const script = document.createElement('script');
  script.type = 'application/ld+json';
  script.setAttribute('data-page', 'study-kit-configurations');
  script.textContent = JSON.stringify(buildArticleSchema(study));
  document.head.appendChild(script);
}

function removeSchema() {
  if (typeof document === 'undefined') return;
  const el = document.querySelector('script[type="application/ld+json"][data-page="study-kit-configurations"]');
  if (el) el.remove();
}

function PedalConfigBarChart({ overall, totalDrummers, theme }) {
  const rows = PEDAL_CONFIG_ORDER.map((key) => ({ key, label: PEDAL_CONFIG_LABELS[key], count: overall[key] })).filter(
    (r) => r.count > 0
  );
  const maxCount = Math.max(...rows.map((r) => r.count), 1);
  const barHeight = 26;
  const gap = 10;
  const labelWidth = 170;
  const chartWidth = 480;
  const barMaxWidth = chartWidth - labelWidth - 60;
  const svgHeight = rows.length * (barHeight + gap);

  if (Platform.OS !== 'web') {
    return (
      <View>
        {rows.map((r) => (
          <View key={r.key} style={styles.nativeBarRow}>
            <Text style={{ color: theme.text }}>{r.label}</Text>
            <Text style={{ color: theme.secondaryText }}>{r.count}</Text>
          </View>
        ))}
      </View>
    );
  }

  return (
    <svg
      width="100%"
      viewBox={`0 0 ${chartWidth} ${svgHeight}`}
      style={{ maxWidth: chartWidth, display: 'block' }}
      role="img"
      aria-label={`Bar chart: pedal configuration — ${rows.map((r) => `${r.label} ${r.count}`).join(', ')}`}
    >
      {rows.map((r, i) => {
        const y = i * (barHeight + gap);
        const w = Math.max((r.count / maxCount) * barMaxWidth, 2);
        const percent = Math.round((r.count / totalDrummers) * 1000) / 10;
        return (
          <g key={r.key}>
            <text x={0} y={y + barHeight / 2 + 4} fontSize={12} fill={theme.text}>
              {r.label}
            </text>
            <rect x={labelWidth} y={y} width={barMaxWidth} height={barHeight} fill={theme.border} rx={4} />
            <rect x={labelWidth} y={y} width={w} height={barHeight} fill={theme.primary} rx={4} />
            <text x={labelWidth + w + 8} y={y + barHeight / 2 + 4} fontSize={12} fill={theme.secondaryText}>
              {r.count} ({percent}%)
            </text>
          </g>
        );
      })}
    </svg>
  );
}

function tableHeadStyle(theme) {
  return { textAlign: 'left', padding: '8px 10px', color: theme.secondaryText, fontWeight: 700, whiteSpace: 'nowrap' };
}
function tableCellStyle(theme) {
  return { padding: '8px 10px', color: theme.text, verticalAlign: 'top' };
}

function PedalByGenreTable({ byGenre, theme }) {
  if (Platform.OS !== 'web') {
    return (
      <View>
        {byGenre.map((g) => (
          <View key={g.genre} style={[styles.nativeTableRow, { borderTopColor: theme.border }]}>
            <Text style={{ color: theme.text, fontWeight: '600' }}>{g.genre}</Text>
            <Text style={{ color: theme.secondaryText }}>{g.totalDrummers} drummers</Text>
          </View>
        ))}
      </View>
    );
  }
  return (
    <div style={{ overflowX: 'auto', WebkitOverflowScrolling: 'touch' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}>
        <thead>
          <tr>
            <th scope="col" style={tableHeadStyle(theme)}>Genre</th>
            <th scope="col" style={tableHeadStyle(theme)}>Drummers</th>
            <th scope="col" style={tableHeadStyle(theme)}>Double Pedal</th>
            <th scope="col" style={tableHeadStyle(theme)}>Double Bass</th>
            <th scope="col" style={tableHeadStyle(theme)}>Twin Single Pedals</th>
            <th scope="col" style={tableHeadStyle(theme)}>Single Pedal</th>
            <th scope="col" style={tableHeadStyle(theme)}>Unspecified</th>
          </tr>
        </thead>
        <tbody>
          {byGenre.map((g) => (
            <tr key={g.genre} style={{ borderTop: `1px solid ${theme.border}` }}>
              <td style={tableCellStyle(theme)}><GenreLink genre={g.genre} theme={theme} /></td>
              <td style={tableCellStyle(theme)}>{g.totalDrummers}</td>
              <td style={tableCellStyle(theme)}>{g.doublePedal}</td>
              <td style={tableCellStyle(theme)}>{g.doubleBass}</td>
              <td style={tableCellStyle(theme)}>{g.twinSinglePedals}</td>
              <td style={tableCellStyle(theme)}>{g.singlePedal}</td>
              <td style={tableCellStyle(theme)}>{g.unspecified}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function CymbalSizeByGenreTable({ byGenre, theme }) {
  if (Platform.OS !== 'web') {
    return (
      <View>
        {byGenre.map((g) => (
          <View key={g.genre} style={[styles.nativeTableRow, { borderTopColor: theme.border }]}>
            <Text style={{ color: theme.text, fontWeight: '600' }}>{g.genre}</Text>
            <Text style={{ color: theme.secondaryText }}>avg {g.avgPieces} pieces ({g.datasetSize} drummers)</Text>
          </View>
        ))}
      </View>
    );
  }
  return (
    <div style={{ overflowX: 'auto', WebkitOverflowScrolling: 'touch' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}>
        <thead>
          <tr>
            <th scope="col" style={tableHeadStyle(theme)}>Genre</th>
            <th scope="col" style={tableHeadStyle(theme)}>Drummers (verified)</th>
            <th scope="col" style={tableHeadStyle(theme)}>Avg Cymbal Pieces</th>
            <th scope="col" style={tableHeadStyle(theme)}>Median Pieces</th>
          </tr>
        </thead>
        <tbody>
          {byGenre.map((g) => (
            <tr key={g.genre} style={{ borderTop: `1px solid ${theme.border}` }}>
              <td style={tableCellStyle(theme)}><GenreLink genre={g.genre} theme={theme} /></td>
              <td style={tableCellStyle(theme)}>{g.datasetSize}</td>
              <td style={tableCellStyle(theme)}>{g.avgPieces}</td>
              <td style={tableCellStyle(theme)}>{g.medianPieces}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function PieceTypeTable({ pieceTypeCounts, theme }) {
  const rows = Object.entries(pieceTypeCounts).filter(([, count]) => count > 0);
  return (
    <div style={{ overflowX: 'auto', WebkitOverflowScrolling: 'touch' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}>
        <thead>
          <tr>
            <th scope="col" style={tableHeadStyle(theme)}>Cymbal Type</th>
            <th scope="col" style={tableHeadStyle(theme)}>Count Across Roster</th>
          </tr>
        </thead>
        <tbody>
          {rows.map(([type, count]) => (
            <tr key={type} style={{ borderTop: `1px solid ${theme.border}` }}>
              <td style={tableCellStyle(theme)}>{PIECE_TYPE_LABELS[type] || type}</td>
              <td style={tableCellStyle(theme)}>{count}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function ShellConfigTable({ configs, theme }) {
  if (Platform.OS !== 'web') {
    return (
      <View>
        {configs.map((c) => (
          <View key={c.drummerSlug} style={[styles.nativeTableRow, { borderTopColor: theme.border }]}>
            <Text style={{ color: theme.text, fontWeight: '600' }}>{c.drummerName}</Text>
            <Text style={{ color: theme.secondaryText }}>{c.totalShells} shells ({c.bassCount} bass, {c.tomCount} toms)</Text>
          </View>
        ))}
      </View>
    );
  }
  return (
    <div style={{ overflowX: 'auto', WebkitOverflowScrolling: 'touch' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}>
        <thead>
          <tr>
            <th scope="col" style={tableHeadStyle(theme)}>Drummer</th>
            <th scope="col" style={tableHeadStyle(theme)}>Bass Drums</th>
            <th scope="col" style={tableHeadStyle(theme)}>Toms</th>
            <th scope="col" style={tableHeadStyle(theme)}>Total Shells</th>
            <th scope="col" style={tableHeadStyle(theme)}>Full Config</th>
          </tr>
        </thead>
        <tbody>
          {configs.map((c) => (
            <tr key={c.drummerSlug} style={{ borderTop: `1px solid ${theme.border}` }}>
              <td style={tableCellStyle(theme)}>
                <WebLink href={drummerHref(c.drummerSlug)} style={{ color: theme.primary, fontWeight: 600 }}>
                  {c.drummerName}
                </WebLink>
                <Text style={{ color: theme.secondaryText }}> ({c.band})</Text>
              </td>
              <td style={tableCellStyle(theme)}>{c.bassCount}</td>
              <td style={tableCellStyle(theme)}>{c.tomCount}</td>
              <td style={tableCellStyle(theme)}>{c.totalShells}</td>
              <td style={tableCellStyle(theme)}>{c.raw}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function MetalKitConfigurationsStudyPage() {
  const theme = useContext(ThemeContext);
  const study = getStudyBySlug(STUDY_SLUG);
  const { pedalConfig, cymbalSetupSize, explicitShellConfigs, totalDrummers, generatedAt } = KIT_CONFIGURATIONS;

  useEffect(() => {
    if (Platform.OS === 'web' && study) {
      document.title = `${study.seoTitle} | MetalForge`;
      injectSchema(study);
    }
    return () => removeSchema();
  }, []);

  if (!study) return null;

  const topPedalConfig = PEDAL_CONFIG_ORDER.map((key) => ({ key, count: pedalConfig.overall[key] })).sort(
    (a, b) => b.count - a.count
  )[0];

  return (
    <ScrollView
      style={[styles.container, { backgroundColor: theme.background }]}
      contentContainerStyle={styles.scrollContent}
    >
      <View style={styles.header}>
        <Text style={[styles.pageTitle, { color: theme.text }]}>{study.seoTitle}</Text>
        <Text style={[styles.subtitle, { color: theme.secondaryText }]}>{study.description}</Text>
      </View>

      <View style={[styles.section, styles.headlineGrid]}>
        <View style={[styles.headlineCard, { backgroundColor: theme.card, borderColor: theme.border }]}>
          <Text style={[styles.headlineLabel, { color: theme.secondaryText }]}>Most Common Pedal Setup</Text>
          <Text style={[styles.headlineBrand, { color: theme.text }]}>{PEDAL_CONFIG_LABELS[topPedalConfig.key]}</Text>
          <Text style={[styles.headlineStat, { color: theme.primary }]}>
            {topPedalConfig.count} of {totalDrummers} drummers
          </Text>
        </View>
        <View style={[styles.headlineCard, { backgroundColor: theme.card, borderColor: theme.border }]}>
          <Text style={[styles.headlineLabel, { color: theme.secondaryText }]}>Physical Double Bass</Text>
          <Text style={[styles.headlineBrand, { color: theme.text }]}>{pedalConfig.overall.doubleBass} drummers</Text>
          <Text style={[styles.headlineStat, { color: theme.primary }]}>vs {pedalConfig.overall.doublePedal} double-pedal</Text>
        </View>
        <View style={[styles.headlineCard, { backgroundColor: theme.card, borderColor: theme.border }]}>
          <Text style={[styles.headlineLabel, { color: theme.secondaryText }]}>Avg Cymbal Setup</Text>
          <Text style={[styles.headlineBrand, { color: theme.text }]}>{cymbalSetupSize.avgPieces} pieces</Text>
          <Text style={[styles.headlineStat, { color: theme.primary }]}>
            {cymbalSetupSize.minPieces}-{cymbalSetupSize.maxPieces} range
          </Text>
        </View>
        <View style={[styles.headlineCard, { backgroundColor: theme.card, borderColor: theme.border }]}>
          <Text style={[styles.headlineLabel, { color: theme.secondaryText }]}>Verified Cymbal Setups</Text>
          <Text style={[styles.headlineBrand, { color: theme.text }]}>{cymbalSetupSize.datasetSize}</Text>
          <Text style={[styles.headlineStat, { color: theme.primary }]}>of {totalDrummers} drummers</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={[styles.sectionTitle, { color: theme.text }]}>Bass Pedal Configuration</Text>
        <Text style={[styles.sectionSubtitle, { color: theme.secondaryText }]}>
          How the {totalDrummers} roster drummers get their double-kick sound: a genuine double-bass kit (two
          physical kick drums), a double pedal on one kick, twin independent single pedals on one kick, or a
          traditional single pedal.
        </Text>
        <View style={[styles.chartBox, { backgroundColor: theme.card, borderColor: theme.border }]}>
          <PedalConfigBarChart overall={pedalConfig.overall} totalDrummers={totalDrummers} theme={theme} />
        </View>
      </View>

      <View style={styles.section}>
        <Text style={[styles.sectionTitle, { color: theme.text }]}>Pedal Configuration by Genre</Text>
        <PedalByGenreTable byGenre={pedalConfig.byGenre} theme={theme} />
      </View>

      <View style={styles.section}>
        <Text style={[styles.sectionTitle, { color: theme.text }]}>Cymbal Setup Size by Genre</Text>
        <Text style={[styles.sectionSubtitle, { color: theme.secondaryText }]}>
          Number of individually parsed cymbal pieces (hi-hats, crashes, rides, chinas, splashes) per drummer,
          across the {cymbalSetupSize.datasetSize}-drummer verified subset.
        </Text>
        <CymbalSizeByGenreTable byGenre={cymbalSetupSize.byGenre} theme={theme} />
      </View>

      <View style={styles.section}>
        <Text style={[styles.sectionTitle, { color: theme.text }]}>Cymbal Piece Types, Roster-Wide</Text>
        <PieceTypeTable pieceTypeCounts={cymbalSetupSize.pieceTypeCounts} theme={theme} />
      </View>

      <View style={styles.section}>
        <Text style={[styles.sectionTitle, { color: theme.text }]}>Full Shell Configurations (Documented Subset)</Text>
        <Text style={[styles.sectionSubtitle, { color: theme.secondaryText }]}>
          Most roster gear listings name only a drum kit's brand/series, not every shell size. These{' '}
          {explicitShellConfigs.length} drummers are the ones whose listing spells out the full kick/tom
          configuration — too small a sample to generalize to the rest of the roster, but useful as concrete
          reference points.
        </Text>
        <ShellConfigTable configs={explicitShellConfigs} theme={theme} />
      </View>

      <View style={[styles.section, styles.methodologyBox, { backgroundColor: theme.card, borderColor: theme.border }]}>
        <Text style={[styles.sectionTitle, { color: theme.text }]}>Methodology</Text>
        <Text style={[styles.methodologyText, { color: theme.secondaryText }]}>
          Dataset: all {totalDrummers} drummers documented on MetalForge as of {generatedAt} for pedal
          configuration (source: gear.drums + gear.hardware fields, current gear only). Pedal classification is
          text-pattern based against those literal strings: "double bass" requires the drums field to say "Bass
          Drums" (plural — either two named shell sizes or an explicit "x2"); "double pedal" and "single pedal"
          come from explicit wording in the hardware field. "Unspecified" ({pedalConfig.overall.unspecified}{' '}
          drummers) means neither field had an unambiguous single/double marker — not that those drummers have
          no pedal at all.
        </Text>
        <Text style={[styles.methodologyText, { color: theme.secondaryText }]}>
          Cymbal setup size uses cymbalSetups.js's verified {cymbalSetupSize.datasetSize}-of-{totalDrummers}{' '}
          subset (gear.verified: true roster entries only — see that module's own header for the excluded list).
          A "piece" is one individually parsed cymbal (a hi-hat pair counts as one piece); pieces with no
          confidently-parseable size in the source text are omitted from that module, so these counts are a
          floor, not a hard ceiling, on each drummer's actual cymbal setup.
        </Text>
        <Text style={[styles.methodologyText, { color: theme.secondaryText, fontStyle: 'italic' }]}>
          Kit "pieces" (full bass/tom shell counts) can't be reported roster-wide: gear.drums names only
          brand/series for most of the roster, not shell sizes. The Full Shell Configurations table above lists
          the small subset where that detail is documented, verbatim, rather than guessing shell counts for
          everyone else.
        </Text>
        <Text style={[styles.methodologyText, { color: theme.secondaryText, fontStyle: 'italic' }]}>
          Roster bias: this counts MetalForge's own documented roster, not a scientific survey of "all metal
          drummers" or beginner setups — the roster skews toward prominent, long-tenured touring acts, whose
          endorsement-deal kits tend to run larger than a typical practice-room or beginner kit.
        </Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, padding: 16 },
  scrollContent: { paddingBottom: 40 },
  header: { marginBottom: 24 },
  pageTitle: { fontSize: 26, fontWeight: '700', marginBottom: 8, lineHeight: 32 },
  subtitle: { fontSize: 16, lineHeight: 22 },
  section: { marginBottom: 32 },
  sectionTitle: { fontSize: 20, fontWeight: '700', marginBottom: 12 },
  sectionSubtitle: { fontSize: 14, lineHeight: 20, marginBottom: 12 },
  headlineGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 8 },
  headlineCard: { flexGrow: 1, minWidth: 140, padding: 14, borderRadius: 8, borderWidth: 1 },
  headlineLabel: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase', marginBottom: 4 },
  headlineBrand: { fontSize: 18, fontWeight: '700', marginBottom: 4 },
  headlineStat: { fontSize: 13, fontWeight: '600' },
  chartBox: { padding: 16, borderRadius: 8, borderWidth: 1, marginBottom: 16 },
  nativeBarRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4 },
  nativeTableRow: { paddingVertical: 8, borderTopWidth: 1 },
  methodologyBox: { padding: 20, borderRadius: 8, borderWidth: 1 },
  methodologyText: { fontSize: 14, lineHeight: 21, marginBottom: 12 },
});

export default MetalKitConfigurationsStudyPage;
