// MostUsedGearBrandsStudyPage — /studies/most-used-gear-brands-metal
// Issue #4764 (phase 1/3 of epic #4763): the flagship study proving the
// /studies pattern — every number here comes from data/studies/mostUsedGearBrands.js,
// generated by scripts/compute-studies.cjs. Nothing on this page is hand-written.

import React, { useEffect, useContext } from 'react';
import { View, Text, ScrollView, StyleSheet, Platform } from 'react-native';
import { ThemeContext } from '../ThemeContext';
import { MOST_USED_GEAR_BRANDS } from '../data/studies/mostUsedGearBrands';
import { getStudyBySlug } from '../data/studies';

const BASE_URL = 'https://metalforge.io';
const STUDY_SLUG = 'most-used-gear-brands-metal';

// Brands with a dedicated /brands/:slug landing page (packages/frontend/data/brands.js).
// Not every brand this study counts has one — those render as plain text instead
// of a dead link.
const BRAND_SLUGS = {
  Tama: 'tama',
  Pearl: 'pearl',
  DW: 'dw',
  Ludwig: 'ludwig',
  Mapex: 'mapex',
  Sonor: 'sonor',
  Zildjian: 'zildjian',
  Sabian: 'sabian',
  Paiste: 'paiste',
  Meinl: 'meinl',
  'Vic Firth': 'vic-firth',
  Promark: 'pro-mark',
  Vater: 'vater',
  Ahead: 'ahead',
  Wincent: 'wincent',
  Axis: 'axis',
};

function drummerHref(slug) {
  return `/drummer/${slug}`;
}

function navigate(path) {
  if (Platform.OS === 'web' && typeof window !== 'undefined') {
    window.history.pushState({}, '', path);
    window.dispatchEvent(new PopStateEvent('popstate'));
  }
}

function WebLink({ href, children, style }) {
  return (
    <a
      href={href}
      onClick={(e) => {
        e.preventDefault();
        navigate(href);
      }}
      style={{ textDecoration: 'none', ...style }}
    >
      {children}
    </a>
  );
}

function buildArticleSchema(study) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: study.seoTitle,
    description: study.description,
    datePublished: study.dateModified,
    dateModified: study.dateModified,
    about: Object.entries(MOST_USED_GEAR_BRANDS.categories).map(([key, cat]) => ({
      '@type': 'Thing',
      name: `${cat.label} brand usage among metal drummers`,
    })),
    author: { '@type': 'Organization', name: 'MetalForge', url: BASE_URL },
    publisher: { '@type': 'Organization', name: 'MetalForge', url: BASE_URL },
    mainEntityOfPage: { '@type': 'WebPage', '@id': `${BASE_URL}/studies/${STUDY_SLUG}` },
  };
}

function injectSchema(study) {
  if (typeof document === 'undefined') return;
  const existing = document.querySelector('script[type="application/ld+json"][data-page="study-gear-brands"]');
  if (existing) existing.remove();
  const script = document.createElement('script');
  script.type = 'application/ld+json';
  script.setAttribute('data-page', 'study-gear-brands');
  script.textContent = JSON.stringify(buildArticleSchema(study));
  document.head.appendChild(script);
}

function removeSchema() {
  if (typeof document === 'undefined') return;
  const el = document.querySelector('script[type="application/ld+json"][data-page="study-gear-brands"]');
  if (el) el.remove();
}

// Horizontal SVG bar chart for a category's top brands. Pure function of the
// generated data — no chart library, no client-only computation to keep it
// SSR-parity-friendly with the equivalent markup api/meta/[...path].js emits
// for bot user-agents.
function CategoryBarChart({ ranked, theme, maxBars = 6 }) {
  const top = ranked.slice(0, maxBars);
  if (top.length === 0) return null;
  const maxPercent = Math.max(...top.map((r) => r.percent), 1);
  const barHeight = 26;
  const gap = 10;
  const labelWidth = 100;
  const chartWidth = 460;
  const barMaxWidth = chartWidth - labelWidth - 70;
  const svgHeight = top.length * (barHeight + gap);

  if (Platform.OS !== 'web') {
    return (
      <View>
        {top.map((r) => (
          <View key={r.brand} style={styles.nativeBarRow}>
            <Text style={{ color: theme.text }}>{r.brand}</Text>
            <Text style={{ color: theme.secondaryText }}>
              {r.count} ({r.percent}%)
            </Text>
          </View>
        ))}
      </View>
    );
  }

  return (
    <svg
      width="100%"
      viewBox={`0 0 ${chartWidth} ${svgHeight}`}
      style={{ maxWidth: chartWidth, display: 'block' }}
      role="img"
      aria-label={`Bar chart: ${top.map((r) => `${r.brand} ${r.percent}%`).join(', ')}`}
    >
      {top.map((r, i) => {
        const y = i * (barHeight + gap);
        const w = Math.max((r.percent / maxPercent) * barMaxWidth, 2);
        return (
          <g key={r.brand}>
            <text x={0} y={y + barHeight / 2 + 4} fontSize={13} fill={theme.text}>
              {r.brand}
            </text>
            <rect x={labelWidth} y={y} width={barMaxWidth} height={barHeight} fill={theme.border} rx={4} />
            <rect x={labelWidth} y={y} width={w} height={barHeight} fill={theme.primary} rx={4} />
            <text x={labelWidth + w + 8} y={y + barHeight / 2 + 4} fontSize={12} fill={theme.secondaryText}>
              {r.count} ({r.percent}%)
            </text>
          </g>
        );
      })}
    </svg>
  );
}

function CategoryTable({ categoryKey, data, theme }) {
  if (Platform.OS !== 'web') {
    return (
      <View>
        {data.ranked.map((row, i) => (
          <View key={row.brand} style={[styles.nativeTableRow, { borderTopColor: theme.border }]}>
            <Text style={{ color: theme.text, fontWeight: '600' }}>
              #{i + 1} {row.brand}
            </Text>
            <Text style={{ color: theme.secondaryText }}>
              {row.count} drummers ({row.percent}%)
            </Text>
          </View>
        ))}
      </View>
    );
  }

  return (
    <div style={{ overflowX: 'auto', WebkitOverflowScrolling: 'touch' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}>
        <thead>
          <tr>
            <th scope="col" style={tableHeadStyle(theme)}>Rank</th>
            <th scope="col" style={tableHeadStyle(theme)}>Brand</th>
            <th scope="col" style={tableHeadStyle(theme)}>Drummers</th>
            <th scope="col" style={tableHeadStyle(theme)}>% of 67</th>
            <th scope="col" style={tableHeadStyle(theme)}>Who plays it</th>
          </tr>
        </thead>
        <tbody>
          {data.ranked.map((row, i) => {
            const brandSlug = BRAND_SLUGS[row.brand];
            return (
              <tr key={row.brand} style={{ borderTop: `1px solid ${theme.border}` }}>
                <td style={tableCellStyle(theme)}>{i + 1}</td>
                <td style={tableCellStyle(theme)}>
                  {brandSlug ? (
                    <WebLink href={`/brands/${brandSlug}`} style={{ color: theme.primary, fontWeight: 600 }}>
                      {row.brand}
                    </WebLink>
                  ) : (
                    <strong>{row.brand}</strong>
                  )}
                </td>
                <td style={tableCellStyle(theme)}>{row.count}</td>
                <td style={tableCellStyle(theme)}>{row.percent}%</td>
                <td style={tableCellStyle(theme)}>
                  {row.drummers.map((d, di) => (
                    <React.Fragment key={d.slug}>
                      {di > 0 ? ', ' : ''}
                      <WebLink href={drummerHref(d.slug)} style={{ color: theme.secondaryText }}>
                        {d.name}
                      </WebLink>
                    </React.Fragment>
                  ))}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

function tableHeadStyle(theme) {
  return { textAlign: 'left', padding: '8px 10px', color: theme.secondaryText, fontWeight: 700, whiteSpace: 'nowrap' };
}
function tableCellStyle(theme) {
  return { padding: '8px 10px', color: theme.text, verticalAlign: 'top' };
}

export function MostUsedGearBrandsStudyPage() {
  const theme = useContext(ThemeContext);
  const study = getStudyBySlug(STUDY_SLUG);
  const { categories, totalDrummers, generatedAt } = MOST_USED_GEAR_BRANDS;

  useEffect(() => {
    if (Platform.OS === 'web' && study) {
      document.title = `${study.seoTitle} | MetalForge`;
      injectSchema(study);
    }
    return () => removeSchema();
  }, []);

  if (!study) return null;

  const categoryOrder = ['kits', 'cymbals', 'snares', 'sticks', 'pedals'];

  return (
    <ScrollView
      style={[styles.container, { backgroundColor: theme.background }]}
      contentContainerStyle={styles.scrollContent}
    >
      <View style={styles.header}>
        <Text style={[styles.pageTitle, { color: theme.text }]}>{study.seoTitle}</Text>
        <Text style={[styles.subtitle, { color: theme.secondaryText }]}>{study.description}</Text>
      </View>

      <View style={[styles.section, styles.headlineGrid]}>
        {categoryOrder.map((key) => {
          const cat = categories[key];
          const top = cat.ranked[0];
          if (!top) return null;
          return (
            <View key={key} style={[styles.headlineCard, { backgroundColor: theme.card, borderColor: theme.border }]}>
              <Text style={[styles.headlineLabel, { color: theme.secondaryText }]}>{cat.label}</Text>
              <Text style={[styles.headlineBrand, { color: theme.text }]}>{top.brand}</Text>
              <Text style={[styles.headlineStat, { color: theme.primary }]}>
                {top.count} of {totalDrummers} ({top.percent}%)
              </Text>
            </View>
          );
        })}
      </View>

      {categoryOrder.map((key) => {
        const cat = categories[key];
        return (
          <View key={key} style={styles.section}>
            <Text style={[styles.sectionTitle, { color: theme.text }]}>{cat.label} — Brand Usage</Text>
            <View style={[styles.chartBox, { backgroundColor: theme.card, borderColor: theme.border }]}>
              <CategoryBarChart ranked={cat.ranked} theme={theme} />
            </View>
            <CategoryTable categoryKey={key} data={cat} theme={theme} />
          </View>
        );
      })}

      <View style={[styles.section, styles.methodologyBox, { backgroundColor: theme.card, borderColor: theme.border }]}>
        <Text style={[styles.sectionTitle, { color: theme.text }]}>Methodology</Text>
        <Text style={[styles.methodologyText, { color: theme.secondaryText }]}>
          Dataset: all {totalDrummers} drummers documented on MetalForge as of {generatedAt} (source: the
          public drummer roster this site is built on). Every one of the {totalDrummers} has a fully
          populated current gear configuration — drum kit, snare, cymbals, sticks, and hardware are all
          non-empty, sourced fields. 56 carry an explicit "verified" sourcing flag, 3 are flagged as
          awaiting source confirmation, and 8 predate that flag but have identical field completeness;
          all {totalDrummers} are counted in this study.
        </Text>
        <Text style={[styles.methodologyText, { color: theme.secondaryText }]}>
          Counting rule: a drummer counts once per brand per category. A dual-brand setup (for example a
          cymbal rig split across "Sabian AAX / Zildjian A Series") credits both brands, so a category's
          percentages can sum to more than 100%. Every percentage is a share of the full {totalDrummers}-drummer
          dataset, not just of the drummers with a recognized brand in that category. Historical gear
          (past-era setups) is excluded — only each drummer's current, most-recently-documented rig counts.
        </Text>
        <Text style={[styles.methodologyText, { color: theme.secondaryText }]}>
          Pedals are parsed only from the segments of the hardware field that mention "pedal," so a
          drummer whose throne or rack is a different brand than their pedal doesn't get that brand
          credited to the pedals category.
        </Text>
        <Text style={[styles.methodologyText, { color: theme.secondaryText, fontStyle: 'italic' }]}>
          Roster bias: this counts MetalForge's own documented roster, not a scientific survey of "all
          metal drummers." The roster skews toward prominent, long-tenured acts with public gear
          endorsements, mostly from North American and European metal — brand shares above describe this
          dataset, not the metal drumming population at large.
        </Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, padding: 16 },
  scrollContent: { paddingBottom: 40 },
  header: { marginBottom: 24 },
  pageTitle: { fontSize: 26, fontWeight: '700', marginBottom: 8, lineHeight: 32 },
  subtitle: { fontSize: 16, lineHeight: 22 },
  section: { marginBottom: 32 },
  sectionTitle: { fontSize: 20, fontWeight: '700', marginBottom: 12 },
  headlineGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 8 },
  headlineCard: { flexGrow: 1, minWidth: 140, padding: 14, borderRadius: 8, borderWidth: 1 },
  headlineLabel: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase', marginBottom: 4 },
  headlineBrand: { fontSize: 18, fontWeight: '700', marginBottom: 4 },
  headlineStat: { fontSize: 13, fontWeight: '600' },
  chartBox: { padding: 16, borderRadius: 8, borderWidth: 1, marginBottom: 16 },
  nativeBarRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4 },
  nativeTableRow: { paddingVertical: 8, borderTopWidth: 1 },
  methodologyBox: { padding: 20, borderRadius: 8, borderWidth: 1 },
  methodologyText: { fontSize: 14, lineHeight: 21, marginBottom: 12 },
});

export default MostUsedGearBrandsStudyPage;
