// TempoBySubgenreStudyPage — /studies/metal-tempo-by-subgenre
// Issue #4765 (phase 2/3 of epic #4763): average/median/max BPM per subgenre,
// tempo distribution, and the 200+ BPM "hall of speed," computed from
// data/studies/tempoBySubgenre.js (generated by scripts/compute-studies.cjs).
// Nothing on this page is hand-written.

import React, { useEffect, useContext } from 'react';
import { View, Text, ScrollView, StyleSheet, Platform } from 'react-native';
import { ThemeContext } from '../ThemeContext';
import { TEMPO_BY_SUBGENRE } from '../data/studies/tempoBySubgenre';
import { getStudyBySlug } from '../data/studies';

const BASE_URL = 'https://metalforge.io';
const STUDY_SLUG = 'metal-tempo-by-subgenre';

// Genres with a dedicated /genre/:slug landing page (packages/frontend/data/genres.js)
// whose slug is an unambiguous match for this study's genre keys — every other genre
// this study counts (heavy-metal, djent, doom-metal, deathcore, ...) has no matching
// landing page and renders as plain text instead of a guessed/dead link.
const GENRE_SLUGS = {
  'thrash-metal': 'thrash',
  'death-metal': 'death',
  'technical-death-metal': 'technical-death',
  'black-metal': 'black',
  'progressive-metal': 'progressive',
  'nu-metal': 'nu-metal',
  'groove-metal': 'groove',
  metalcore: 'metalcore',
};

function drummerHref(slug) {
  return `/drummer/${slug}`;
}

function navigate(path) {
  if (Platform.OS === 'web' && typeof window !== 'undefined') {
    window.history.pushState({}, '', path);
    window.dispatchEvent(new PopStateEvent('popstate'));
  }
}

function WebLink({ href, children, style }) {
  return (
    <a
      href={href}
      onClick={(e) => {
        e.preventDefault();
        navigate(href);
      }}
      style={{ textDecoration: 'none', ...style }}
    >
      {children}
    </a>
  );
}

function buildArticleSchema(study) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: study.seoTitle,
    description: study.description,
    datePublished: study.dateModified,
    dateModified: study.dateModified,
    about: TEMPO_BY_SUBGENRE.genres.slice(0, 8).map((g) => ({
      '@type': 'Thing',
      name: `${g.label} drumming tempo`,
    })),
    author: { '@type': 'Organization', name: 'MetalForge', url: BASE_URL },
    publisher: { '@type': 'Organization', name: 'MetalForge', url: BASE_URL },
    mainEntityOfPage: { '@type': 'WebPage', '@id': `${BASE_URL}/studies/${STUDY_SLUG}` },
  };
}

function injectSchema(study) {
  if (typeof document === 'undefined') return;
  const existing = document.querySelector('script[type="application/ld+json"][data-page="study-tempo-subgenre"]');
  if (existing) existing.remove();
  const script = document.createElement('script');
  script.type = 'application/ld+json';
  script.setAttribute('data-page', 'study-tempo-subgenre');
  script.textContent = JSON.stringify(buildArticleSchema(study));
  document.head.appendChild(script);
}

function removeSchema() {
  if (typeof document === 'undefined') return;
  const el = document.querySelector('script[type="application/ld+json"][data-page="study-tempo-subgenre"]');
  if (el) el.remove();
}

// Horizontal SVG bar chart of average BPM per genre. Pure function of the generated
// data, mirroring MostUsedGearBrandsStudyPage's CategoryBarChart so the two studies
// share a visual language without sharing a component (phase 1's own comment: each
// study's shape gets its own bespoke page).
function AvgBpmBarChart({ genres, theme, maxBars = 10 }) {
  const top = genres.slice(0, maxBars);
  if (top.length === 0) return null;
  const maxBpm = Math.max(...top.map((g) => g.avgBpm), 1);
  const barHeight = 24;
  const gap = 10;
  const labelWidth = 140;
  const chartWidth = 480;
  const barMaxWidth = chartWidth - labelWidth - 60;
  const svgHeight = top.length * (barHeight + gap);

  if (Platform.OS !== 'web') {
    return (
      <View>
        {top.map((g) => (
          <View key={g.genre} style={styles.nativeBarRow}>
            <Text style={{ color: theme.text }}>{g.label}</Text>
            <Text style={{ color: theme.secondaryText }}>{g.avgBpm} BPM</Text>
          </View>
        ))}
      </View>
    );
  }

  return (
    <svg
      width="100%"
      viewBox={`0 0 ${chartWidth} ${svgHeight}`}
      style={{ maxWidth: chartWidth, display: 'block' }}
      role="img"
      aria-label={`Bar chart: average BPM by genre — ${top.map((g) => `${g.label} ${g.avgBpm}`).join(', ')}`}
    >
      {top.map((g, i) => {
        const y = i * (barHeight + gap);
        const w = Math.max((g.avgBpm / maxBpm) * barMaxWidth, 2);
        return (
          <g key={g.genre}>
            <text x={0} y={y + barHeight / 2 + 4} fontSize={12} fill={theme.text}>
              {g.label}
            </text>
            <rect x={labelWidth} y={y} width={barMaxWidth} height={barHeight} fill={theme.border} rx={4} />
            <rect x={labelWidth} y={y} width={w} height={barHeight} fill={theme.primary} rx={4} />
            <text x={labelWidth + w + 8} y={y + barHeight / 2 + 4} fontSize={12} fill={theme.secondaryText}>
              {g.avgBpm} BPM
            </text>
          </g>
        );
      })}
    </svg>
  );
}

function GenreLink({ genre, label, theme }) {
  const slug = GENRE_SLUGS[genre];
  if (!slug) return <strong>{label}</strong>;
  return (
    <WebLink href={`/genre/${slug}`} style={{ color: theme.primary, fontWeight: 600 }}>
      {label}
    </WebLink>
  );
}

function GenreTable({ genres, theme }) {
  if (Platform.OS !== 'web') {
    return (
      <View>
        {genres.map((g, i) => (
          <View key={g.genre} style={[styles.nativeTableRow, { borderTopColor: theme.border }]}>
            <Text style={{ color: theme.text, fontWeight: '600' }}>
              #{i + 1} {g.label}
            </Text>
            <Text style={{ color: theme.secondaryText }}>
              {g.songCount} songs, avg {g.avgBpm} BPM ({g.minBpm}-{g.maxBpm})
            </Text>
          </View>
        ))}
      </View>
    );
  }

  return (
    <div style={{ overflowX: 'auto', WebkitOverflowScrolling: 'touch' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}>
        <thead>
          <tr>
            <th scope="col" style={tableHeadStyle(theme)}>Subgenre</th>
            <th scope="col" style={tableHeadStyle(theme)}>Songs</th>
            <th scope="col" style={tableHeadStyle(theme)}>Avg BPM</th>
            <th scope="col" style={tableHeadStyle(theme)}>Median BPM</th>
            <th scope="col" style={tableHeadStyle(theme)}>Range</th>
          </tr>
        </thead>
        <tbody>
          {genres.map((g) => (
            <tr key={g.genre} style={{ borderTop: `1px solid ${theme.border}` }}>
              <td style={tableCellStyle(theme)}><GenreLink genre={g.genre} label={g.label} theme={theme} /></td>
              <td style={tableCellStyle(theme)}>{g.songCount}</td>
              <td style={tableCellStyle(theme)}>{g.avgBpm}</td>
              <td style={tableCellStyle(theme)}>{g.medianBpm}</td>
              <td style={tableCellStyle(theme)}>{g.minBpm}-{g.maxBpm}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function HallOfSpeedTable({ songs, theme }) {
  if (Platform.OS !== 'web') {
    return (
      <View>
        {songs.map((s, i) => (
          <View key={s.id} style={[styles.nativeTableRow, { borderTopColor: theme.border }]}>
            <Text style={{ color: theme.text, fontWeight: '600' }}>
              #{i + 1} {s.song} — {s.bpm} BPM
            </Text>
            <Text style={{ color: theme.secondaryText }}>{s.band} ({s.genreLabel})</Text>
          </View>
        ))}
      </View>
    );
  }

  return (
    <div style={{ overflowX: 'auto', WebkitOverflowScrolling: 'touch' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}>
        <thead>
          <tr>
            <th scope="col" style={tableHeadStyle(theme)}>Rank</th>
            <th scope="col" style={tableHeadStyle(theme)}>Song</th>
            <th scope="col" style={tableHeadStyle(theme)}>Band</th>
            <th scope="col" style={tableHeadStyle(theme)}>BPM</th>
            <th scope="col" style={tableHeadStyle(theme)}>Genre</th>
            <th scope="col" style={tableHeadStyle(theme)}>Drummer</th>
          </tr>
        </thead>
        <tbody>
          {songs.map((s, i) => (
            <tr key={s.id} style={{ borderTop: `1px solid ${theme.border}` }}>
              <td style={tableCellStyle(theme)}>{i + 1}</td>
              <td style={tableCellStyle(theme)}><strong>{s.song}</strong> ({s.year})</td>
              <td style={tableCellStyle(theme)}>{s.band}</td>
              <td style={tableCellStyle(theme)}>{s.bpm}</td>
              <td style={tableCellStyle(theme)}><GenreLink genre={s.genre} label={s.genreLabel} theme={theme} /></td>
              <td style={tableCellStyle(theme)}>
                {s.drummer.inRoster ? (
                  <WebLink href={drummerHref(s.drummer.slug)} style={{ color: theme.secondaryText }}>
                    {s.drummer.name}
                  </WebLink>
                ) : (
                  s.drummer.name
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function tableHeadStyle(theme) {
  return { textAlign: 'left', padding: '8px 10px', color: theme.secondaryText, fontWeight: 700, whiteSpace: 'nowrap' };
}
function tableCellStyle(theme) {
  return { padding: '8px 10px', color: theme.text, verticalAlign: 'top' };
}

export function TempoBySubgenreStudyPage() {
  const theme = useContext(ThemeContext);
  const study = getStudyBySlug(STUDY_SLUG);
  const { genres, overall, hallOfSpeed, totalSongs, bpmVerified } = TEMPO_BY_SUBGENRE;

  useEffect(() => {
    if (Platform.OS === 'web' && study) {
      document.title = `${study.seoTitle} | MetalForge`;
      injectSchema(study);
    }
    return () => removeSchema();
  }, []);

  if (!study) return null;

  return (
    <ScrollView
      style={[styles.container, { backgroundColor: theme.background }]}
      contentContainerStyle={styles.scrollContent}
    >
      <View style={styles.header}>
        <Text style={[styles.pageTitle, { color: theme.text }]}>{study.seoTitle}</Text>
        <Text style={[styles.subtitle, { color: theme.secondaryText }]}>{study.description}</Text>
      </View>

      <View style={[styles.section, styles.headlineGrid]}>
        <View style={[styles.headlineCard, { backgroundColor: theme.card, borderColor: theme.border }]}>
          <Text style={[styles.headlineLabel, { color: theme.secondaryText }]}>Dataset</Text>
          <Text style={[styles.headlineBrand, { color: theme.text }]}>{totalSongs} songs</Text>
          <Text style={[styles.headlineStat, { color: theme.primary }]}>{genres.length} subgenres</Text>
        </View>
        <View style={[styles.headlineCard, { backgroundColor: theme.card, borderColor: theme.border }]}>
          <Text style={[styles.headlineLabel, { color: theme.secondaryText }]}>Average Tempo</Text>
          <Text style={[styles.headlineBrand, { color: theme.text }]}>{overall.avgBpm} BPM</Text>
          <Text style={[styles.headlineStat, { color: theme.primary }]}>Median {overall.medianBpm} BPM</Text>
        </View>
        <View style={[styles.headlineCard, { backgroundColor: theme.card, borderColor: theme.border }]}>
          <Text style={[styles.headlineLabel, { color: theme.secondaryText }]}>Fastest Subgenre</Text>
          <Text style={[styles.headlineBrand, { color: theme.text }]}>
            {[...genres].sort((a, b) => b.avgBpm - a.avgBpm)[0].label}
          </Text>
          <Text style={[styles.headlineStat, { color: theme.primary }]}>
            {[...genres].sort((a, b) => b.avgBpm - a.avgBpm)[0].avgBpm} BPM avg
          </Text>
        </View>
        <View style={[styles.headlineCard, { backgroundColor: theme.card, borderColor: theme.border }]}>
          <Text style={[styles.headlineLabel, { color: theme.secondaryText }]}>200+ BPM Club</Text>
          <Text style={[styles.headlineBrand, { color: theme.text }]}>{hallOfSpeed.length} songs</Text>
          <Text style={[styles.headlineStat, { color: theme.primary }]}>
            Fastest: {hallOfSpeed[0]?.bpm} BPM
          </Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={[styles.sectionTitle, { color: theme.text }]}>Average BPM by Subgenre</Text>
        <View style={[styles.chartBox, { backgroundColor: theme.card, borderColor: theme.border }]}>
          <AvgBpmBarChart genres={genres} theme={theme} />
        </View>
        <GenreTable genres={genres} theme={theme} />
      </View>

      <View style={styles.section}>
        <Text style={[styles.sectionTitle, { color: theme.text }]}>The 200+ BPM Club</Text>
        <Text style={[styles.sectionSubtitle, { color: theme.secondaryText }]}>
          Every song in the {totalSongs}-song database clocking 200 BPM or faster, fastest first.
        </Text>
        <HallOfSpeedTable songs={hallOfSpeed} theme={theme} />
      </View>

      <View style={[styles.section, styles.methodologyBox, { backgroundColor: theme.card, borderColor: theme.border }]}>
        <Text style={[styles.sectionTitle, { color: theme.text }]}>Methodology</Text>
        <Text style={[styles.methodologyText, { color: theme.secondaryText }]}>
          Dataset: the {totalSongs} songs in MetalForge's curated tempo database (source:
          packages/frontend/data/metalSongsBpm.js), spanning {genres.length} subgenre tags, as of{' '}
          {TEMPO_BY_SUBGENRE.generatedAt}. This is a curated selection of well-known tracks used elsewhere on the
          site's BPM tap-tempo tool — not an exhaustive catalog of every metal song ever recorded, so subgenre
          averages describe this dataset, not "all death metal" or "all thrash metal."
        </Text>
        <Text style={[styles.methodologyText, { color: theme.secondaryText, fontStyle: 'italic' }]}>
          BPM accuracy: {bpmVerified
            ? 'every BPM in this dataset has been verified against per-song audio analysis.'
            : 'this dataset’s BPM values are approximate, based on common tempo markings rather than per-song ' +
              'audio analysis (see metalSongsBpm.js’s own header comment). MetalForge’s companion songs ' +
              'project has a verified-BPM phase in progress (issue #4759) that has not merged as of this snapshot ' +
              '— once it has, this study will be regenerated against verified tempos and this note removed.'}
        </Text>
        <Text style={[styles.methodologyText, { color: theme.secondaryText }]}>
          Tempo ranges follow the site's existing tap-tempo classification: Doom/Sludge 40-89 BPM, Groove/Heavy
          90-129 BPM, Thrash/Power 130-169 BPM, Death/Black 170-250 BPM, Grindcore/Blast 251-400 BPM. A song's
          subgenre is its own tagged genre in the database, not a genre derived from its drummer's overall style.
        </Text>
        <Text style={[styles.methodologyText, { color: theme.secondaryText, fontStyle: 'italic' }]}>
          Drummer credits on the 200+ BPM table link to a MetalForge profile only when that drummer is in the
          current roster; several historical/former members tracked only in the songs database (e.g. earlier
          lineup drummers) are named but not linked.
        </Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, padding: 16 },
  scrollContent: { paddingBottom: 40 },
  header: { marginBottom: 24 },
  pageTitle: { fontSize: 26, fontWeight: '700', marginBottom: 8, lineHeight: 32 },
  subtitle: { fontSize: 16, lineHeight: 22 },
  section: { marginBottom: 32 },
  sectionTitle: { fontSize: 20, fontWeight: '700', marginBottom: 12 },
  sectionSubtitle: { fontSize: 14, lineHeight: 20, marginBottom: 12 },
  headlineGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 8 },
  headlineCard: { flexGrow: 1, minWidth: 140, padding: 14, borderRadius: 8, borderWidth: 1 },
  headlineLabel: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase', marginBottom: 4 },
  headlineBrand: { fontSize: 18, fontWeight: '700', marginBottom: 4 },
  headlineStat: { fontSize: 13, fontWeight: '600' },
  chartBox: { padding: 16, borderRadius: 8, borderWidth: 1, marginBottom: 16 },
  nativeBarRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4 },
  nativeTableRow: { paddingVertical: 8, borderTopWidth: 1 },
  methodologyBox: { padding: 20, borderRadius: 8, borderWidth: 1 },
  methodologyText: { fontSize: 14, lineHeight: 21, marginBottom: 12 },
});

export default TempoBySubgenreStudyPage;
