#!/bin/bash
# Daily E2E Test Runner for MetalForge
# Based on Ryan Carson's agent-driven E2E approach
# 
# Features:
# - Retry logic (2 attempts before failing)
# - Bug deduplication (checks for similar issues in last 24h)
# - Screenshots on failure
# - Rich context in GitHub issues

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOG_DIR="$PROJECT_DIR/.agents/test/logs"
SCREENSHOT_DIR="$PROJECT_DIR/.agents/test/screenshots"
LOG_FILE="$LOG_DIR/e2e-$(date '+%Y-%m-%d-%H%M').log"

# Config
BASE_URL="${TEST_URL:-https://metalforge.io}"
MAX_ATTEMPTS=2
REPO="ricardoparro/MetalDrummerGear"

# Ensure directories exist
mkdir -p "$LOG_DIR" "$SCREENSHOT_DIR"

# Cleanup old logs (keep last 7 days)
find "$LOG_DIR" -name "e2e-*.log" -mtime +7 -delete 2>/dev/null || true
find "$SCREENSHOT_DIR" -name "*.png" -mtime +7 -delete 2>/dev/null || true

log() {
  local msg="[$(date '+%H:%M:%S')] $1"
  echo "$msg" | tee -a "$LOG_FILE"
}

# Check for duplicate issues in last 24h
check_duplicate_issue() {
  local error_msg="$1"
  local search_query="repo:$REPO is:issue is:open label:ux-bug in:title \"UX Test\""
  
  # Get issues from last 24h
  local recent_issues=$(gh issue list \
    --repo "$REPO" \
    --label "ux-bug" \
    --state open \
    --json title,number,createdAt \
    --limit 10 2>/dev/null || echo "[]")
  
  # Check if any issue was created in last 24h with similar error
  local now=$(date +%s)
  local day_ago=$((now - 86400))
  
  echo "$recent_issues" | jq -r '.[] | select(.title | contains("UX Test")) | .number' | head -1
}

# Take screenshot on failure
capture_screenshot() {
  local name="$1"
  local screenshot_path="$SCREENSHOT_DIR/${name}-$(date '+%Y%m%d-%H%M%S').png"
  
  # Use playwright to capture
  cd "$PROJECT_DIR"
  npx playwright screenshot "$BASE_URL" "$screenshot_path" --full-page 2>/dev/null || true
  
  if [[ -f "$screenshot_path" ]]; then
    echo "$screenshot_path"
  else
    echo ""
  fi
}

# Run tests with retry
run_tests_with_retry() {
  local attempt=1
  local test_output=""
  local exit_code=0
  
  while [[ $attempt -le $MAX_ATTEMPTS ]]; do
    log "🧪 Attempt $attempt of $MAX_ATTEMPTS"
    
    cd "$PROJECT_DIR"
    test_output=$(node .agents/test/ux-interaction-tests.mjs 2>&1) || exit_code=$?
    
    if [[ $exit_code -eq 0 ]]; then
      log "✅ Tests passed on attempt $attempt"
      echo "$test_output"
      return 0
    fi
    
    log "⚠️ Attempt $attempt failed"
    
    if [[ $attempt -lt $MAX_ATTEMPTS ]]; then
      log "⏳ Waiting 10s before retry..."
      sleep 10
    fi
    
    ((attempt++))
  done
  
  log "❌ All $MAX_ATTEMPTS attempts failed"
  echo "$test_output"
  return 1
}

# File bug with deduplication
file_bug() {
  local errors="$1"
  local test_output="$2"
  
  # Check for duplicate
  local existing_issue=$(check_duplicate_issue "$errors")
  
  if [[ -n "$existing_issue" && "$existing_issue" != "null" ]]; then
    log "📝 Found existing issue #$existing_issue - adding comment instead of new issue"
    
    gh issue comment "$existing_issue" \
      --repo "$REPO" \
      --body "**🔄 Test failed again at $(date '+%Y-%m-%d %H:%M')**

\`\`\`
$errors
\`\`\`

<details>
<summary>Full output</summary>

\`\`\`
$test_output
\`\`\`
</details>"
    
    return
  fi
  
  # Capture screenshot
  local screenshot=$(capture_screenshot "failure")
  
  # Create new issue
  local title="[E2E] UX Test Failed - $(date '+%Y-%m-%d %H:%M')"
  local body="## 🚨 Daily E2E Test Failure

**Time:** $(date '+%Y-%m-%d %H:%M:%S')
**URL:** $BASE_URL
**Attempts:** $MAX_ATTEMPTS (all failed)

### Errors
\`\`\`
$errors
\`\`\`

### Full Test Output
<details>
<summary>Click to expand</summary>

\`\`\`
$test_output
\`\`\`
</details>

### Log File
\`$LOG_FILE\`
"

  if [[ -n "$screenshot" ]]; then
    body+="
### Screenshot
Captured at: \`$screenshot\`
"
  fi

  body+="
---
*Auto-generated by daily E2E runner*"

  log "🐛 Creating new issue..."
  gh issue create \
    --repo "$REPO" \
    --title "$title" \
    --body "$body" \
    --label "ai-fix" \
    --label "ux-bug"
}

# Main
main() {
  log "🚀 Starting MetalForge Daily E2E Tests"
  log "📍 URL: $BASE_URL"
  log "📂 Log: $LOG_FILE"
  
  local test_output=""
  local exit_code=0
  
  test_output=$(run_tests_with_retry) || exit_code=$?
  
  echo "$test_output" >> "$LOG_FILE"
  
  if [[ $exit_code -ne 0 ]]; then
    # Extract failures from output
    local errors=$(echo "$test_output" | grep -E "^❌|FAIL" | head -10 || echo "Unknown error")
    
    file_bug "$errors" "$test_output"
    
    log "❌ E2E Tests FAILED - Bug filed"
    exit 1
  fi
  
  log "✅ UX Tests PASSED"
  
  # Run media validation tests
  log "🎬 Running Drummer Media Tests..."
  local media_output=""
  local media_exit=0
  
  media_output=$(node .agents/test/drummer-media-tests.mjs 2>&1) || media_exit=$?
  
  echo "$media_output" >> "$LOG_FILE"
  
  if [[ $media_exit -ne 0 ]]; then
    local media_errors=$(echo "$media_output" | grep -E "^✗|→" | head -10 || echo "Media validation failed")
    
    file_bug "$media_errors" "$media_output"
    
    log "❌ Media Tests FAILED - Bug filed"
    exit 1
  fi
  
  log "✅ Media Tests PASSED"
  
  # Print summary
  echo ""
  echo "================================"
  echo "$test_output" | tail -10
  echo ""
  echo "$media_output" | tail -15
}

main "$@"
