// Image optimization utilities for MetalDrummerGear
// Implements Issue #311: Lazy loading and WebP support for images
//
// Reduces Vercel bandwidth costs and improves Core Web Vitals by:
// 1. Proxying external images through /api/image with CDN caching
// 2. Requesting appropriately sized images (Wikipedia thumb URLs)
// 3. Using responsive width hints with srcset
// 4. Converting to WebP format for modern browsers (via <picture> element)
// 5. Implementing lazy loading for below-the-fold images (loading="lazy")
// 6. Eager loading for above-the-fold images (loading="eager", priority={true})
// 7. Using decoding="async" and fetchPriority hints for optimal loading

const IS_PRODUCTION = typeof window !== 'undefined' && 
  window.location && 
  !window.location.hostname.includes('localhost');

const API_BASE = IS_PRODUCTION ? '' : '';

// Domains that should be proxied through our image optimization API
const PROXY_DOMAINS = [
  'upload.wikimedia.org',
  'commons.wikimedia.org',
];

// Standard responsive breakpoints (match ALLOWED_WIDTHS in api/image)
export const IMAGE_WIDTHS = {
  thumbnail: 64,      // List items, small avatars
  small: 128,         // Grid thumbnails
  medium: 256,        // Cards, medium avatars
  large: 384,         // Large cards
  hero: 640,          // Hero images, detail pages
  full: 1080,         // Full-width images
};

// Standard srcset widths for responsive images
export const SRCSET_WIDTHS = [400, 800, 1200];

// Local responsive image widths (generated by scripts/generate-responsive-images.cjs)
// For mobile LCP optimization (Issue #465, #466)
export const LOCAL_RESPONSIVE_WIDTHS = [100, 200, 400];

// Check if browser supports WebP
let webpSupported = null;
export function supportsWebP() {
  if (typeof window === 'undefined') return true; // SSR assumes modern browser
  
  if (webpSupported !== null) return webpSupported;
  
  // Check via canvas
  try {
    const canvas = document.createElement('canvas');
    canvas.width = 1;
    canvas.height = 1;
    webpSupported = canvas.toDataURL('image/webp').indexOf('data:image/webp') === 0;
  } catch {
    webpSupported = false;
  }
  
  return webpSupported;
}

// Check if browser supports AVIF (more aggressive check)
let avifSupported = null;
export function supportsAVIF() {
  if (typeof window === 'undefined') return false; // SSR assumes no AVIF
  
  if (avifSupported !== null) return avifSupported;
  
  // AVIF support is still limited, default to false for now
  // Can be enabled once browser support is broader
  avifSupported = false;
  return avifSupported;
}

/**
 * Check if a URL should be proxied through our image optimization API
 */
function shouldProxy(url) {
  if (!url) return false;
  try {
    const parsed = new URL(url);
    return PROXY_DOMAINS.some(domain => parsed.hostname.endsWith(domain));
  } catch {
    return false;
  }
}

/**
 * Get the preferred image format based on browser support
 */
function getPreferredFormat() {
  if (supportsAVIF()) return 'avif';
  if (supportsWebP()) return 'webp';
  return null;
}

/**
 * Get optimized image URL
 * @param {string} originalUrl - The original image URL
 * @param {object} options - Optimization options
 * @param {number} options.width - Desired width (will snap to nearest allowed width)
 * @param {number} options.quality - Quality 10-100 (default 80)
 * @param {string} options.format - Force format ('webp', 'avif', or null for auto)
 * @returns {string} Optimized image URL
 */
export function getOptimizedImageUrl(originalUrl, options = {}) {
  if (!originalUrl) return originalUrl;
  
  // Local images are already optimized and cached via vercel.json headers
  if (originalUrl.startsWith('/images/') || originalUrl.startsWith('/api/')) {
    return originalUrl;
  }
  
  // Only proxy external images from allowed domains
  if (!shouldProxy(originalUrl)) {
    return originalUrl;
  }
  
  const { width, quality = 80, format = null } = options;
  
  // Build proxy URL with optimization parameters
  const params = new URLSearchParams();
  params.set('url', originalUrl);
  
  if (width) {
    params.set('w', String(width));
  }
  
  if (quality !== 80) {
    params.set('q', String(quality));
  }
  
  // Request WebP format for supported browsers
  const preferredFormat = format || getPreferredFormat();
  if (preferredFormat) {
    params.set('f', preferredFormat);
  }
  
  return `${API_BASE}/api/image?${params.toString()}`;
}

/**
 * Get responsive image sources for different screen sizes
 * @param {string} originalUrl - The original image URL
 * @param {number[]} widths - Array of widths to generate
 * @returns {object[]} Array of { uri, width } objects
 */
export function getResponsiveImageSources(originalUrl, widths = [256, 512, 1080]) {
  return widths.map(width => ({
    uri: getOptimizedImageUrl(originalUrl, { width }),
    width,
  }));
}

/**
 * Generate srcset string for responsive images with WebP support
 * @param {string} originalUrl - The original image URL  
 * @param {number[]} widths - Array of widths (default: SRCSET_WIDTHS)
 * @returns {string} srcset string for <img> tag
 */
export function generateSrcSet(originalUrl, widths = SRCSET_WIDTHS) {
  if (!originalUrl) return '';
  return widths.map(w => `${getOptimizedImageUrl(originalUrl, { width: w })} ${w}w`).join(', ');
}

/**
 * Generate srcset string specifically for WebP format
 * @param {string} originalUrl - The original image URL  
 * @param {number[]} widths - Array of widths (default: SRCSET_WIDTHS)
 * @returns {string} srcset string for WebP source
 */
export function generateWebPSrcSet(originalUrl, widths = SRCSET_WIDTHS) {
  if (!originalUrl) return '';
  return widths.map(w => `${getOptimizedImageUrl(originalUrl, { width: w, format: 'webp' })} ${w}w`).join(', ');
}

/**
 * Check if URL is a local drummer image (served from /images/drummers/)
 * @param {string} url - Image URL to check
 * @returns {boolean} True if it's a local drummer image
 */
export function isLocalDrummerImage(url) {
  if (!url) return false;
  return url.startsWith('/images/drummers/') && url.endsWith('.webp');
}

/**
 * Generate srcset for local drummer images using pre-generated responsive sizes
 * Mobile LCP optimization (Issue #465, #466)
 * 
 * @param {string} imageUrl - Local drummer image URL (e.g., /images/drummers/lars-ulrich.webp)
 * @returns {string} srcset string with 100w, 200w, 400w, and original size
 */
export function generateLocalDrummerSrcSet(imageUrl) {
  if (!imageUrl || !isLocalDrummerImage(imageUrl)) return '';
  
  // Extract base name without extension
  const basePath = imageUrl.replace(/\.webp$/, '');
  
  // Generate srcset with pre-generated responsive sizes
  const srcsetParts = LOCAL_RESPONSIVE_WIDTHS.map(w => `${basePath}-${w}w.webp ${w}w`);
  
  // Add original as fallback for larger screens (assume ~800w for most)
  srcsetParts.push(`${imageUrl} 800w`);
  
  return srcsetParts.join(', ');
}

/**
 * Get optimized URL for local drummer image based on desired width
 * Returns the closest pre-generated size
 * 
 * @param {string} imageUrl - Local drummer image URL
 * @param {number} targetWidth - Desired display width
 * @returns {string} Optimized image URL
 */
export function getLocalDrummerImageUrl(imageUrl, targetWidth) {
  if (!imageUrl || !isLocalDrummerImage(imageUrl)) return imageUrl;
  
  // Find the smallest size that's >= target width (for crisp display)
  const basePath = imageUrl.replace(/\.webp$/, '');
  
  // Available widths: 100, 200, 400, original (~800)
  if (targetWidth <= 100) return `${basePath}-100w.webp`;
  if (targetWidth <= 200) return `${basePath}-200w.webp`;
  if (targetWidth <= 400) return `${basePath}-400w.webp`;
  
  // For larger sizes, use the original
  return imageUrl;
}

/**
 * Get sizes attribute for responsive images based on context
 * @param {string} context - Image context: 'thumbnail', 'card', 'detail', 'gallery', 'hero', 'spotlight'
 * @returns {string} sizes attribute value
 */
export function getSizesAttribute(context = 'card') {
  switch (context) {
    case 'thumbnail':
      return '60px';
    case 'card':
      return '(max-width: 480px) 100vw, (max-width: 768px) 50vw, 400px';
    case 'detail':
      return '(max-width: 480px) 100vw, (max-width: 768px) 50vw, 800px';
    case 'gallery':
      return '(max-width: 480px) 90vw, (max-width: 768px) 45vw, 400px';
    case 'hero':
    case 'spotlight':
      // Hero/spotlight images: larger on desktop, constrained on mobile
      return '(max-width: 480px) 100px, 140px';
    default:
      return '(max-width: 768px) 100vw, 800px';
  }
}

/**
 * Get lazy loading attribute based on image priority
 * @param {boolean} priority - Whether image is above the fold
 * @returns {string} loading attribute value
 */
export function getLoadingAttribute(priority = false) {
  return priority ? 'eager' : 'lazy';
}

/**
 * Get decoding attribute for optimal performance
 * @param {boolean} priority - Whether image is above the fold
 * @returns {string} decoding attribute value
 */
export function getDecodingAttribute(priority = false) {
  return priority ? 'sync' : 'async';
}

/**
 * Get fetchpriority attribute for resource prioritization
 * @param {boolean} priority - Whether image is above the fold
 * @returns {string} fetchpriority attribute value
 */
export function getFetchPriorityAttribute(priority = false) {
  return priority ? 'high' : 'low';
}

/**
 * Precomputed optimized URLs for common drummer image sizes
 * Call this when fetching drummer data to pre-optimize URLs
 */
export function optimizeDrummerImages(drummer) {
  if (!drummer) return drummer;
  
  return {
    ...drummer,
    // Thumbnail for lists (small)
    thumbnailUrl: getOptimizedImageUrl(drummer.image, { width: IMAGE_WIDTHS.thumbnail }),
    // Medium size for cards
    cardImageUrl: getOptimizedImageUrl(drummer.image, { width: IMAGE_WIDTHS.medium }),
    // Large size for detail pages
    heroImageUrl: getOptimizedImageUrl(drummer.image, { width: IMAGE_WIDTHS.hero }),
    // Original URL preserved
    originalImageUrl: drummer.image,
    // WebP URLs for modern browsers
    webpThumbnailUrl: getOptimizedImageUrl(drummer.image, { width: IMAGE_WIDTHS.thumbnail, format: 'webp' }),
    webpCardImageUrl: getOptimizedImageUrl(drummer.image, { width: IMAGE_WIDTHS.medium, format: 'webp' }),
    webpHeroImageUrl: getOptimizedImageUrl(drummer.image, { width: IMAGE_WIDTHS.hero, format: 'webp' }),
    // Optimized photo gallery
    optimizedPhotos: drummer.photos?.map(photo => ({
      thumbnail: getOptimizedImageUrl(photo, { width: IMAGE_WIDTHS.small }),
      full: getOptimizedImageUrl(photo, { width: IMAGE_WIDTHS.full }),
      webpThumbnail: getOptimizedImageUrl(photo, { width: IMAGE_WIDTHS.small, format: 'webp' }),
      webpFull: getOptimizedImageUrl(photo, { width: IMAGE_WIDTHS.full, format: 'webp' }),
      original: photo,
    })) || [],
  };
}

/**
 * expo-image props for optimal performance with lazy loading
 */
export const imageDefaults = {
  cachePolicy: 'memory-disk',
  transition: 200,
  contentFit: 'cover',
  placeholder: null,
};

/**
 * Get image props optimized for lazy loading
 * @param {boolean} priority - Whether this image is above the fold
 * @returns {object} Props object for expo-image or native img
 */
export function getLazyLoadingProps(priority = false) {
  return {
    loading: getLoadingAttribute(priority),
    decoding: getDecodingAttribute(priority),
    fetchPriority: getFetchPriorityAttribute(priority),
  };
}

/**
 * Create a blurhash placeholder for an image
 * This can be used as a placeholder while the full image loads
 * @param {string} blurhash - The blurhash string
 * @param {number} width - Placeholder width
 * @param {number} height - Placeholder height
 * @returns {object} Placeholder config for expo-image
 */
export function createBlurhashPlaceholder(blurhash, width = 32, height = 32) {
  if (!blurhash) return null;
  return {
    blurhash,
    width,
    height,
  };
}

/**
 * Generate picture element sources for WebP with fallback
 * @param {string} originalUrl - The original image URL
 * @param {number} width - Desired width
 * @returns {object} Object with webp and fallback sources
 */
export function getPictureSources(originalUrl, width) {
  if (!originalUrl || !shouldProxy(originalUrl)) {
    return {
      webp: null,
      fallback: originalUrl,
    };
  }
  
  return {
    webp: getOptimizedImageUrl(originalUrl, { width, format: 'webp' }),
    fallback: getOptimizedImageUrl(originalUrl, { width }),
  };
}

export default {
  getOptimizedImageUrl,
  getResponsiveImageSources,
  generateSrcSet,
  generateWebPSrcSet,
  getSizesAttribute,
  getLoadingAttribute,
  getDecodingAttribute,
  getFetchPriorityAttribute,
  getLazyLoadingProps,
  optimizeDrummerImages,
  getPictureSources,
  createBlurhashPlaceholder,
  supportsWebP,
  supportsAVIF,
  imageDefaults,
  IMAGE_WIDTHS,
  SRCSET_WIDTHS,
};
