// Vercel Serverless Function - List all available Gear Cards
// Issue #747: Gear Cards Gallery

export default function handler(req, res) {
  // List of all drummers with gear cards
  const cards = [
    {
      slug: 'lars-ulrich',
      name: 'Lars Ulrich',
      band: 'Metallica',
      genre: 'Thrash Metal',
      country: 'Denmark',
      stats: { totalPieces: 42, totalCost: 27450 },
      cardUrls: {
        instagram: '/api/card/lars-ulrich?format=instagram',
        twitter: '/api/card/lars-ulrich?format=twitter',
        stats: '/api/card/lars-ulrich?type=stats',
        spotlight: '/api/card/lars-ulrich?type=spotlight',
      },
    },
    {
      slug: 'joey-jordison',
      name: 'Joey Jordison',
      band: 'Slipknot',
      genre: 'Nu Metal',
      country: 'USA',
      stats: { totalPieces: 38, totalCost: 24800 },
      cardUrls: {
        instagram: '/api/card/joey-jordison?format=instagram',
        twitter: '/api/card/joey-jordison?format=twitter',
        stats: '/api/card/joey-jordison?type=stats',
        spotlight: '/api/card/joey-jordison?type=spotlight',
      },
    },
    {
      slug: 'gene-hoglan',
      name: 'Gene Hoglan',
      band: 'Testament',
      genre: 'Death/Thrash Metal',
      country: 'USA',
      stats: { totalPieces: 45, totalCost: 28200 },
      cardUrls: {
        instagram: '/api/card/gene-hoglan?format=instagram',
        twitter: '/api/card/gene-hoglan?format=twitter',
        stats: '/api/card/gene-hoglan?type=stats',
        spotlight: '/api/card/gene-hoglan?type=spotlight',
      },
    },
    {
      slug: 'dave-lombardo',
      name: 'Dave Lombardo',
      band: 'Slayer',
      genre: 'Thrash Metal',
      country: 'USA',
      stats: { totalPieces: 40, totalCost: 26500 },
      cardUrls: {
        instagram: '/api/card/dave-lombardo?format=instagram',
        twitter: '/api/card/dave-lombardo?format=twitter',
        stats: '/api/card/dave-lombardo?type=stats',
        spotlight: '/api/card/dave-lombardo?type=spotlight',
      },
    },
    {
      slug: 'tomas-haake',
      name: 'Tomas Haake',
      band: 'Meshuggah',
      genre: 'Progressive Metal',
      country: 'Sweden',
      stats: { totalPieces: 35, totalCost: 32500 },
      cardUrls: {
        instagram: '/api/card/tomas-haake?format=instagram',
        twitter: '/api/card/tomas-haake?format=twitter',
        stats: '/api/card/tomas-haake?type=stats',
        spotlight: '/api/card/tomas-haake?type=spotlight',
      },
    },
    {
      slug: 'danny-carey',
      name: 'Danny Carey',
      band: 'Tool',
      genre: 'Progressive Metal',
      country: 'USA',
      stats: { totalPieces: 48, totalCost: 45000 },
      cardUrls: {
        instagram: '/api/card/danny-carey?format=instagram',
        twitter: '/api/card/danny-carey?format=twitter',
        stats: '/api/card/danny-carey?type=stats',
        spotlight: '/api/card/danny-carey?type=spotlight',
      },
    },
    {
      slug: 'chris-adler',
      name: 'Chris Adler',
      band: 'Lamb of God',
      genre: 'Groove Metal',
      country: 'USA',
      stats: { totalPieces: 32, totalCost: 18500 },
      cardUrls: {
        instagram: '/api/card/chris-adler?format=instagram',
        twitter: '/api/card/chris-adler?format=twitter',
        stats: '/api/card/chris-adler?type=stats',
        spotlight: '/api/card/chris-adler?type=spotlight',
      },
    },
    {
      slug: 'george-kollias',
      name: 'George Kollias',
      band: 'Nile',
      genre: 'Death Metal',
      country: 'Greece',
      stats: { totalPieces: 36, totalCost: 22800 },
      cardUrls: {
        instagram: '/api/card/george-kollias?format=instagram',
        twitter: '/api/card/george-kollias?format=twitter',
        stats: '/api/card/george-kollias?type=stats',
        spotlight: '/api/card/george-kollias?type=spotlight',
      },
    },
    {
      slug: 'mike-portnoy',
      name: 'Mike Portnoy',
      band: 'Dream Theater',
      genre: 'Progressive Metal',
      country: 'USA',
      stats: { totalPieces: 55, totalCost: 38000 },
      cardUrls: {
        instagram: '/api/card/mike-portnoy?format=instagram',
        twitter: '/api/card/mike-portnoy?format=twitter',
        stats: '/api/card/mike-portnoy?type=stats',
        spotlight: '/api/card/mike-portnoy?type=spotlight',
      },
    },
    {
      slug: 'vinnie-paul',
      name: 'Vinnie Paul',
      band: 'Pantera',
      genre: 'Groove Metal',
      country: 'USA',
      stats: { totalPieces: 44, totalCost: 28500 },
      cardUrls: {
        instagram: '/api/card/vinnie-paul?format=instagram',
        twitter: '/api/card/vinnie-paul?format=twitter',
        stats: '/api/card/vinnie-paul?type=stats',
        spotlight: '/api/card/vinnie-paul?type=spotlight',
      },
    },
    {
      slug: 'charlie-benante',
      name: 'Charlie Benante',
      band: 'Anthrax',
      genre: 'Thrash Metal',
      country: 'USA',
      stats: { totalPieces: 38, totalCost: 25800 },
      cardUrls: {
        instagram: '/api/card/charlie-benante?format=instagram',
        twitter: '/api/card/charlie-benante?format=twitter',
        stats: '/api/card/charlie-benante?type=stats',
        spotlight: '/api/card/charlie-benante?type=spotlight',
      },
    },
    {
      slug: 'igor-cavalera',
      name: 'Igor Cavalera',
      band: 'Sepultura',
      genre: 'Thrash/Groove Metal',
      country: 'Brazil',
      stats: { totalPieces: 28, totalCost: 18000 },
      cardUrls: {
        instagram: '/api/card/igor-cavalera?format=instagram',
        twitter: '/api/card/igor-cavalera?format=twitter',
        stats: '/api/card/igor-cavalera?type=stats',
        spotlight: '/api/card/igor-cavalera?type=spotlight',
      },
    },
    {
      slug: 'nicko-mcbrain',
      name: 'Nicko McBrain',
      band: 'Iron Maiden',
      genre: 'Heavy Metal',
      country: 'UK',
      stats: { totalPieces: 42, totalCost: 35000 },
      cardUrls: {
        instagram: '/api/card/nicko-mcbrain?format=instagram',
        twitter: '/api/card/nicko-mcbrain?format=twitter',
        stats: '/api/card/nicko-mcbrain?type=stats',
        spotlight: '/api/card/nicko-mcbrain?type=spotlight',
      },
    },
    {
      slug: 'abe-cunningham',
      name: 'Abe Cunningham',
      band: 'Deftones',
      genre: 'Alternative Metal',
      country: 'USA',
      stats: { totalPieces: 30, totalCost: 24000 },
      cardUrls: {
        instagram: '/api/card/abe-cunningham?format=instagram',
        twitter: '/api/card/abe-cunningham?format=twitter',
        stats: '/api/card/abe-cunningham?type=stats',
        spotlight: '/api/card/abe-cunningham?type=spotlight',
      },
    },
    {
      slug: 'brann-dailor',
      name: 'Brann Dailor',
      band: 'Mastodon',
      genre: 'Progressive Metal',
      country: 'USA',
      stats: { totalPieces: 34, totalCost: 28000 },
      cardUrls: {
        instagram: '/api/card/brann-dailor?format=instagram',
        twitter: '/api/card/brann-dailor?format=twitter',
        stats: '/api/card/brann-dailor?type=stats',
        spotlight: '/api/card/brann-dailor?type=spotlight',
      },
    },
    {
      slug: 'mario-duplantier',
      name: 'Mario Duplantier',
      band: 'Gojira',
      genre: 'Progressive Death Metal',
      country: 'France',
      stats: { totalPieces: 32, totalCost: 19500 },
      cardUrls: {
        instagram: '/api/card/mario-duplantier?format=instagram',
        twitter: '/api/card/mario-duplantier?format=twitter',
        stats: '/api/card/mario-duplantier?type=stats',
        spotlight: '/api/card/mario-duplantier?type=spotlight',
      },
    },
    {
      slug: 'eloy-casagrande',
      name: 'Eloy Casagrande',
      band: 'Sepultura/Slipknot',
      genre: 'Thrash/Nu Metal',
      country: 'Brazil',
      stats: { totalPieces: 38, totalCost: 26500 },
      cardUrls: {
        instagram: '/api/card/eloy-casagrande?format=instagram',
        twitter: '/api/card/eloy-casagrande?format=twitter',
        stats: '/api/card/eloy-casagrande?type=stats',
        spotlight: '/api/card/eloy-casagrande?type=spotlight',
      },
    },
    {
      slug: 'inferno',
      name: 'Inferno',
      band: 'Behemoth',
      genre: 'Black/Death Metal',
      country: 'Poland',
      stats: { totalPieces: 40, totalCost: 28000 },
      cardUrls: {
        instagram: '/api/card/inferno?format=instagram',
        twitter: '/api/card/inferno?format=twitter',
        stats: '/api/card/inferno?type=stats',
        spotlight: '/api/card/inferno?type=spotlight',
      },
    },
    {
      slug: 'flo-mounier',
      name: 'Flo Mounier',
      band: 'Cryptopsy',
      genre: 'Technical Death Metal',
      country: 'Canada',
      stats: { totalPieces: 35, totalCost: 22000 },
      cardUrls: {
        instagram: '/api/card/flo-mounier?format=instagram',
        twitter: '/api/card/flo-mounier?format=twitter',
        stats: '/api/card/flo-mounier?type=stats',
        spotlight: '/api/card/flo-mounier?type=spotlight',
      },
    },
    {
      slug: 'hellhammer',
      name: 'Hellhammer',
      band: 'Mayhem',
      genre: 'Black Metal',
      country: 'Norway',
      stats: { totalPieces: 36, totalCost: 21500 },
      cardUrls: {
        instagram: '/api/card/hellhammer?format=instagram',
        twitter: '/api/card/hellhammer?format=twitter',
        stats: '/api/card/hellhammer?type=stats',
        spotlight: '/api/card/hellhammer?type=spotlight',
      },
    },
    {
      slug: 'pete-sandoval',
      name: 'Pete Sandoval',
      band: 'Morbid Angel',
      genre: 'Death Metal',
      country: 'USA',
      stats: { totalPieces: 38, totalCost: 24000 },
      cardUrls: {
        instagram: '/api/card/pete-sandoval?format=instagram',
        twitter: '/api/card/pete-sandoval?format=twitter',
        stats: '/api/card/pete-sandoval?type=stats',
        spotlight: '/api/card/pete-sandoval?type=spotlight',
      },
    },
  ];

  res.setHeader('Cache-Control', 'public, s-maxage=3600, stale-while-revalidate=86400');
  res.status(200).json({
    total: cards.length,
    cards,
    formats: ['instagram', 'twitter'],
    types: ['full', 'stats', 'spotlight'],
    usage: {
      full: 'Complete gear list with drummer info - best for social sharing',
      stats: 'Key statistics (pieces count, total cost) - great for quick sharing',
      spotlight: 'Focus on signature gear - ideal for brand highlights',
    },
  });
}
