// /api/article-preview/:slug — tiny {title, description} payload for one
// album drum-setup article. Issue #8452 (L4 perf watch): /articles/:slug
// shares TopListPage with /lists/:slug, but only the list route ever got the
// critical-hero swap from #7148 — article pages still show the generic
// static hero (title/description that don't match the article) until the
// whole per-drummer chunk loads, so Lighthouse credits LCP to the late,
// fully-hydrated real content instead of the fast static paint.
//
// Mirrors api/list-preview/[slug].js: reads the already-committed, lightweight
// catalog (packages/frontend/data/albumArticles/albumArticlesCatalog.js,
// generated by scripts/generate-album-articles-catalog.mjs for #7149) instead
// of the full per-drummer article body.
import { ALBUM_ARTICLES_META } from '../../packages/frontend/data/albumArticles/albumArticlesCatalog.js';

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Cache-Control', 'public, s-maxage=86400, stale-while-revalidate=604800');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  const { slug } = req.query;
  const article = ALBUM_ARTICLES_META[slug];

  if (!article) {
    return res.status(404).json({ error: 'Article not found' });
  }

  res.status(200).json({
    title: article.title,
    description: article.description,
  });
}
