// Vercel Serverless Function - sitemap.xml
// Issue #361: Added band pages
// Issue #339: Added gear category pages for SEO
// Issue #344: Added drumming technique pages
// Issue #345: Added gear comparison pages
// Issue #785: Import albumArticles dynamically from data source

import { ALBUM_ARTICLES } from '../packages/frontend/data/albumArticles.js';
// Issue #994 (split 3/3 of #870): source technique slugs for the new
// /technique/<slug>/drummers pages directly from the data module so the
// sitemap stays in sync as techniques are added.
// Issue #4771: getAllTechniques additionally sources each technique's real
// (non-fabricated) video, for the video:video sitemap extension below.
import { getAllTechniqueSlugs, getAllTechniques } from '../packages/frontend/data/techniques.js';
// Issue #997 (split 3/4 of #871): source the /gear/<brand>/<series>/drummers-using
// slugs from the generated gear index so the sitemap stays in sync with the
// pages added in #996. We import the self-contained GEAR_INDEX data directly
// (rather than data/gearSeriesPages.js, which pulls in pricing/affiliate
// helpers) and mirror that module's slug + dedupe logic verbatim so the URLs
// emitted here resolve 1:1 with the live routes.
import { GEAR_INDEX, GEAR_INDEX_BRAND_LEVEL } from '../packages/frontend/data/gearIndex.js';
// Issue #1056: derive the signature-lick page + hub URLs directly from the
// composed SIGNATURE_LICKS data (now modularized under data/licks/) instead of
// hand-maintaining two parallel arrays here. New lick batches add a per-drummer
// file and auto-appear in the sitemap — no manual edit, no second conflict surface.
import { SIGNATURE_LICKS } from '../packages/frontend/data/signatureLicks.js';
// Issue #1125: source the full drummer roster WITH gear records so the
// /drummer/<slug>/<category> long-tail pages are declared for every drummer
// that has real data in a category (not just 16 hardcoded names). Same module
// the renderer api/gear/[slug]/[category].js reads, so URLs ↔ pages stay 1:1.
import { drummers as DRUMMER_GEAR_DATA } from './drummers/index.js';
// Issue #1171: source all 19 band slugs from the canonical data module so the
// sitemap stays in sync as bands are added, and URLs match the live /bands/ route.
import { bands as BAND_DATA } from '../packages/frontend/data/bands.js';
// Issue #1276: per-pair LLM comparison Markdown files — source slugs from the
// canonical drummerComparisons data so /llms/vs/<slug>.md URLs stay 1:1 with
// the files generated by scripts/generate-llms-vs.cjs.
import { getAllDrummerComparisonSlugs } from '../packages/frontend/data/drummerComparisons.js';
// Issue #1475: drummer gear evolution pages — source slugs from the canonical
// data module so /drummers/<slug>/evolution URLs stay 1:1 with live routes.
import { DRUMMER_EVOLUTION } from '../packages/frontend/data/drummerEvolution.js';
// Issue #1473: individual /battles/<slug> pages — 8 curated matchups with
// SEO-targeted titles for "X vs Y drum kit" long-tail queries.
import { CURATED_MATCHUPS } from '../packages/frontend/data/battles.js';
// Issue #1794: Genre gear guide pages — /guides/best-[gear]-for-[genre]
import { GENRE_GEAR_GUIDES } from '../packages/frontend/data/genreGearGuides.js';
// Issue #1799: Genre hub + 8 genre landing pages
import { getAllGenreSlugs } from '../packages/frontend/data/genres.js';
// Issue #2403: kit-level /gear/:brand/:series/drummers-using pages (12 scaffold slugs).
import { DRUMMERS_BY_KIT } from '../packages/frontend/data/drummersByKit.js';
// Issue #2726: source top-10 list slugs from canonical data module so sitemap
// stays in sync when new list pages ship.
import { TOP_10_LISTS } from '../packages/frontend/data/top10Lists.js';
// Issue #4764 (phase 1/3 of epic #4763): /studies registry — sitemap entries
// derive from it so a new study only needs registering in one place.
import { STUDIES } from '../packages/frontend/data/studies/index.js';
// Issue #4760 (songs epic #4758, phase 2/4): /songs hub + tempo/flagship/
// drummer list pages — tempo tiers and drummer counts derive from the same
// module the pages themselves read, so the sitemap can't drift out of sync.
import { getTempoTiers, getDrummersWithSongCounts, getSongPageSlugs } from '../packages/frontend/data/metalSongsBpm.js';
// Issue #3661: source gear-history and sound-like-guide slugs from their
// canonical data modules (same pattern as above) so the sitemap can never
// drift out of sync with these two data files again.
import { GEAR_PRICE_HISTORY } from '../packages/frontend/data/gearPriceHistory.js';
import { SOUND_LIKE_GUIDES } from '../packages/frontend/data/soundLikeGuides.js';
// Issue #4138 (phase 3/4 of epic #4135): /drumsticks/signature/<drummer> pages —
// source slugs from the verified drummer→stick mapping so the sitemap only ever
// lists drummers with a confirmed signature stick (no thin pages).
import { DRUMMER_STICKS } from '../packages/frontend/data/drumsticks.js';
// Issue #4137 (phase 2/4 of epic #4135): /drumsticks hub + reference pages.
import { REFERENCE_PAGE_ORDER } from '../packages/frontend/data/drumstickReferencePages.js';
// Issue #4139 (phase 4/4 of epic #4135): /drumsticks/brands + per-brand pages.
import { DRUMSTICK_BRANDS } from '../packages/frontend/data/drumstickBrands.js';
// Issue #4305 (phase 2/4 of epic #4303): /cymbals hub + reference pages.
import { REFERENCE_PAGE_ORDER as CYMBAL_REFERENCE_PAGE_ORDER } from '../packages/frontend/data/cymbalReferencePages.js';
// Issue #4310 (phase 2/4 of epic #4308): /snares hub + reference pages.
import { REFERENCE_PAGE_ORDER as SNARE_REFERENCE_PAGE_ORDER } from '../packages/frontend/data/snareReferencePages.js';
// Issue #4392 (phase 2/4 of epic #4387): /pedals hub + reference pages.
import { REFERENCE_PAGE_ORDER as PEDAL_REFERENCE_PAGE_ORDER } from '../packages/frontend/data/pedalReferencePages.js';
// Issue #4311 (phase 3/4 of epic #4308): /snares/signature/<drummer> pages —
// source slugs from the verified isSignature: true snare records so the
// sitemap only ever lists drummers with a confirmed signature snare (no thin pages).
import { SIGNATURE_SNARES } from '../packages/frontend/data/snares.js';
// Issue #4307 (phase 4/4 of epic #4303): /cymbals/brands + per-brand pages.
import { CYMBAL_BRANDS } from '../packages/frontend/data/cymbalBrands.js';
// Issue #4306 (phase 3/4 of epic #4303): /cymbals/setups/<drummer> pages —
// source slugs from the verified drummer→cymbal setup mapping so the sitemap
// only ever lists drummers with a confirmed setup (no thin pages).
import { DRUMMER_CYMBALS } from '../packages/frontend/data/cymbalSetups.js';
// Issue #4274: Endorsement Tracker pages — source slugs directly from
// ENDORSEMENT_TIMELINE so the sitemap can never drift out of sync again.
import { ENDORSEMENT_TIMELINE } from '../packages/frontend/data/endorsementNews.js';
// Issue #4393 (phase 3/4 of epic #4387): /pedals/setups/<drummer> pages —
// source slugs from the verified drummer→pedal mapping so the sitemap only
// ever lists drummers with a confirmed pedal (no thin pages).
import { DRUMMER_PEDALS } from '../packages/frontend/data/pedals.js';
// Issue #4432 (split 1/3 of #4394): /pedals/brands/<brand> pages.
import { PEDAL_BRANDS } from '../packages/frontend/data/pedalBrands.js';
// Issue #4483: /snares/brands + per-brand pages.
import { SNARE_BRANDS } from '../packages/frontend/data/snareBrands.js';
// Issue #4453: /brands/<slug> + /llms/brands/<slug>.md pages — source slugs
// from the canonical brands data module so the sitemap stays in sync as
// brands are added (was hardcoded to 10 of 18 live brands).
import { getAllBrands } from '../packages/frontend/data/brands.js';

// Issue #4201: Content Scale Sprint - All 65 drummers now in sitemap
const drummers = [
  { id: 1, name: 'Lars Ulrich' }, { id: 2, name: 'Joey Jordison' }, { id: 3, name: 'Gene Hoglan' },
  { id: 4, name: 'Dave Lombardo' }, { id: 5, name: 'Tomas Haake' }, { id: 6, name: 'George Kollias' },
  { id: 7, name: 'Eloy Casagrande' }, { id: 8, name: 'Ray Luzier' }, { id: 9, name: 'John Otto' },
  { id: 10, name: 'Jay Weinberg' }, { id: 11, name: 'Vinnie Paul' }, { id: 12, name: 'Charlie Benante' },
  { id: 13, name: 'Mike Portnoy' }, { id: 14, name: 'Danny Carey' }, { id: 15, name: 'Mario Duplantier' },
  { id: 16, name: 'Brann Dailor' }, { id: 17, name: 'Chris Adler' }, { id: 18, name: 'Matt Halpern' },
  { id: 19, name: 'Inferno' }, { id: 20, name: 'Hellhammer' }, { id: 21, name: 'Pete Sandoval' },
  { id: 22, name: 'Art Cruz' }, { id: 23, name: 'Arin Ilejay' }, { id: 24, name: 'Navene Koperweis' },
  { id: 25, name: 'Alex Bent' }, { id: 26, name: 'Shannon Larkin' }, { id: 27, name: 'Raymond Herrera' },
  { id: 28, name: 'Morgan Ågren' }, { id: 29, name: 'Igor Cavalera' }, { id: 30, name: 'Bill Ward' },
  { id: 31, name: 'Nick Augusto' }, { id: 32, name: 'Matt Greiner' }, { id: 33, name: 'Blake Richardson' },
  { id: 34, name: 'Ben Koller' }, { id: 35, name: 'Flo Mounier' }, { id: 36, name: 'Martin Axenrot' },
  { id: 37, name: 'Jason Bittner' },
  { id: 38, name: 'Martin Lopez' }, { id: 39, name: 'Travis Orbin' }, { id: 40, name: 'Chris Turner' },
  { id: 41, name: 'Nicko McBrain' }, { id: 42, name: 'Scott Travis' }, { id: 43, name: 'Mikkey Dee' },
  { id: 44, name: 'Derek Roddy' }, { id: 45, name: 'Dirk Verbeuren' }, { id: 46, name: 'Frost' },
  { id: 47, name: 'Gavin Harrison' }, { id: 48, name: 'Abe Cunningham' }, { id: 49, name: 'Richard Christy' },
  { id: 50, name: 'Aquiles Priester' }, { id: 51, name: 'Paul Mazurkiewicz' }, { id: 52, name: 'Mike Mangini' },
  { id: 53, name: 'Matt Garstka' }, { id: 54, name: 'Daniel Erlandsson' }, { id: 55, name: 'Jaska Raatikainen' },
  { id: 56, name: 'Hannes Grossmann' }, { id: 57, name: 'Daray' }, { id: 58, name: 'Jocke Wallgren' },
  { id: 59, name: 'Tim Yeung' }, { id: 60, name: 'Kevin Talley' }, { id: 61, name: 'Isaac Lamb' },
  { id: 62, name: 'Ryan Van Poederooyen' }, { id: 63, name: 'Paul Bostaph' },
  { id: 64, name: 'Sean Reinert' }, { id: 65, name: 'Nick Menza' },
  // Issue #4214: 2 orphan drummers with deep existing content (comparisons, licks,
  // gear history, album articles) added to the roster to stop soft-404s.
  { id: 66, name: 'Adrian Erlandsson' }, { id: 67, name: 'Jon Dette' },
  // Issue #4926: split 1/5 of #4748 — Jimmy DeGrasso (Megadeth) roster gap.
  { id: 68, name: 'Jimmy DeGrasso' },
];

const gearItems = [
  { slug: 'tama-iron-cobra-900-double-pedal', name: 'Tama Iron Cobra 900' },
  { slug: 'meinl-byzance-series-cymbals', name: 'Meinl Byzance Series' },
  { slug: 'paiste-rude-series-cymbals', name: 'Paiste RUDE Series' },
  { slug: 'zildjian-a-custom-series-cymbals', name: 'Zildjian A Custom' },
  { slug: 'vic-firth-american-classic-5b', name: 'Vic Firth 5B' },
  { slug: 'pearl-demon-drive-double-pedal', name: 'Pearl Demon Drive' },
  { slug: 'tama-starclassic-walnut-birch-drums', name: 'Tama Starclassic' },
  { slug: 'pearl-reference-series-drums', name: 'Pearl Reference' },
  { slug: 'sonor-sq2-heavy-beech-drums', name: 'Sonor SQ2' },
  { slug: 'sabian-hhx-series-cymbals', name: 'Sabian HHX' },
];

// Issue #2726: derive from TOP_10_LISTS data module (19 entries) so the sitemap
// stays in sync automatically when new list pages ship.
const top10Lists = Object.values(TOP_10_LISTS).map(l => ({ slug: l.slug, name: l.title }));

// Issue #642, #658: Article pages (SEO-optimized with /articles/:slug route)
const articles = [
  { slug: 'most-expensive-drum-setups', name: 'Top 10 Most Expensive Metal Drum Setups' },
  { slug: 'fastest-double-bass-drummers', name: 'Top 10 Fastest Double Bass Drummers in Metal' },
  { slug: 'most-brutal-drum-solos', name: 'Top 10 Most Brutal Drum Solos in Metal History' },
];

// Issue #663: Album gear breakdown articles
// Issue #785: Dynamically generate albumArticles from ALBUM_ARTICLES data source
const albumArticles = Object.keys(ALBUM_ARTICLES).map(slug => ({
  slug,
  name: ALBUM_ARTICLES[slug].albumTitle 
    ? `${ALBUM_ARTICLES[slug].albumTitle} Drum Setup`
    : ALBUM_ARTICLES[slug].title || slug
}));

// Issue #1171: derive slugs from BAND_DATA (19 entries) instead of a hardcoded 2-entry list.
const bandPages = Object.keys(BAND_DATA);

// Issue #339: Gear category pages for SEO
const gearCategories = [
  { slug: 'drums', name: 'Metal Drum Kits' },
  // 'sticks' removed: /gear/sticks 301s to /drumsticks (already in this sitemap)
  // 'cymbals' removed: /gear/cymbals 301s to /cymbals (already in this sitemap)
  // 'snares' removed: /gear/snares 301s to /snares (already in this sitemap)
  // 'pedals' removed: /gear/pedals 301s to /pedals (already in this sitemap) — Issue #4434
  { slug: 'hardware', name: 'Metal Drum Hardware' },
];

// Issue #344: Drumming technique pages
const techniques = [
  { slug: 'blast-beat', name: 'Blast Beat' },
  { slug: 'double-bass', name: 'Double Bass Drumming' },
  { slug: 'gravity-blast', name: 'Gravity Blast' },
  { slug: 'polyrhythms', name: 'Polyrhythms' },
  { slug: 'odd-time-signatures', name: 'Odd Time Signatures' },
  { slug: 'one-handed-roll', name: 'One-Handed Roll' },
  { slug: 'triggered-drums', name: 'Triggered Drums' },
  { slug: 'groove-drumming', name: 'Groove Metal Drumming' },
  { slug: 'linear-drumming', name: 'Linear Drumming' },
  { slug: 'fill-techniques', name: 'Metal Drum Fills' },
  { slug: 'ghost-notes', name: 'Ghost Notes' },
  { slug: 'rudiments', name: 'Rudiments & Stick Control' },
  { slug: 'hand-foot-independence', name: 'Hand-Foot Independence' },
];

// Issue #656: Gear brand landing pages for SEO
// Issue #4453: sourced from getAllBrands() instead of a hand-maintained list
// so this can never drift out of sync with packages/frontend/data/brands.js
// again (was stuck at 10 of 18 live brands).
const gearBrands = getAllBrands().map(b => ({ slug: b.slug, name: b.name, type: b.type }));

// Issue #345: Gear comparison pages for SEO
const gearComparisons = [
  { slug: 'tama-vs-pearl', name: 'Tama vs Pearl Drums' },
  { slug: 'meinl-vs-zildjian', name: 'Meinl vs Zildjian Cymbals' },
  { slug: 'tama-iron-cobra-vs-pearl-demon-drive', name: 'Tama Iron Cobra vs Pearl Demon Drive' },
  { slug: 'paiste-vs-sabian', name: 'Paiste vs Sabian Cymbals' },
  { slug: 'tama-slp-vs-pearl-sensitone', name: 'Tama SLP vs Pearl Sensitone' },
  { slug: 'sonor-vs-dw', name: 'Sonor vs DW Drums' },
  { slug: 'zildjian-vs-sabian', name: 'Zildjian vs Sabian Cymbals' },
  // Issue #4124: SEO batch - 3 new brand comparison pages
  { slug: 'dw-vs-tama', name: 'DW vs Tama Drums' },
  { slug: 'mapex-vs-pearl', name: 'Mapex vs Pearl Drums' },
  { slug: 'sabian-vs-meinl', name: 'Sabian vs Meinl Cymbals' },
  // Issue #4127: SEO batch - 2 Ludwig brand comparison pages
  { slug: 'ludwig-vs-tama', name: 'Ludwig vs Tama Drums' },
  { slug: 'ludwig-vs-dw', name: 'Ludwig vs DW Drums' },
];

// Issue #558, #598, #650: Drummer vs Drummer comparison pages for SEO
// Issue #650: Generate ALL drummer comparison pairs dynamically (65 drummers = 2080 pairs)
function generateAllDrummerComparisons(drummerList) {
  const comparisons = [];
  for (let i = 0; i < drummerList.length; i++) {
    for (let j = i + 1; j < drummerList.length; j++) {
      const slug1 = generateSlug(drummerList[i].name);
      const slug2 = generateSlug(drummerList[j].name);
      // Alphabetical order for consistency
      const orderedSlug = slug1 < slug2 ? `${slug1}-vs-${slug2}` : `${slug2}-vs-${slug1}`;
      comparisons.push({
        slug: orderedSlug,
        name: `${drummerList[i].name} vs ${drummerList[j].name}`
      });
    }
  }
  return comparisons;
}
const drummerComparisons = generateAllDrummerComparisons(drummers);

// SITEMAP DIET (founder-approved 2026-07-16): the all-pairs /vs/ matrix above
// (67 drummers → 2,211 pages) shows ~zero search demand — 2 of 335 queries
// with impressions in the 2026-07-13 GSC snapshot. Listing all of them told
// Google two-thirds of our site is thin combinatorial content, diluting crawl
// budget for the pages that earn traffic. Only pairs where BOTH drummers are
// demand-evidenced entities (earning GSC impressions on their own head terms)
// stay in the sitemap. The other /vs/ pages REMAIN LIVE and reachable — they
// are just no longer flagged to Google as index-worthy. Update this set from
// GSC evidence, not intuition; removing a slug here is reversible.
const VS_DEMAND_DRUMMERS = new Set([
  'joey-jordison', 'eloy-casagrande', 'mario-duplantier', 'bill-ward',
  'john-otto', 'shannon-larkin', 'matt-greiner', 'jay-weinberg',
  'dirk-verbeuren', 'nick-menza', 'aquiles-priester', 'igor-cavalera',
  'nicko-mcbrain', 'mike-portnoy', 'tomas-haake', 'gene-hoglan',
  'george-kollias', 'danny-carey', 'dave-lombardo', 'lars-ulrich',
  'hellhammer', 'jocke-wallgren', 'nick-augusto', 'ray-luzier',
]);
const sitemapDrummerComparisons = drummerComparisons.filter(c => {
  const [a, b] = c.slug.split('-vs-');
  return VS_DEMAND_DRUMMERS.has(a) && VS_DEMAND_DRUMMERS.has(b);
});

// Issue #685 / #3661: "How to Sound Like" guides - SEO content hub, sourced
// directly from the canonical data module so the sitemap stays in sync as
// new guides ship (no hand-maintained duplicate list to drift).
const soundLikeGuides = Object.values(SOUND_LIKE_GUIDES).map(g => ({ slug: g.slug, name: g.title || g.name }));

// Issue #702: Beginner gear guides - SEO content hub
const beginnerGuides = [
  { slug: 'beginner-metal-drummer-setup', name: 'The Ultimate Beginner Metal Drummer Gear Guide Under $1000' },
  // Issue #833: $500 budget tier guide
  { slug: 'budget-metal-drum-setup-500', name: 'The Best Budget Metal Drum Setup Under $500' },
  // Issue #834: $1000 mid-tier budget guide (split 2/3 of #830)
  { slug: 'budget-metal-drum-setup-1000', name: 'The Best Metal Drum Setup Under $1000' },
  // Issue #835: $2000 pro-tier budget guide (split 3/3 of #830)
  { slug: 'budget-metal-drum-setup-2000', name: 'The Best Metal Drum Setup Under $2000' },
];

// Issue #704: Metal Drummer Name Generator - viral tool
const toolPages = [
  { slug: 'metal-drummer-name-generator', name: 'Metal Drummer Name Generator' },
];

// Issue #4634 / #4645: genre-gear-guide llms mirrors (public/llms/guides/best-*.md).
// GENRE_GEAR_GUIDES has 278 entries and every slug is "best-*" prefixed. #4634
// wired in only the 49 slugs that had a hand-authored .md file at the time;
// #4645 (scripts/generate-llms-genre-gear-guides.cjs) generated the remaining
// 229 mechanically from the data module fields, so every slug now has a real
// file on disk — source the full list directly instead of hand-maintaining a
// duplicate array that drifts as new guides ship.
const genreGearGuideMdSlugs = Object.keys(GENRE_GEAR_GUIDES);

// Issue #732: Top 20 Gear Comparison Tool pairs for SEO
// High-traffic matchups for auto-generation
const top20GearComparisons = [
  { d1: 'joey-jordison', d2: 'lars-ulrich' },
  { d1: 'lars-ulrich', d2: 'dave-lombardo' },
  { d1: 'joey-jordison', d2: 'george-kollias' },
  { d1: 'mario-duplantier', d2: 'tomas-haake' },
  { d1: 'mike-portnoy', d2: 'danny-carey' },
  { d1: 'gene-hoglan', d2: 'pete-sandoval' },
  { d1: 'hellhammer', d2: 'inferno' },
  { d1: 'brann-dailor', d2: 'mario-duplantier' },
  { d1: 'dave-lombardo', d2: 'gene-hoglan' },
  { d1: 'matt-halpern', d2: 'alex-bent' },
  { d1: 'nicko-mcbrain', d2: 'vinnie-paul' },
  { d1: 'charlie-benante', d2: 'dave-lombardo' },
  { d1: 'eloy-casagrande', d2: 'joey-jordison' },
  { d1: 'george-kollias', d2: 'flo-mounier' },
  { d1: 'danny-carey', d2: 'tomas-haake' },
  { d1: 'chris-adler', d2: 'brann-dailor' },
  { d1: 'joey-jordison', d2: 'vinnie-paul' },
  { d1: 'matt-garstka', d2: 'matt-halpern' },
  { d1: 'inferno', d2: 'george-kollias' },
  { d1: 'mike-portnoy', d2: 'mike-mangini' },
];

// Issue #4889: drummerComparisons.js has 226 hand-curated pairs with real
// verdict/pros/cons content (same data #4885 wired into the FAQ schema), but
// the sitemap only ever declared the 20 above, leaving 206 live, crawlable
// pages with zero discovery path. Union rather than replace: 7 of the top20
// pairs above aren't in the 226 curated set at all (they render the route's
// generic fallback content, not a curated verdict) and 2 more only match the
// curated set in REVERSED slug order — replacing top20GearComparisons
// wholesale would silently swap already-indexed URLs, which URLs-immutable
// forbids. So every top20 URL is kept exactly as shipped, and curated slugs
// are added only for pairs not already covered by a top20 URL in either order.
const top20SlugPairs = new Set();
top20GearComparisons.forEach(c => {
  top20SlugPairs.add(`${c.d1}-vs-${c.d2}`);
  top20SlugPairs.add(`${c.d2}-vs-${c.d1}`);
});
const curatedToolsCompareSlugs = [
  ...top20GearComparisons.map(c => `${c.d1}-vs-${c.d2}`),
  ...getAllDrummerComparisonSlugs().filter(slug => !top20SlugPairs.has(slug)),
];

// Issue #739: Signature Gear Spotlight pages
const signatureGearPages = [
  { drummerSlug: 'joey-jordison', gearSlug: 'joey-jordison-pearl-signature-snare', name: 'Pearl Joey Jordison Signature Snare' },
  { drummerSlug: 'lars-ulrich', gearSlug: 'lars-ulrich-paiste-rude-china', name: 'Paiste 20" RUDE Wild China' },
  { drummerSlug: 'danny-carey', gearSlug: 'danny-carey-paiste-giant-beat-gongs', name: 'Paiste Giant Beat Gongs' },
  { drummerSlug: 'mario-duplantier', gearSlug: 'mario-duplantier-tama-starphonic-bronze', name: 'Tama Starphonic Bronze' },
  { drummerSlug: 'gene-hoglan', gearSlug: 'gene-hoglan-pearl-reference-kit', name: 'Pearl Reference Pure Kit' },
  { drummerSlug: 'dave-lombardo', gearSlug: 'dave-lombardo-promark-2bx-signature', name: 'Promark Dave Lombardo Signature 2Bx' },
  { drummerSlug: 'tomas-haake', gearSlug: 'tomas-haake-sonor-signature-snare', name: 'Sonor Tomas Haake Signature Snare' },
];

// Issue #749 / #1056: Signature Licks pages — derived from SIGNATURE_LICKS so new
// per-drummer lick modules auto-appear in the sitemap (no hand-maintained list).
const signatureLicksPages = Object.values(SIGNATURE_LICKS).map(lick => ({
  drummerSlug: lick.drummerSlug,
  lickSlug: lick.slug,
  name: lick.name,
}));

// Issue #4771: video sitemap extension (<video:video>) — one entry per page
// that carries a VideoObject in api/meta/[...path].js's JSON-LD, built from
// the same data modules the meta layer reads (SIGNATURE_LICKS, techniques.js)
// rather than a hand-maintained second video registry. The audit script
// (scripts/audit-video-seo.mjs) cross-checks this against the meta layer's
// real output so the two can't silently drift apart.
function youtubeVideoEntry({ youtubeId, title, description, contentUrl }) {
  return {
    thumbnailLoc: `https://i.ytimg.com/vi/${youtubeId}/hqdefault.jpg`,
    title,
    description,
    contentLoc: contentUrl || `https://www.youtube.com/watch?v=${youtubeId}`,
    playerLoc: `https://www.youtube.com/embed/${youtubeId}`,
  };
}

// Signature lick pages: primary performance video if present, else the
// tutorial video — mirrors the fallback in api/meta/[...path].js's
// lickPageMatch block (both the JSON-LD VideoObject and the #3698 SSR iframe
// use this same fallback as of #4771).
const lickVideoByLoc = {};
for (const lick of Object.values(SIGNATURE_LICKS)) {
  const source = lick.video?.youtubeId ? lick.video : (lick.tutorial?.youtubeId ? lick.tutorial : null);
  if (!source) continue;
  lickVideoByLoc[`/drummers/${lick.drummerSlug}/licks/${lick.slug}`] = youtubeVideoEntry({
    youtubeId: source.youtubeId,
    title: source.title || lick.name,
    description: source.description || lick.description || `${lick.name} — ${lick.drummerName}`,
  });
}

// Technique pages with a real (non-fabricated) YouTube URL — mirrors the
// technique-page VideoObject block in api/meta/[...path].js (#4767/#4771).
const techniqueVideoBySlug = {};
for (const technique of getAllTechniques()) {
  const firstVideo = (technique.videos || []).find(v => /(?:youtube\.com\/watch\?v=|youtu\.be\/)[a-zA-Z0-9_-]{11}/.test(v.url || ''));
  if (!firstVideo) continue;
  const youtubeId = firstVideo.url.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/)([a-zA-Z0-9_-]{11})/)[1];
  techniqueVideoBySlug[technique.slug] = youtubeVideoEntry({
    youtubeId,
    title: firstVideo.title,
    description: `${firstVideo.title} — ${technique.title} demonstrated for metal drummers.`,
    contentUrl: firstVideo.url,
  });
}

// Drummers with licks hub pages — distinct drummerSlugs in first-appearance order.
const drummerLicksHubs = Object.values(SIGNATURE_LICKS).reduce((hubs, lick) => {
  if (!hubs.some(h => h.drummerSlug === lick.drummerSlug)) {
    hubs.push({ drummerSlug: lick.drummerSlug, name: lick.drummerName });
  }
  return hubs;
}, []);

// Issue #802 / #4274: Endorsement Tracker pages — derive directly from
// ENDORSEMENT_TIMELINE so this list can never drift out of sync again (same
// pattern as gearPriceHistoryDrummers below).
const endorsementDrummers = Object.keys(ENDORSEMENT_TIMELINE);

// Issue #813 / #3661: Gear Price History Tracker pages — inflation-adjusted
// setup costs over time, sourced directly from the canonical data module so
// the sitemap stays in sync as new drummers are added (no hand-maintained
// duplicate list to drift).
const gearPriceHistoryDrummers = Object.keys(GEAR_PRICE_HISTORY);

// Issue #1473: Individual /battles/<slug> pages — derive slugs from CURATED_MATCHUPS
// so the sitemap stays in sync as matchups are added or changed.
const drummerIdToSlugMap = {};
for (const d of drummers) {
  drummerIdToSlugMap[d.id] = generateSlug(d.name);
}
const battleSlugs = CURATED_MATCHUPS.map(m => {
  const s1 = drummerIdToSlugMap[m.drummer1Id];
  const s2 = drummerIdToSlugMap[m.drummer2Id];
  return s1 && s2 ? `${s1}-vs-${s2}` : null;
}).filter(Boolean);

// Issue #770 / #1125: Drummer Gear Category Pages — long-tail keyword pages at
// /drummer/<slug>/<category>. The renderer api/gear/[slug]/[category].js serves
// a real page iff `drummer.gear[category]` is populated (else 404). We mirror
// that exact gate here and emit a URL for EVERY drummer × category that has real
// gear data, extending coverage from 16 hardcoded "priority" drummers to the
// full roster — while guaranteeing every declared URL resolves to a substantive
// page (no thin/404 pages).
// Issue #4327: no drummer record carries a `gear.pedals` field — pedal gear
// only ever exists as free text inside `gear.hardware` — so `pedals` needs the
// same keyword extraction the renderer now uses, not a raw field lookup.
const GEAR_CATEGORIES = ['cymbals', 'drums', 'pedals', 'hardware', 'snare', 'sticks', 'heads'];
const PEDAL_KEYWORDS = ['pedal', 'cobra', 'demon', 'eliminator', 'speed'];
function extractPedals(hardwareString) {
  if (!hardwareString) return null;
  const items = hardwareString.split(/[,;]/).map(i => i.trim());
  const pedals = items.filter(item => PEDAL_KEYWORDS.some(kw => item.toLowerCase().includes(kw)));
  return pedals.length > 0 ? pedals.join(', ') : null;
}
// Same presence check the renderer uses to decide a category section exists.
function drummerHasCategoryGear(drummer, category) {
  if (category === 'pedals') return Boolean(extractPedals(drummer.gear?.hardware));
  return Boolean(drummer.gear && drummer.gear[category]);
}
const drummerGearCategoryPages = [];
for (const d of DRUMMER_GEAR_DATA) {
  for (const category of GEAR_CATEGORIES) {
    if (drummerHasCategoryGear(d, category)) {
      drummerGearCategoryPages.push({ drummerSlug: generateSlug(d.name), category });
    }
  }
}

// Issue #1021 (split 3/4 of #1017): LLM-facing Markdown surface.
// Static files live in public/llms/*.md and public/llms/drummers/<slug>.md.
// Listing them in the sitemap makes them crawlable, not just discoverable
// via prose links in llms.txt. Every roster member has a committed
// public/llms/drummers/<slug>.md profile.
// Issue #4276: derive from `drummers` instead of hand-maintaining a duplicate
// slug list — this list drifted twice (61/67, then 65/67, fixed by #4273)
// because nothing kept it in sync when the roster grew.
const llmsDrummerSlugs = drummers.map(d => generateSlug(d.name)).sort();

const BASE_URL = 'https://metalforge.io';

// Issue #1072: stop stamping <lastmod>=today on every URL every crawl.
// Google discards a site-wide lastmod it observes to be inaccurate, so a
// churning all-URLs-same-date-every-fetch value forfeits the crawl-freshness
// signal. Use a single STABLE release date for pages without a verifiable
// per-URL date; bump it only on material content releases (never wire it back
// to new Date()). Article URLs override this with their real ALBUM_ARTICLES
// dateModified via the per-entry `lastmod` field below.
const SITE_LASTMOD = '2026-06-26';

// Real per-URL date if the entry carries a verifiable one, else the stable
// site-wide release date.
function lastmodFor(url) {
  return url.lastmod || SITE_LASTMOD;
}

function generateSlug(name) {
  return name.toLowerCase()
    .replace(/[åä]/g, 'a').replace(/ö/g, 'o').replace(/ü/g, 'u')
    .replace(/é|è|ê|ë/g, 'e').replace(/í|ì|î|ï/g, 'i').replace(/ó|ò|ô/g, 'o')
    .replace(/ú|ù|û/g, 'u').replace(/ñ/g, 'n').replace(/ß/g, 'ss')
    .replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
}

function xmlEscape(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Issue #1274: slug→band lookup for drummer image sitemap entries.
const drummerBandBySlug = {};
for (const d of DRUMMER_GEAR_DATA) {
  drummerBandBySlug[generateSlug(d.name)] = d.band || null;
}

// Issue #4760 (songs epic #4758, phase 2/4): /songs/drummer/<slug> pages only
// exist for roster drummers (this file's own `drummers` array — the same set
// that generates the /drummer/<slug> entries below) with >= 3 songs in
// metalSongsBpm.js, matching the SongsByDrummerPage gate.
const songRosterSlugs = new Set(drummers.map(d => generateSlug(d.name)));
const songsQualifyingDrummers = getDrummersWithSongCounts().filter(d => songRosterSlugs.has(d.drummer));

// Issue #997: gear/series "drummers-using" page URLs.
// Mirrors slugifySeries + the dedupe rule in
// packages/frontend/data/gearSeriesPages.js so these <loc>s match the
// routes #996 actually serves. Only series with ≥2 drummers earn a page,
// and the first series to claim a given slug wins it (keeps URLs unique).
function slugifyGearSeries(str) {
  return String(str)
    .toLowerCase()
    .replace(/['"]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// Issue #3714: reserved series slug for the brand-level "drummers using" pages
// (drumhead brands — Evans, Remo). Mirrors BRAND_LEVEL_SERIES_SLUG in
// packages/frontend/data/gearSeriesPages.js.
const BRAND_LEVEL_SERIES_SLUG = 'all-drumheads';

function getGearSeriesUrls() {
  const seen = new Set();
  const urls = [];
  for (const [brand, seriesObj] of Object.entries(GEAR_INDEX)) {
    const brandSlug = slugifyGearSeries(brand);
    for (const [series, drummers] of Object.entries(seriesObj)) {
      if (!Array.isArray(drummers) || drummers.length < 2) continue;
      const seriesSlug = slugifyGearSeries(series);
      const key = `${brandSlug}/${seriesSlug}`;
      if (seen.has(key)) continue; // first series wins a given slug
      seen.add(key);
      urls.push(`/gear/${brandSlug}/${seriesSlug}/drummers-using`);
    }
  }
  for (const [brand, drummers] of Object.entries(GEAR_INDEX_BRAND_LEVEL)) {
    if (!Array.isArray(drummers) || drummers.length < 2) continue;
    const brandSlug = slugifyGearSeries(brand);
    const key = `${brandSlug}/${BRAND_LEVEL_SERIES_SLUG}`;
    if (seen.has(key)) continue;
    seen.add(key);
    urls.push(`/gear/${brandSlug}/${BRAND_LEVEL_SERIES_SLUG}/drummers-using`);
  }
  return urls;
}

// Issue: pre-render at build time. The full URL list + XML serialization is
// extracted here so scripts/generate-sitemap.mjs can emit a static
// dist/sitemap.xml at build time (no Vercel cold-start on every Googlebot
// fetch), while the serverless handler below stays a thin fallback.
export function buildSitemapXml() {
  const urls = [
    { loc: '/', priority: '1.0', changefreq: 'weekly' },
    // Issue #1053: #2 organic page (GA4) — drummer database hub, links to all 62 profiles
    { loc: '/drummers', priority: '0.9', changefreq: 'weekly' },
    // Issue #1053: #3 organic page (GA4) — "Which Metal Drummer Are You?" match quiz
    { loc: '/quiz', priority: '0.9', changefreq: 'weekly' },
    { loc: '/kit-quiz', priority: '0.9', changefreq: 'weekly' },
    { loc: '/guess-the-kit', priority: '0.95', changefreq: 'weekly' }, // Issue #706: Photo Quiz
    { loc: '/kit-builder', priority: '0.9', changefreq: 'weekly' },
    { loc: '/gear', priority: '0.9', changefreq: 'weekly' },
    // Issue #1823: Budget-tier gear shopping hub — high commercial intent
    { loc: '/gear-by-budget', priority: '0.9', changefreq: 'weekly' },
    { loc: '/quotes', priority: '0.9', changefreq: 'weekly' },
    { loc: '/facts', priority: '0.8', changefreq: 'monthly' }, // Issue #452: Quick Facts (FAQPage schema) — #1051 de-orphan
    { loc: '/lists', priority: '0.9', changefreq: 'weekly' },
    // Issue #4764 (phase 1/3 of epic #4763): /studies hub — grows in phase 2/3.
    { loc: '/studies', priority: '0.85', changefreq: 'weekly' },
    { loc: '/birthdays', priority: '0.9', changefreq: 'weekly' },
    // Issue #723: Metal Drummer Evolution Timeline (1970-2024)
    { loc: '/history', priority: '0.9', changefreq: 'monthly' },
    { loc: '/techniques', priority: '0.9', changefreq: 'weekly' },
    // Issue #1042: top-level signature licks index hub
    { loc: '/licks', priority: '0.9', changefreq: 'weekly' },
    // Issue #660: Gear News page with RSS
    { loc: '/gear-news', priority: '0.9', changefreq: 'daily' },
    // Issue #4372: general /news aggregator hub (distinct from /gear-news, /endorsement-news)
    { loc: '/news', priority: '0.85', changefreq: 'daily' },
    // Issue #689: Drummer Battle voting feature
    { loc: '/battles', priority: '0.9', changefreq: 'weekly' },
    // Issue #1822: Drummer spotlight features hub
    { loc: '/spotlights', priority: '0.85', changefreq: 'weekly' },
    // Issue #1473: Individual /battles/<slug> pages (8 curated matchups)
    ...battleSlugs.map(slug => ({ loc: `/battles/${slug}`, priority: '0.85', changefreq: 'monthly' })),
    // Issue #695: Gear Statistics data hub
    { loc: '/stats', priority: '0.9', changefreq: 'weekly' },
    { loc: '/stats/gear-insights', priority: '0.9', changefreq: 'weekly' },
    // Issue #685: "How to Sound Like" guides hub
    { loc: '/guides', priority: '0.9', changefreq: 'weekly' },
    ...soundLikeGuides.map(g => ({ loc: `/guides/${g.slug}`, priority: '0.9', changefreq: 'monthly' })),
    // Issue #1801: Beginner guide hub page
    { loc: '/beginner-guide', priority: '0.85', changefreq: 'monthly' },
    // Issue #702: Beginner gear guides
    ...beginnerGuides.map(g => ({ loc: `/guides/${g.slug}`, priority: '0.95', changefreq: 'monthly' })),
    // Issue #1794: Genre gear guides (commercial-intent purchase queries)
    ...Object.values(GENRE_GEAR_GUIDES).map(g => ({ loc: `/guides/${g.slug}`, priority: '0.95', changefreq: 'monthly' })),
    // Issue #1804: Shareable gear cards gallery
    { loc: '/cards', priority: '0.6', changefreq: 'monthly' },
    // Issue #1579: BPM Tap Calculator + Metal Songs BPM Database
    { loc: '/bpm', priority: '0.95', changefreq: 'weekly' },
    { loc: '/bpm-tap', priority: '0.9', changefreq: 'monthly' },
    // Issue #4760 (songs epic #4758, phase 2/4): /songs hub + flagship + tempo
    // tiers (derived from TEMPO_RANGES via getTempoTiers) + qualifying
    // by-drummer pages (roster drummers with >= 3 songs) — nothing hand-listed.
    { loc: '/songs', priority: '0.9', changefreq: 'weekly' },
    { loc: '/songs/fastest-metal-songs', priority: '0.9', changefreq: 'weekly' },
    ...getTempoTiers().map(t => ({ loc: `/songs/tempo/${t.slug}`, priority: '0.85', changefreq: 'monthly' })),
    ...songsQualifyingDrummers.map(d => ({ loc: `/songs/drummer/${d.drummer}`, priority: '0.7', changefreq: 'monthly' })),
    // Issue #4761 (songs epic #4758, phase 3/4): per-song pages, gated by
    // content-richness (getSongPageSlugs) — under-gate songs stay list-only
    // and never get a sitemap entry.
    ...getSongPageSlugs().map(slug => ({ loc: `/songs/${slug}`, priority: '0.75', changefreq: 'monthly' })),
    // Issue #4371: Gear Finder tool
    { loc: '/gear-finder', priority: '0.85', changefreq: 'weekly' },
    // Issue #4370: Metal Drumming Evolution Timeline (47 events, 1970-2024)
    { loc: '/timeline', priority: '0.85', changefreq: 'monthly' },
    // Issue #729: Tools Hub landing page
    { loc: '/tools', priority: '0.95', changefreq: 'weekly' },
    // Issue #704: Tools pages (viral tools)
    ...toolPages.map(t => ({ loc: `/tools/${t.slug}`, priority: '0.95', changefreq: 'weekly' })),
    // Issue #4443: Dream Setup Builder (flagship isNew:true tool)
    { loc: '/tools/setup-builder', priority: '0.85', changefreq: 'monthly' },
    // Issue #721, #732: Gear Comparison Tool + Top 20 SEO comparisons
    { loc: '/tools/compare', priority: '0.95', changefreq: 'weekly' },
    ...curatedToolsCompareSlugs.map(slug => ({
      loc: `/tools/compare/${slug}`,
      priority: '0.85',
      changefreq: 'monthly',
    })),
    ...gearCategories.map(c => ({ loc: `/gear/${c.slug}`, priority: '0.9', changefreq: 'weekly' })),
    ...top10Lists.map(l => ({ loc: `/lists/${l.slug}`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #4764: study pages, derived from the STUDIES registry (not hand-listed).
    ...STUDIES.map(s => ({ loc: `/studies/${s.slug}`, lastmod: s.dateModified, priority: '0.85', changefreq: 'monthly' })),
    // Issue #1821: Articles hub (CollectionPage schema exists in api/meta/[...path].js)
    { loc: '/articles', priority: '0.9', changefreq: 'weekly' },
    // Issue #642: Article pages for SEO-optimized content
    ...articles.map(a => ({ loc: `/articles/${a.slug}`, priority: '0.9', changefreq: 'weekly' })),
    // Issue #663: Album gear breakdown and drummer kit articles
    // Issue #1072: emit each article's real dateModified (falls back to SITE_LASTMOD).
    ...albumArticles.map(a => ({ loc: `/articles/${a.slug}`, lastmod: ALBUM_ARTICLES[a.slug]?.dateModified, priority: '0.9', changefreq: 'monthly' })),
    ...drummers.map(d => {
      const slug = generateSlug(d.name);
      const band = drummerBandBySlug[slug] || null;
      return {
        loc: `/drummer/${slug}`,
        priority: '0.8',
        changefreq: 'monthly',
        image: {
          loc: `${BASE_URL}/api/card/${slug}?format=og`,
          title: `${d.name} drum kit setup${band ? ' — ' + band : ''}`,
          caption: `Complete drum gear setup of ${d.name}${band ? ' from ' + band : ''}`,
        },
      };
    }),
    ...gearItems.map(g => ({ loc: `/gear/item/${g.slug}`, priority: '0.7', changefreq: 'monthly' })),
    // Issue #1799: Genre hub (/genres) + 8 genre landing pages (/genre/<slug>)
    { loc: '/genres', priority: '0.9', changefreq: 'weekly' },
    ...getAllGenreSlugs().map(slug => ({ loc: `/genre/${slug}`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #1171: /bands index hub + all 19 band pages at the correct plural path.
    { loc: '/bands', priority: '0.9', changefreq: 'weekly' },
    ...bandPages.map(slug => ({ loc: `/bands/${slug}`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #4769 (epic #4753 extension): drum-chair-changes timeline, derived
    // entirely from bands.js drummerHistory — changefreq weekly since it grows
    // whenever any band's lineup changes.
    { loc: '/bands/drum-chair-changes', priority: '0.8', changefreq: 'weekly' },
    ...techniques.map(t => ({ loc: `/techniques/${t.slug}`, priority: '0.8', changefreq: 'monthly', video: techniqueVideoBySlug[t.slug] })),
    // Issue #870, #994: Technique → drummers SEO pages (/technique/<slug>/drummers)
    // Same priority/changefreq pattern as drummer pages.
    ...getAllTechniqueSlugs().map(slug => ({ loc: `/technique/${slug}/drummers`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #656: Gear brand landing pages
    { loc: '/brands', priority: '0.9', changefreq: 'weekly' },
    ...gearBrands.map(b => ({ loc: `/brands/${b.slug}`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #345: Gear comparison pages
    { loc: '/compare', priority: '0.9', changefreq: 'weekly' },
    ...gearComparisons.map(c => ({ loc: `/compare/${c.slug}`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #558, #691: Drummer vs Drummer comparison pages (SEO play)
    { loc: '/vs', priority: '0.9', changefreq: 'weekly' },
    // Gated by VS_DEMAND_DRUMMERS (sitemap diet) — see the filter definition above.
    ...sitemapDrummerComparisons.map(c => ({ loc: `/vs/${c.slug}`, priority: '0.7', changefreq: 'monthly' })),
    // Issue #2389: curated /vs/ pages whose canonical slug the all-pairs generator above
    // doesn't produce — either because a drummer (e.g. Sean Reinert) isn't in the `drummers`
    // list, or because the generator always alphabetizes the pair while the curated slug
    // doesn't (e.g. lars-ulrich-vs-charlie-benante, not charlie-benante-vs-lars-ulrich).
    // Listed explicitly so sitemap.xml matches each page's actual canonical URL.
    ...([
      'sean-reinert-vs-martin-lopez',
      'sean-reinert-vs-hannes-grossmann',
      'lars-ulrich-vs-charlie-benante',
      // Issue #3611: 3 new curated pairs closing the zero-pairing roster gap.
      'richard-christy-vs-derek-roddy',
      'kevin-talley-vs-george-kollias',
      'ryan-van-poederooyen-vs-mike-portnoy',
      // Issue #4122: curated pairs closing thin-coverage gaps for Jon Dette,
      // who isn't in the `drummers` list above.
      'jon-dette-vs-dave-lombardo',
      'jon-dette-vs-gene-hoglan',
      // Issue #4128: navene-koperweis-vs-matt-garstka's curated slug keeps the
      // founder-then-successor narrative order; the alphabetized generator above
      // would instead produce matt-garstka-vs-navene-koperweis.
      'navene-koperweis-vs-matt-garstka',
    ].map(slug => ({ loc: `/vs/${slug}`, priority: '0.7', changefreq: 'monthly' }))),
    // Issue #739: Signature Gear Spotlight pages
    ...signatureGearPages.map(sg => ({ loc: `/drummers/${sg.drummerSlug}/signature/${sg.gearSlug}`, priority: '0.85', changefreq: 'monthly' })),
    // Issue #749: Signature Licks Database pages
    ...drummerLicksHubs.map(d => ({ loc: `/drummers/${d.drummerSlug}/licks`, priority: '0.9', changefreq: 'weekly' })),
    ...signatureLicksPages.map(sl => ({ loc: `/drummers/${sl.drummerSlug}/licks/${sl.lickSlug}`, priority: '0.85', changefreq: 'monthly', video: lickVideoByLoc[`/drummers/${sl.drummerSlug}/licks/${sl.lickSlug}`] })),
    // Issue #770: SEO Blitz - Drummer Gear Category Pages (long-tail keywords)
    ...drummerGearCategoryPages.map(dgc => ({ loc: `/drummer/${dgc.drummerSlug}/${dgc.category}`, priority: '0.85', changefreq: 'monthly' })),
    // Issue #802: Endorsement Tracker pages
    { loc: '/endorsement-news', priority: '0.9', changefreq: 'weekly' },
    ...endorsementDrummers.map(slug => ({ loc: `/drummers/${slug}/endorsements`, priority: '0.85', changefreq: 'monthly' })),
    // Issue #813: Gear Price History Tracker pages
    ...gearPriceHistoryDrummers.map(slug => ({ loc: `/drummers/${slug}/gear-history`, priority: '0.9', changefreq: 'monthly' })),
    // Issue #1475: Drummer gear evolution pages (3 drummers: lars-ulrich, joey-jordison, dave-lombardo)
    ...Object.keys(DRUMMER_EVOLUTION).map(slug => ({ loc: `/drummers/${slug}/evolution`, priority: '0.82', changefreq: 'monthly' })),
    // Issue #1805: per-drummer gear evolution LLM markdown files
    ...Object.keys(DRUMMER_EVOLUTION).map(slug => ({ loc: `/llms/evolution/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #871/#997: gear/series "drummers-using" SEO pages (≥2 drummers each)
    ...getGearSeriesUrls().map(loc => ({ loc, priority: '0.8', changefreq: 'monthly' })),
    // Issue #2403: kit-level "drummers-using" pages (12 purchase-intent scaffold slugs).
    // Issue #4361: excludes kit keys with zero drummers — those serve a noindex
    // meta response (empty ItemList is a thin/duplicate-content signal risk).
    ...Object.keys(DRUMMERS_BY_KIT).filter(key => DRUMMERS_BY_KIT[key].length > 0).map(key => ({ loc: `/gear/${key}/drummers-using`, priority: '0.85', changefreq: 'monthly' })),
    // Issue #4137: /drumsticks pillar page + sizes/materials/tips reference pages.
    { loc: '/drumsticks', priority: '0.9', changefreq: 'weekly' },
    ...REFERENCE_PAGE_ORDER.map(slug => ({ loc: `/drumsticks/${slug}`, priority: '0.85', changefreq: 'monthly' })),
    // Issue #4138: /drumsticks/signature/<drummer> pages (only drummers with a
    // confirmed stick mapping in DRUMMER_STICKS).
    ...Object.keys(DRUMMER_STICKS).map(slug => ({ loc: `/drumsticks/signature/${slug}`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #4139: /drumsticks/brands hub + per-brand pages, and the
    // /drumsticks/best-for-metal buying guide.
    { loc: '/drumsticks/brands', priority: '0.85', changefreq: 'monthly' },
    ...DRUMSTICK_BRANDS.map(brand => ({ loc: `/drumsticks/brands/${brand.slug}`, priority: '0.8', changefreq: 'monthly' })),
    { loc: '/drumsticks/best-for-metal', priority: '0.9', changefreq: 'monthly' },
    // Issue #4305: /cymbals pillar page + types/alloys/sizes-weights reference pages.
    { loc: '/cymbals', priority: '0.9', changefreq: 'weekly' },
    ...CYMBAL_REFERENCE_PAGE_ORDER.map(slug => ({ loc: `/cymbals/${slug}`, priority: '0.85', changefreq: 'monthly' })),
    // Issue #4307: /cymbals/brands hub + per-brand pages, and the
    // /cymbals/best-for-metal buying guide.
    { loc: '/cymbals/brands', priority: '0.85', changefreq: 'monthly' },
    ...CYMBAL_BRANDS.map(brand => ({ loc: `/cymbals/brands/${brand.slug}`, priority: '0.8', changefreq: 'monthly' })),
    { loc: '/cymbals/best-for-metal', priority: '0.9', changefreq: 'monthly' },
    // Issue #4306: /cymbals/setups/<drummer> pages (only drummers with a
    // confirmed cymbal setup in DRUMMER_CYMBALS).
    ...Object.keys(DRUMMER_CYMBALS).map(slug => ({ loc: `/cymbals/setups/${slug}`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #4393: /pedals/setups/<drummer> pages (only drummers with a
    // confirmed pedal in DRUMMER_PEDALS).
    ...Object.keys(DRUMMER_PEDALS).map(slug => ({ loc: `/pedals/setups/${slug}`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #4310: /snares pillar page + shells/sizes/tuning-for-metal reference pages.
    { loc: '/snares', priority: '0.9', changefreq: 'weekly' },
    ...SNARE_REFERENCE_PAGE_ORDER.map(slug => ({ loc: `/snares/${slug}`, priority: '0.85', changefreq: 'monthly' })),
    // Issue #4311: /snares/signature/<drummer> pages (only drummers with a
    // confirmed isSignature: true snare record).
    ...SIGNATURE_SNARES.map(snare => ({ loc: `/snares/signature/${snare.drummerSlug}`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #4312: /snares/best-for-metal buying guide.
    { loc: '/snares/best-for-metal', priority: '0.9', changefreq: 'monthly' },
    // Issue #4483: /snares/brands hub + per-brand pages (Tama, Pearl, Ludwig,
    // Sonor, Mapex, DW), matching the drumsticks/cymbals/pedals brand precedent.
    { loc: '/snares/brands', priority: '0.85', changefreq: 'monthly' },
    ...SNARE_BRANDS.map(brand => ({ loc: `/snares/brands/${brand.slug}`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #4392: /pedals pillar page + drive-types/single-vs-double/setup-tuning reference pages.
    { loc: '/pedals', priority: '0.9', changefreq: 'weekly' },
    ...PEDAL_REFERENCE_PAGE_ORDER.map(slug => ({ loc: `/pedals/${slug}`, priority: '0.85', changefreq: 'monthly' })),
    // Issue #4433 (split 2/3 of #4394): /pedals/best-for-metal buying guide.
    { loc: '/pedals/best-for-metal', priority: '0.9', changefreq: 'monthly' },
    // Issue #4432 (split 1/3 of #4394): /pedals/brands/<brand> pages; hub
    // route added by #4482.
    { loc: '/pedals/brands', priority: '0.85', changefreq: 'monthly' },
    ...PEDAL_BRANDS.map(brand => ({ loc: `/pedals/brands/${brand.slug}`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #1021 (split 3/4 of #1017): LLM-facing Markdown surface (public/llms/*.md).
    { loc: '/llms/index.md', priority: '0.6', changefreq: 'monthly' },
    { loc: '/llms/faq.md', priority: '0.6', changefreq: 'monthly' },
    { loc: '/llms/gear-guide.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1185: brand-first LLM citation surface for "which drummers use X brand" queries.
    { loc: '/llms/gear-by-brand.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #4390 (epic #4386 phase 3): brand history timeline LLM surface for the
    // /brands hub's "1623 -> today" upgrade.
    { loc: '/llms/brands-timeline.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1045: signature-lick database as ingestible markdown for AI crawlers.
    { loc: '/llms/licks.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1126: drumming-techniques reference as ingestible markdown.
    { loc: '/llms/techniques.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1173: bands + drummer-history reference as ingestible markdown.
    { loc: '/llms/bands.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1806: per-band LLM markdown files for AI citation of band drummer/gear queries.
    ...Object.keys(BAND_DATA).map(slug => ({
      loc: `/llms/bands/${slug}.md`,
      priority: '0.5',
      changefreq: 'monthly',
    })),
    // Issue #4769 (epic #4753 extension): drum-chair-changes timeline mirror.
    { loc: '/llms/drum-chair-changes.md', priority: '0.5', changefreq: 'weekly' },
    // Issue #1309: gear price timeline data for Lars Ulrich, Joey Jordison, Dave Lombardo.
    { loc: '/llms/gear-history.md', priority: '0.5', changefreq: 'monthly' },
    // Issue #1782: per-drummer gear history LLM markdown
    ...gearPriceHistoryDrummers.map(slug => ({ loc: `/llms/gear-history/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #1561: drummer birth dates as LLM markdown for birthday/calendar AI queries.
    { loc: '/llms/birthdays.md', priority: '0.5', changefreq: 'monthly' },
    // Issue #1190: drummer comparison pages as ingestible markdown.
    { loc: '/llms/comparisons.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #4552: per-pair Q&A comparison Markdown files for direct AI citation
    // (distinct "Q: ... A: ..." format from /llms/vs/<slug>.md's gear-stat format).
    // All 26 slugs are a curated subset of drummerComparisons keys, but no field
    // in that data distinguishes them (verified: "faqs" presence doesn't match 1:1)
    // so this is hardcoded to match the 26 files shipped in public/llms/comparisons/,
    // mirroring the #1703 /llms/battles/ precedent below.
    ...([
      'art-cruz-vs-jay-weinberg',
      'bill-ward-vs-charlie-benante',
      'bill-ward-vs-mario-duplantier',
      'bill-ward-vs-matt-greiner',
      'dave-lombardo-vs-chris-adler',
      'dirk-verbeuren-vs-paul-bostaph',
      'flo-mounier-vs-george-kollias',
      'frost-vs-daray',
      'frost-vs-hellhammer',
      'frost-vs-inferno',
      'frost-vs-jaska-raatikainen',
      'gavin-harrison-vs-mike-mangini',
      'gene-hoglan-vs-tomas-haake',
      'jaska-raatikainen-vs-mario-duplantier',
      'jaska-raatikainen-vs-matt-greiner',
      'jaska-raatikainen-vs-nicko-mcbrain',
      'joey-jordison-vs-jay-weinberg',
      'mario-duplantier-vs-hellhammer',
      'mario-duplantier-vs-tomas-haake',
      'martin-axenrot-vs-martin-lopez',
      'matt-greiner-vs-matt-halpern',
      'ray-luzier-vs-scott-travis',
      'scott-travis-vs-nicko-mcbrain',
      'sean-reinert-vs-hannes-grossmann',
      'shannon-larkin-vs-jay-weinberg',
      'tomas-haake-vs-blake-richardson',
    ].map(slug => ({
      loc: `/llms/comparisons/${slug}.md`,
      priority: '0.5',
      changefreq: 'monthly',
    }))),
    // Issue #1222: top-10 ranked lists as ingestible markdown for AI citation.
    { loc: '/llms/lists.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1223: quick facts page as ingestible markdown for AI citation.
    { loc: '/llms/facts.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1246: quiz LLM citation surface — #3 organic page, zero prior AI discoverability.
    { loc: '/llms/quiz.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #4608: 4 live /llms/*.md hub files never wired into the sitemap
    // (battles/guess-the-kit/kit-quiz shipped via #1433 without sitemap wiring;
    // gear-comparison.md hub shipped by scripts/generate-llms-gear-comparisons.cjs,
    // distinct from the already-sitemapped /llms/tools/gear-comparison.md tool page).
    { loc: '/llms/battles.md', priority: '0.6', changefreq: 'monthly' },
    { loc: '/llms/guess-the-kit.md', priority: '0.6', changefreq: 'monthly' },
    { loc: '/llms/kit-quiz.md', priority: '0.6', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1560: quotes LLM citation surface — 36 attributed quotes from 12 metal drummers.
    { loc: '/llms/quotes.md', priority: '0.5', changefreq: 'monthly' },
    // Issue #1330: gear stats LLM citation surface — brand-popularity data for AI queries.
    { loc: '/llms/stats.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1401: gear brand insights LLM citation surface — named drummer citations with % data.
    { loc: '/llms/gear-insights.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #4283: drumsticks hub LLM citation surface — complete index of the
    // DRUMSTICKS module (generated by scripts/generate-llms-drumsticks.cjs).
    { loc: '/llms/drumsticks.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #4579: /drumsticks/sizes|materials|tips LLM citation surface —
    // one file per REFERENCE_PAGE_ORDER entry (generated by
    // scripts/generate-llms-drumsticks.cjs), matching the /pedals reference
    // page precedent (#4497).
    ...REFERENCE_PAGE_ORDER.map(slug => ({ loc: `/llms/drumsticks/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #4478: /drumsticks/brands/<slug> LLM citation surface — one file
    // per DRUMSTICK_BRANDS entry (generated by
    // scripts/generate-llms-drumsticks-brands.cjs), matching the /pedals/brands
    // precedent (#4432/#4431).
    ...DRUMSTICK_BRANDS.map(brand => ({ loc: `/llms/drumsticks/brands/${brand.slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #4577: /drumsticks/signature/<drummer> LLM citation surface — one
    // file per DRUMMER_STICKS entry (generated by
    // scripts/generate-llms-drumsticks-signature.cjs), closing the gap left
    // when only the hub (#4283) and brands tier (#4478) were wired, matching
    // the /pedals/setups (#4497) and /cymbals/setups (#4518) precedent.
    ...Object.keys(DRUMMER_STICKS).map(slug => ({ loc: `/llms/drumsticks/signature/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #4307: cymbals hub LLM citation surface — complete index of the
    // CYMBAL_SETUPS module (generated by scripts/generate-llms-cymbals.cjs).
    { loc: '/llms/cymbals.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #4579: /cymbals/types|alloys|sizes-weights LLM citation surface —
    // one file per CYMBAL_REFERENCE_PAGE_ORDER entry (generated by
    // scripts/generate-llms-cymbals.cjs), matching the /pedals reference
    // page precedent (#4497).
    ...CYMBAL_REFERENCE_PAGE_ORDER.map(slug => ({ loc: `/llms/cymbals/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #4478: /cymbals/brands/<slug> LLM citation surface — one file per
    // CYMBAL_BRANDS entry (generated by scripts/generate-llms-cymbals-brands.cjs),
    // matching the /pedals/brands precedent (#4432/#4431).
    ...CYMBAL_BRANDS.map(brand => ({ loc: `/llms/cymbals/brands/${brand.slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #4518: /cymbals/setups/<drummer> LLM citation surface — one file
    // per DRUMMER_CYMBALS entry (generated by
    // scripts/generate-llms-cymbals-setups.cjs), closing the gap left when
    // only the hub (#4307) and brands tier (#4478) were wired, matching the
    // /pedals/setups precedent (#4497) below.
    ...Object.keys(DRUMMER_CYMBALS).map(slug => ({ loc: `/llms/cymbals/setups/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #4484: /pedals/brands/<slug> LLM citation surface — one file per
    // PEDAL_BRANDS entry, mirroring the drumsticks/cymbals brands precedent
    // above (#4478). Files already exist on disk under public/llms/pedals/brands/.
    ...PEDAL_BRANDS.map(brand => ({ loc: `/llms/pedals/brands/${brand.slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #4497: /llms/pedals.md hub + reference pages + per-drummer
    // setup pages — mirrors the drumsticks.md/cymbals.md hub precedent (#4283/#4307),
    // closing the gap left when only the brands tier (#4484) was wired.
    { loc: '/llms/pedals.md', priority: '0.6', changefreq: 'monthly' },
    ...PEDAL_REFERENCE_PAGE_ORDER.map(slug => ({ loc: `/llms/pedals/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    ...Object.keys(DRUMMER_PEDALS).map(slug => ({ loc: `/llms/pedals/setups/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #4312: snares hub LLM citation surface — complete index of the
    // SNARES module (generated by scripts/generate-llms-snares.cjs).
    { loc: '/llms/snares.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #4579: /snares/shells|sizes|tuning-for-metal LLM citation
    // surface — one file per SNARE_REFERENCE_PAGE_ORDER entry (generated by
    // scripts/generate-llms-snares.cjs), matching the /pedals reference page
    // precedent (#4497).
    ...SNARE_REFERENCE_PAGE_ORDER.map(slug => ({ loc: `/llms/snares/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #4488: /snares/brands/<slug> LLM citation surface — one file per
    // SNARE_BRANDS entry (generated by scripts/generate-llms-snares-brands.cjs),
    // matching the /drumsticks/brands and /cymbals/brands precedent (#4478).
    ...SNARE_BRANDS.map(brand => ({ loc: `/llms/snares/brands/${brand.slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #4578: /snares/signature/<drummer> LLM citation surface — one file
    // per SIGNATURE_SNARES entry (generated by
    // scripts/generate-llms-snares-signature.cjs), matching the
    // /pedals/setups and /cymbals/setups precedent (#4431/#4518).
    ...SIGNATURE_SNARES.map(snare => ({ loc: `/llms/snares/signature/${snare.drummerSlug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #4592: /gear/item/<slug> LLM citation surface — one file per
    // gearItems entry (generated by scripts/generate-llms-gear-item.cjs),
    // closing the last remaining "HTML surface with schema, no llms mirror"
    // gap across the drumsticks/cymbals/snares/pedals/gear-items categories.
    ...gearItems.map(g => ({ loc: `/llms/gear/item/${g.slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #1586: gear-news + endorsement-news LLM citation surfaces (temporal/news dimension).
    { loc: '/llms/gear-news.md', priority: '0.6', changefreq: 'daily' },
    { loc: '/llms/endorsement-news.md', priority: '0.6', changefreq: 'weekly' },
    // Issue #1416: endorsement hub LLM citation surface — cross-brand index of 15 drummers.
    { loc: '/llms/endorsements.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1435: per-drummer endorsement detail pages — one file per endorsement-tracked drummer.
    ...endorsementDrummers.map(slug => ({ loc: `/llms/endorsements/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #1781: per-brand LLM markdown — sitemap entries for 8 files shipped in #1415
    ...gearBrands.map(b => ({ loc: `/llms/brands/${b.slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #1273: tools section LLM citation surface — gear-search, dream-set-builder, kit-builder, gear-comparison, tier-list.
    { loc: '/llms/tools/gear-search.md', priority: '0.6', changefreq: 'monthly' },
    { loc: '/llms/tools/dream-set-builder.md', priority: '0.6', changefreq: 'monthly' },
    { loc: '/llms/tools/kit-builder.md', priority: '0.6', changefreq: 'monthly' },
    { loc: '/llms/tools/gear-comparison.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1780: per-comparison brand LLM files — 7 files shipped in #1514, absent from sitemap.
    ...gearComparisons.map(c => ({ loc: `/llms/gear-comparison/${c.slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #2404: drummers-using LLM files for top-3 flagship kit pages (Tama Star Classic Maple, DW Collector's Maple, Pearl Reference Pure).
    { loc: '/llms/gear-comparison/drummers-using-tama-star-classic-maple.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-dw-collectors-maple.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-pearl-reference-pure.md', priority: '0.5', changefreq: 'monthly' },
    // Issue #2405: drummers-using LLM files for mid-tier kit pages (Gretsch USA Custom, Sonor SQ2, Mapex Armory).
    { loc: '/llms/gear-comparison/drummers-using-gretsch-usa-custom.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-sonor-sq2.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-mapex-armory.md', priority: '0.5', changefreq: 'monthly' },
    // Issue #2406: drummers-using LLM files for final 6 kit pages (Ludwig Classic Maple, Yamaha Recording Custom,
    // Tama Superstar Classic, DW Performance Maple, Pearl Masters Maple, Sonor Vintage).
    { loc: '/llms/gear-comparison/drummers-using-ludwig-classic-maple.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-yamaha-recording-custom.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-tama-superstar-classic.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-dw-performance-maple.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-pearl-masters-maple.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-sonor-vintage.md', priority: '0.5', changefreq: 'monthly' },
    // Issue #3714: drumhead brand-level LLM files (Evans ~31 drummers, Remo ~18 drummers).
    { loc: '/llms/gear-comparison/drummers-using-evans.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-remo.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/tools/tier-list.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1351: name-generator LLM citation surface — metal drummer alias generator.
    { loc: '/llms/tools/name-generator.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1582: BPM + metal songs tempo database LLM citation surface.
    { loc: '/llms/bpm.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1329: how-to-sound-like + beginner guides LLM citation surface.
    { loc: '/llms/guides.md', priority: '0.4', changefreq: 'monthly' },
    // Issue #1450: per-guide deep-dive Markdown files for AI citation (10 sound-like guides).
    ...soundLikeGuides.map(g => ({ loc: `/llms/guides/${g.slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #4634 / #4645: genre-gear-guide LLM citation surfaces (all 278 best-* guides).
    ...genreGearGuideMdSlugs.map(slug => ({ loc: `/llms/guides/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #1562: beginner/budget gear guide LLM citation surfaces.
    { loc: '/llms/guides/beginner-metal-drummer-setup.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/guides/budget-metal-drum-setup-500.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/guides/budget-metal-drum-setup-1000.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/guides/budget-metal-drum-setup-2000.md', priority: '0.5', changefreq: 'monthly' },
    // Per-drummer Markdown profiles — low priority, full crawl coverage.
    ...llmsDrummerSlugs.map(slug => ({ loc: `/llms/drummers/${slug}.md`, priority: '0.4', changefreq: 'monthly' })),
    // Issue #1058: per-article Markdown breakdowns (public/llms/articles/<slug>.md).
    // Slugs sourced from ALBUM_ARTICLES so they stay 1:1 with the committed files.
    // Issue #1072: same real dateModified as the article HTML page (1:1 data).
    ...Object.keys(ALBUM_ARTICLES).map(slug => ({ loc: `/llms/articles/${slug}.md`, lastmod: ALBUM_ARTICLES[slug]?.dateModified, priority: '0.4', changefreq: 'monthly' })),
    // Issue #2311: lick-guide LLM articles (not album articles — no /articles/ frontend page).
    { loc: '/llms/articles/matt-greiner-licks.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/joey-jordison-licks.md', priority: '0.5', changefreq: 'monthly' },
    // Issue #4649: orphaned Gear Evolution Timeline / Signature Gear Guide
    // articles — a different content shape than ALBUM_ARTICLES, so they were
    // never wired into the block above despite existing on disk.
    { loc: '/llms/articles/ben-koller-evolution.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/catch-33-drum-setup.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/charlie-benante-licks.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/dave-lombardo-signature-gear-guide.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/gavin-harrison-porcupine-tree-drum-setup.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/hunter-drum-setup.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/igor-cavalera-licks.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/mario-duplantier-gear-evolution.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/mikkey-dee-evolution.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/nick-augusto-drum-setup.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/paul-mazurkiewicz-gear-evolution.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/periphery-self-titled-drum-setup.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/pete-sandoval-evolution.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/tomas-haake-signature-gear-guide.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/vinnie-paul-gear-evolution.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/vol3-subliminal-verses-drum-setup.md', priority: '0.5', changefreq: 'monthly' },
    // Issue #1201: per-technique deep-dive Markdown files for AI citation.
    // One file per technique slug mirrors the per-drummer pattern above.
    ...getAllTechniqueSlugs().map(slug => ({ loc: `/llms/technique/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #1218 / #1244: per-drummer lick Markdown files for AI citation.
    // Issue #4276: derive from `drummerLicksHubs` (itself sourced from
    // SIGNATURE_LICKS above) instead of hand-maintaining a duplicate slug
    // list — this list drifted 4 separate times (#1219, #1248, #1702, #4275)
    // because every new lick batch needed a second manual edit here that was
    // easy to forget.
    ...drummerLicksHubs.map(d => ({ loc: `/llms/licks/${d.drummerSlug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #1271: per-series LLM Markdown files for AI citation.
    // Slugs derived from GEAR_INDEX (same slugifyGearSeries logic used for HTML pages)
    // so /llms/gear-series/<brand>-<series>.md URLs stay 1:1 with committed files.
    ...Object.entries(GEAR_INDEX).flatMap(([brand, seriesObj]) =>
      Object.entries(seriesObj)
        .filter(([, ds]) => Array.isArray(ds) && ds.length >= 2)
        .map(([series]) => ({
          loc: `/llms/gear-series/${slugifyGearSeries(brand)}-${slugifyGearSeries(series)}.md`,
          priority: '0.5',
          changefreq: 'monthly',
        }))
    ),
    // Issue #1276: per-pair drummer comparison Markdown files for AI citation.
    // Slugs sourced from drummerComparisons data so /llms/vs/<slug>.md URLs
    // stay 1:1 with the files generated by scripts/generate-llms-vs.cjs.
    ...getAllDrummerComparisonSlugs().map(slug => ({
      loc: `/llms/vs/${slug}.md`,
      priority: '0.5',
      changefreq: 'monthly',
    })),
    // Issue #4217: removed the #1795/#2101 hardcoded pair list — all 9 stale/dead
    // slugs it carried had no committed public/llms/vs/ file (7 were stale-order
    // duplicates of a curated reversed-slug entry, 2 had no curated entry at all),
    // and its remaining entry (mike-portnoy-vs-mike-mangini) is a curated
    // drummerComparisons key already sourced via getAllDrummerComparisonSlugs() above.
    // Issue #1703: per-matchup battle LLM Markdown files for AI citation (8 files).
    // Hardcoded to match the 8 files shipped in public/llms/battles/.
    ...([
      'brann-dailor-vs-chris-adler',
      'danny-carey-vs-mike-portnoy',
      'gene-hoglan-vs-george-kollias',
      'inferno-vs-hellhammer',
      'joey-jordison-vs-eloy-casagrande',
      'lars-ulrich-vs-dave-lombardo',
      'tomas-haake-vs-mario-duplantier',
      'vinnie-paul-vs-dave-lombardo',
    ].map(slug => ({
      loc: `/llms/battles/${slug}.md`,
      priority: '0.5',
      changefreq: 'monthly',
    }))),
    // Issue #1512: per-list LLM Markdown files for AI citation (8 top-10 lists).
    // Slugs sourced from the same top10Lists array used for /lists/<slug> HTML pages
    // so /llms/lists/<slug>.md URLs stay 1:1 with the files generated by
    // scripts/generate-llms-lists-per-slug.cjs.
    ...top10Lists.map(l => ({
      loc: `/llms/lists/${l.slug}.md`,
      priority: '0.5',
      changefreq: 'monthly',
    })),
    // Issue #1800: genre LLM citation surface — 8 genre pages
    ...getAllGenreSlugs().map(slug => ({ loc: `/llms/genres/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
  ];
  // SITEMAP DIET (founder-approved 2026-07-16), part 2: /llms/**.md mirrors are
  // built FOR AI crawlers, which discover them via llms.txt — not this sitemap.
  // Listing ~1.9K of them here invited Google to spend crawl budget on
  // near-duplicate markdown copies of the HTML pages. Excluded wholesale at
  // render time (the generation blocks above are intentionally left in place —
  // smallest reversible diff). The .md files stay live; llms.txt still links them.
  const googleUrls = urls.filter(u => !u.loc.startsWith('/llms/'));
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
        xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
${googleUrls.map(url => `  <url>
    <loc>${xmlEscape(BASE_URL + url.loc)}</loc>
    <lastmod>${lastmodFor(url)}</lastmod>
    <changefreq>${url.changefreq}</changefreq>
    <priority>${url.priority}</priority>${url.image ? `
    <image:image>
      <image:loc>${xmlEscape(url.image.loc)}</image:loc>
      <image:title>${xmlEscape(url.image.title)}</image:title>
      <image:caption>${xmlEscape(url.image.caption)}</image:caption>
    </image:image>` : ''}${url.video ? `
    <video:video>
      <video:thumbnail_loc>${xmlEscape(url.video.thumbnailLoc)}</video:thumbnail_loc>
      <video:title>${xmlEscape(url.video.title)}</video:title>
      <video:description>${xmlEscape(url.video.description)}</video:description>
      <video:content_loc>${xmlEscape(url.video.contentLoc)}</video:content_loc>
      <video:player_loc>${xmlEscape(url.video.playerLoc)}</video:player_loc>
    </video:video>` : ''}
  </url>`).join('\n')}
</urlset>`;
  return sitemap;
}

export default function handler(req, res) {
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 'public, max-age=86400');
  res.status(200).send(buildSitemapXml());
}
