// Vercel Serverless Function - sitemap.xml
// Issue #361: Added band pages
// Issue #339: Added gear category pages for SEO
// Issue #344: Added drumming technique pages
// Issue #345: Added gear comparison pages
// Issue #785: Import albumArticles dynamically from data source

import { ALBUM_ARTICLES } from '../packages/frontend/data/albumArticles.js';
// Issue #994 (split 3/3 of #870): source technique slugs for the new
// /technique/<slug>/drummers pages directly from the data module so the
// sitemap stays in sync as techniques are added.
import { getAllTechniqueSlugs } from '../packages/frontend/data/techniques.js';
// Issue #997 (split 3/4 of #871): source the /gear/<brand>/<series>/drummers-using
// slugs from the generated gear index so the sitemap stays in sync with the
// pages added in #996. We import the self-contained GEAR_INDEX data directly
// (rather than data/gearSeriesPages.js, which pulls in pricing/affiliate
// helpers) and mirror that module's slug + dedupe logic verbatim so the URLs
// emitted here resolve 1:1 with the live routes.
import { GEAR_INDEX } from '../packages/frontend/data/gearIndex.js';
// Issue #1056: derive the signature-lick page + hub URLs directly from the
// composed SIGNATURE_LICKS data (now modularized under data/licks/) instead of
// hand-maintaining two parallel arrays here. New lick batches add a per-drummer
// file and auto-appear in the sitemap — no manual edit, no second conflict surface.
import { SIGNATURE_LICKS } from '../packages/frontend/data/signatureLicks.js';
// Issue #1125: source the full drummer roster WITH gear records so the
// /drummer/<slug>/<category> long-tail pages are declared for every drummer
// that has real data in a category (not just 16 hardcoded names). Same module
// the renderer api/gear/[slug]/[category].js reads, so URLs ↔ pages stay 1:1.
import { drummers as DRUMMER_GEAR_DATA } from './drummers/index.js';
// Issue #1171: source all 19 band slugs from the canonical data module so the
// sitemap stays in sync as bands are added, and URLs match the live /bands/ route.
import { bands as BAND_DATA } from '../packages/frontend/data/bands.js';
// Issue #1276: per-pair LLM comparison Markdown files — source slugs from the
// canonical drummerComparisons data so /llms/vs/<slug>.md URLs stay 1:1 with
// the files generated by scripts/generate-llms-vs.cjs.
import { getAllDrummerComparisonSlugs } from '../packages/frontend/data/drummerComparisons.js';
// Issue #1475: drummer gear evolution pages — source slugs from the canonical
// data module so /drummers/<slug>/evolution URLs stay 1:1 with live routes.
import { DRUMMER_EVOLUTION } from '../packages/frontend/data/drummerEvolution.js';
// Issue #1473: individual /battles/<slug> pages — 8 curated matchups with
// SEO-targeted titles for "X vs Y drum kit" long-tail queries.
import { CURATED_MATCHUPS } from '../packages/frontend/data/battles.js';
// Issue #1794: Genre gear guide pages — /guides/best-[gear]-for-[genre]
import { GENRE_GEAR_GUIDES } from '../packages/frontend/data/genreGearGuides.js';
// Issue #1799: Genre hub + 8 genre landing pages
import { getAllGenreSlugs } from '../packages/frontend/data/genres.js';
// Issue #2403: kit-level /gear/:brand/:series/drummers-using pages (12 scaffold slugs).
import { DRUMMERS_BY_KIT } from '../packages/frontend/data/drummersByKit.js';
// Issue #2726: source top-10 list slugs from canonical data module so sitemap
// stays in sync when new list pages ship.
import { TOP_10_LISTS } from '../packages/frontend/data/top10Lists.js';

// Issue #623: Content Scale Sprint - All 62 drummers now in sitemap
const drummers = [
  { id: 1, name: 'Lars Ulrich' }, { id: 2, name: 'Joey Jordison' }, { id: 3, name: 'Gene Hoglan' },
  { id: 4, name: 'Dave Lombardo' }, { id: 5, name: 'Tomas Haake' }, { id: 6, name: 'George Kollias' },
  { id: 7, name: 'Eloy Casagrande' }, { id: 8, name: 'Ray Luzier' }, { id: 9, name: 'John Otto' },
  { id: 10, name: 'Jay Weinberg' }, { id: 11, name: 'Vinnie Paul' }, { id: 12, name: 'Charlie Benante' },
  { id: 13, name: 'Mike Portnoy' }, { id: 14, name: 'Danny Carey' }, { id: 15, name: 'Mario Duplantier' },
  { id: 16, name: 'Brann Dailor' }, { id: 17, name: 'Chris Adler' }, { id: 18, name: 'Matt Halpern' },
  { id: 19, name: 'Inferno' }, { id: 20, name: 'Hellhammer' }, { id: 21, name: 'Pete Sandoval' },
  { id: 22, name: 'Art Cruz' }, { id: 23, name: 'Arin Ilejay' }, { id: 24, name: 'Navene Koperweis' },
  { id: 25, name: 'Alex Bent' }, { id: 26, name: 'Shannon Larkin' }, { id: 27, name: 'Raymond Herrera' },
  { id: 28, name: 'Morgan Ågren' }, { id: 29, name: 'Igor Cavalera' }, { id: 30, name: 'Bill Ward' },
  { id: 31, name: 'Nick Augusto' }, { id: 32, name: 'Matt Greiner' }, { id: 33, name: 'Blake Richardson' },
  { id: 34, name: 'Ben Koller' }, { id: 35, name: 'Flo Mounier' }, { id: 37, name: 'Jason Bittner' },
  { id: 38, name: 'Martin Lopez' }, { id: 39, name: 'Travis Orbin' }, { id: 40, name: 'Chris Turner' },
  { id: 41, name: 'Nicko McBrain' }, { id: 42, name: 'Scott Travis' }, { id: 43, name: 'Mikkey Dee' },
  { id: 44, name: 'Derek Roddy' }, { id: 45, name: 'Dirk Verbeuren' }, { id: 46, name: 'Frost' },
  { id: 47, name: 'Gavin Harrison' }, { id: 48, name: 'Abe Cunningham' }, { id: 49, name: 'Richard Christy' },
  { id: 50, name: 'Aquiles Priester' }, { id: 51, name: 'Paul Mazurkiewicz' }, { id: 52, name: 'Mike Mangini' },
  { id: 53, name: 'Matt Garstka' }, { id: 54, name: 'Daniel Erlandsson' }, { id: 55, name: 'Jaska Raatikainen' },
  { id: 56, name: 'Hannes Grossmann' }, { id: 57, name: 'Daray' }, { id: 58, name: 'Jocke Wallgren' },
  { id: 59, name: 'Tim Yeung' }, { id: 60, name: 'Kevin Talley' }, { id: 61, name: 'Isaac Lamb' },
  { id: 62, name: 'Ryan Van Poederooyen' },
];

const gearItems = [
  { slug: 'tama-iron-cobra-900-double-pedal', name: 'Tama Iron Cobra 900' },
  { slug: 'meinl-byzance-series-cymbals', name: 'Meinl Byzance Series' },
  { slug: 'paiste-rude-series-cymbals', name: 'Paiste RUDE Series' },
  { slug: 'zildjian-a-custom-series-cymbals', name: 'Zildjian A Custom' },
  { slug: 'vic-firth-american-classic-5b', name: 'Vic Firth 5B' },
  { slug: 'pearl-demon-drive-double-pedal', name: 'Pearl Demon Drive' },
  { slug: 'tama-starclassic-walnut-birch-drums', name: 'Tama Starclassic' },
  { slug: 'pearl-reference-series-drums', name: 'Pearl Reference' },
  { slug: 'sonor-sq2-heavy-beech-drums', name: 'Sonor SQ2' },
  { slug: 'sabian-hhx-series-cymbals', name: 'Sabian HHX' },
];

// Issue #2726: derive from TOP_10_LISTS data module (19 entries) so the sitemap
// stays in sync automatically when new list pages ship.
const top10Lists = Object.values(TOP_10_LISTS).map(l => ({ slug: l.slug, name: l.title }));

// Issue #642, #658: Article pages (SEO-optimized with /articles/:slug route)
const articles = [
  { slug: 'most-expensive-drum-setups', name: 'Top 10 Most Expensive Metal Drum Setups' },
  { slug: 'fastest-double-bass-drummers', name: 'Top 10 Fastest Double Bass Drummers in Metal' },
  { slug: 'most-brutal-drum-solos', name: 'Top 10 Most Brutal Drum Solos in Metal History' },
];

// Issue #663: Album gear breakdown articles
// Issue #785: Dynamically generate albumArticles from ALBUM_ARTICLES data source
const albumArticles = Object.keys(ALBUM_ARTICLES).map(slug => ({
  slug,
  name: ALBUM_ARTICLES[slug].albumTitle 
    ? `${ALBUM_ARTICLES[slug].albumTitle} Drum Setup`
    : ALBUM_ARTICLES[slug].title || slug
}));

// Issue #1171: derive slugs from BAND_DATA (19 entries) instead of a hardcoded 2-entry list.
const bandPages = Object.keys(BAND_DATA);

// Issue #339: Gear category pages for SEO
const gearCategories = [
  { slug: 'cymbals', name: 'Metal Cymbals' },
  { slug: 'snares', name: 'Metal Snare Drums' },
  { slug: 'drums', name: 'Metal Drum Kits' },
  { slug: 'pedals', name: 'Metal Bass Drum Pedals' },
  { slug: 'sticks', name: 'Metal Drumsticks' },
  { slug: 'hardware', name: 'Metal Drum Hardware' },
];

// Issue #344: Drumming technique pages
const techniques = [
  { slug: 'blast-beat', name: 'Blast Beat' },
  { slug: 'double-bass', name: 'Double Bass Drumming' },
  { slug: 'gravity-blast', name: 'Gravity Blast' },
  { slug: 'polyrhythms', name: 'Polyrhythms' },
  { slug: 'odd-time-signatures', name: 'Odd Time Signatures' },
  { slug: 'one-handed-roll', name: 'One-Handed Roll' },
  { slug: 'triggered-drums', name: 'Triggered Drums' },
  { slug: 'groove-drumming', name: 'Groove Metal Drumming' },
  { slug: 'linear-drumming', name: 'Linear Drumming' },
  { slug: 'fill-techniques', name: 'Metal Drum Fills' },
];

// Issue #656: Gear brand landing pages for SEO
const gearBrands = [
  // Drum Brands
  { slug: 'tama', name: 'Tama', type: 'drums' },
  { slug: 'pearl', name: 'Pearl', type: 'drums' },
  { slug: 'dw', name: 'DW (Drum Workshop)', type: 'drums' },
  { slug: 'ludwig', name: 'Ludwig', type: 'drums' },
  // Cymbal Brands
  { slug: 'zildjian', name: 'Zildjian', type: 'cymbals' },
  { slug: 'paiste', name: 'Paiste', type: 'cymbals' },
  { slug: 'meinl', name: 'Meinl', type: 'cymbals' },
  { slug: 'sabian', name: 'Sabian', type: 'cymbals' },
];

// Issue #345: Gear comparison pages for SEO
const gearComparisons = [
  { slug: 'tama-vs-pearl', name: 'Tama vs Pearl Drums' },
  { slug: 'meinl-vs-zildjian', name: 'Meinl vs Zildjian Cymbals' },
  { slug: 'tama-iron-cobra-vs-pearl-demon-drive', name: 'Tama Iron Cobra vs Pearl Demon Drive' },
  { slug: 'paiste-vs-sabian', name: 'Paiste vs Sabian Cymbals' },
  { slug: 'tama-slp-vs-pearl-sensitone', name: 'Tama SLP vs Pearl Sensitone' },
  { slug: 'sonor-vs-dw', name: 'Sonor vs DW Drums' },
  { slug: 'zildjian-vs-sabian', name: 'Zildjian vs Sabian Cymbals' },
];

// Issue #558, #598, #650: Drummer vs Drummer comparison pages for SEO
// Issue #650: Generate ALL drummer comparison pairs dynamically (62 drummers = 1891 pairs)
function generateAllDrummerComparisons(drummerList) {
  const comparisons = [];
  for (let i = 0; i < drummerList.length; i++) {
    for (let j = i + 1; j < drummerList.length; j++) {
      const slug1 = generateSlug(drummerList[i].name);
      const slug2 = generateSlug(drummerList[j].name);
      // Alphabetical order for consistency
      const orderedSlug = slug1 < slug2 ? `${slug1}-vs-${slug2}` : `${slug2}-vs-${slug1}`;
      comparisons.push({
        slug: orderedSlug,
        name: `${drummerList[i].name} vs ${drummerList[j].name}`
      });
    }
  }
  return comparisons;
}
const drummerComparisons = generateAllDrummerComparisons(drummers);

// Issue #685: "How to Sound Like" guides - SEO content hub
const soundLikeGuides = [
  { slug: 'how-to-sound-like-joey-jordison', name: 'How to Sound Like Joey Jordison' },
  { slug: 'how-to-sound-like-danny-carey', name: 'How to Sound Like Danny Carey' },
  { slug: 'how-to-sound-like-lars-ulrich', name: 'How to Sound Like Lars Ulrich' },
  { slug: 'how-to-sound-like-dave-lombardo', name: 'How to Sound Like Dave Lombardo' },
  { slug: 'how-to-sound-like-mario-duplantier', name: 'How to Sound Like Mario Duplantier' },
  { slug: 'how-to-sound-like-tomas-haake', name: 'How to Sound Like Tomas Haake' },
  { slug: 'how-to-sound-like-gene-hoglan', name: 'How to Sound Like Gene Hoglan' },
  { slug: 'how-to-sound-like-brann-dailor', name: 'How to Sound Like Brann Dailor' },
  { slug: 'how-to-sound-like-matt-halpern', name: 'How to Sound Like Matt Halpern' },
  { slug: 'how-to-sound-like-chris-adler', name: 'How to Sound Like Chris Adler' },
  // Issue #1803: SEO batch — 4 new sound-like guides
  { slug: 'how-to-sound-like-matt-greiner', name: 'How to Sound Like Matt Greiner' },
  { slug: 'how-to-sound-like-george-kollias', name: 'How to Sound Like George Kollias' },
  { slug: 'how-to-sound-like-travis-orbin', name: 'How to Sound Like Travis Orbin' },
  { slug: 'how-to-sound-like-flo-mounier', name: 'How to Sound Like Flo Mounier' },
  // Issue #1932: SEO batch — Jay Weinberg, Mike Mangini, Gavin Harrison
  { slug: 'how-to-sound-like-jay-weinberg', name: 'How to Sound Like Jay Weinberg' },
  { slug: 'how-to-sound-like-mike-mangini', name: 'How to Sound Like Mike Mangini' },
  { slug: 'how-to-sound-like-gavin-harrison', name: 'How to Sound Like Gavin Harrison' },
  // Issue #2015: SEO batch — Nick Menza, Nicko McBrain, Igor Cavalera
  { slug: 'how-to-sound-like-nick-menza', name: 'How to Sound Like Nick Menza' },
  { slug: 'how-to-sound-like-nicko-mcbrain', name: 'How to Sound Like Nicko McBrain' },
  { slug: 'how-to-sound-like-igor-cavalera', name: 'How to Sound Like Igor Cavalera' },
  // Issue #2271: SEO batch — Matt Garstka, Mikkey Dee, Sean Reinert
  { slug: 'how-to-sound-like-matt-garstka', name: 'How to Sound Like Matt Garstka' },
  { slug: 'how-to-sound-like-mikkey-dee', name: 'How to Sound Like Mikkey Dee' },
  { slug: 'how-to-sound-like-sean-reinert', name: 'How to Sound Like Sean Reinert' },
  // Issue #2432: SEO batch 17 — Mike Portnoy, Shannon Larkin, Scott Travis
  { slug: 'how-to-sound-like-mike-portnoy', name: 'How to Sound Like Mike Portnoy' },
  { slug: 'how-to-sound-like-shannon-larkin', name: 'How to Sound Like Shannon Larkin' },
  { slug: 'how-to-sound-like-scott-travis', name: 'How to Sound Like Scott Travis' },
  // Issue #2409: SEO batch 18 — Aquiles Priester, Eloy Casagrande, Charlie Benante
  { slug: 'how-to-sound-like-aquiles-priester', name: 'How to Sound Like Aquiles Priester' },
  { slug: 'how-to-sound-like-eloy-casagrande', name: 'How to Sound Like Eloy Casagrande' },
  { slug: 'how-to-sound-like-charlie-benante', name: 'How to Sound Like Charlie Benante' },
  // Issue #2727: SEO batch 19 — Daniel Erlandsson, Paul Bostaph, Hannes Grossmann
  { slug: 'how-to-sound-like-daniel-erlandsson', name: 'How to Sound Like Daniel Erlandsson' },
  { slug: 'how-to-sound-like-paul-bostaph', name: 'How to Sound Like Paul Bostaph' },
  { slug: 'how-to-sound-like-hannes-grossmann', name: 'How to Sound Like Hannes Grossmann' },
  // Issue #2815: SEO batch 26 — Inferno, Pete Sandoval, Jaska Raatikainen
  { slug: 'how-to-sound-like-inferno', name: 'How to Sound Like Inferno' },
  { slug: 'how-to-sound-like-pete-sandoval', name: 'How to Sound Like Pete Sandoval' },
  { slug: 'how-to-sound-like-jaska-raatikainen', name: 'How to Sound Like Jaska Raatikainen' },
  // Issues #2226 & #2099: Hellhammer, Paul Mazurkiewicz, Richard Christy
  { slug: 'how-to-sound-like-hellhammer', name: 'How to Sound Like Hellhammer' },
  { slug: 'how-to-sound-like-paul-mazurkiewicz', name: 'How to Sound Like Paul Mazurkiewicz' },
  { slug: 'how-to-sound-like-richard-christy', name: 'How to Sound Like Richard Christy' },
  // Issue #2950: SEO batch 33 — Ben Koller, Vinnie Paul, Blake Richardson
  { slug: 'how-to-sound-like-ben-koller', name: 'How to Sound Like Ben Koller' },
  { slug: 'how-to-sound-like-vinnie-paul', name: 'How to Sound Like Vinnie Paul' },
  { slug: 'how-to-sound-like-blake-richardson', name: 'How to Sound Like Blake Richardson' },
];

// Issue #702: Beginner gear guides - SEO content hub
const beginnerGuides = [
  { slug: 'beginner-metal-drummer-setup', name: 'The Ultimate Beginner Metal Drummer Gear Guide Under $1000' },
  // Issue #833: $500 budget tier guide
  { slug: 'budget-metal-drum-setup-500', name: 'The Best Budget Metal Drum Setup Under $500' },
  // Issue #834: $1000 mid-tier budget guide (split 2/3 of #830)
  { slug: 'budget-metal-drum-setup-1000', name: 'The Best Metal Drum Setup Under $1000' },
  // Issue #835: $2000 pro-tier budget guide (split 3/3 of #830)
  { slug: 'budget-metal-drum-setup-2000', name: 'The Best Metal Drum Setup Under $2000' },
];

// Issue #704: Metal Drummer Name Generator - viral tool
const toolPages = [
  { slug: 'metal-drummer-name-generator', name: 'Metal Drummer Name Generator' },
];

// Issue #732: Top 20 Gear Comparison Tool pairs for SEO
// High-traffic matchups for auto-generation
const top20GearComparisons = [
  { d1: 'joey-jordison', d2: 'lars-ulrich' },
  { d1: 'lars-ulrich', d2: 'dave-lombardo' },
  { d1: 'joey-jordison', d2: 'george-kollias' },
  { d1: 'mario-duplantier', d2: 'tomas-haake' },
  { d1: 'mike-portnoy', d2: 'danny-carey' },
  { d1: 'gene-hoglan', d2: 'pete-sandoval' },
  { d1: 'hellhammer', d2: 'inferno' },
  { d1: 'brann-dailor', d2: 'mario-duplantier' },
  { d1: 'dave-lombardo', d2: 'gene-hoglan' },
  { d1: 'matt-halpern', d2: 'alex-bent' },
  { d1: 'nicko-mcbrain', d2: 'vinnie-paul' },
  { d1: 'charlie-benante', d2: 'dave-lombardo' },
  { d1: 'eloy-casagrande', d2: 'joey-jordison' },
  { d1: 'george-kollias', d2: 'flo-mounier' },
  { d1: 'danny-carey', d2: 'tomas-haake' },
  { d1: 'chris-adler', d2: 'brann-dailor' },
  { d1: 'joey-jordison', d2: 'vinnie-paul' },
  { d1: 'matt-garstka', d2: 'matt-halpern' },
  { d1: 'inferno', d2: 'george-kollias' },
  { d1: 'mike-portnoy', d2: 'mike-mangini' },
];

// Issue #739: Signature Gear Spotlight pages
const signatureGearPages = [
  { drummerSlug: 'joey-jordison', gearSlug: 'joey-jordison-pearl-signature-snare', name: 'Pearl Joey Jordison Signature Snare' },
  { drummerSlug: 'lars-ulrich', gearSlug: 'lars-ulrich-paiste-rude-china', name: 'Paiste 20" RUDE Wild China' },
  { drummerSlug: 'danny-carey', gearSlug: 'danny-carey-paiste-giant-beat-gongs', name: 'Paiste Giant Beat Gongs' },
  { drummerSlug: 'mario-duplantier', gearSlug: 'mario-duplantier-tama-starphonic-bronze', name: 'Tama Starphonic Bronze' },
  { drummerSlug: 'gene-hoglan', gearSlug: 'gene-hoglan-pearl-reference-kit', name: 'Pearl Reference Pure Kit' },
];

// Issue #749 / #1056: Signature Licks pages — derived from SIGNATURE_LICKS so new
// per-drummer lick modules auto-appear in the sitemap (no hand-maintained list).
const signatureLicksPages = Object.values(SIGNATURE_LICKS).map(lick => ({
  drummerSlug: lick.drummerSlug,
  lickSlug: lick.slug,
  name: lick.name,
}));

// Drummers with licks hub pages — distinct drummerSlugs in first-appearance order.
const drummerLicksHubs = Object.values(SIGNATURE_LICKS).reduce((hubs, lick) => {
  if (!hubs.some(h => h.drummerSlug === lick.drummerSlug)) {
    hubs.push({ drummerSlug: lick.drummerSlug, name: lick.drummerName });
  }
  return hubs;
}, []);

// Issue #802: Endorsement Tracker pages
// Track brand deals and endorsement history for drummers
const endorsementDrummers = [
  'lars-ulrich', 'joey-jordison', 'tomas-haake', 'dave-lombardo',
  'george-kollias', 'eloy-casagrande', 'jay-weinberg', 'mike-portnoy',
  'danny-carey', 'mario-duplantier', 'brann-dailor', 'chris-adler',
  'matt-halpern', 'inferno', 'charlie-benante',
];

// Issue #813: Gear Price History Tracker pages
// Inflation-adjusted setup costs over time
// Issue #1808: Phase 2 — Mike Portnoy, Gene Hoglan, Danny Carey
// Issue #1818: Phase 3 — Tomas Haake, Pete Sandoval, Vinnie Paul
// Issue #2100: Phase 4 — Igor Cavalera, Nicko McBrain, Matt Greiner
const gearPriceHistoryDrummers = [
  'lars-ulrich',     // Kill 'Em All era (1983)
  'joey-jordison',   // Iowa era (2001)
  'dave-lombardo',   // Reign in Blood era (1986)
  'mike-portnoy',    // Images and Words era (1992)
  'gene-hoglan',     // Individual Thought Patterns era (1993)
  'danny-carey',     // Undertow/Aenima era (1994)
  'tomas-haake',     // Chaosphere era (1998)
  'pete-sandoval',   // Altars of Madness era (1989)
  'vinnie-paul',     // Cowboys from Hell era (1990)
  'igor-cavalera',   // Roots era (1996)
  'nicko-mcbrain',   // Powerslave era (1984)
  'matt-greiner',    // Leveler era (2011)
  'charlie-benante', // Among the Living era (1987) — Issue #2238
  'nick-menza',      // Rust in Peace era (1990) — Issue #2238
  'inferno',         // Demigod era (2004) — Issue #2238
  'chris-adler',     // Ashes of the Wake era (2004) — Issue #3077
  'daniel-erlandsson', // Wages of Sin era (2001) — Issue #3077
  'ray-luzier',      // Korn III era (2010) — Issue #3077
  'paul-mazurkiewicz', // Tomb of the Mutilated era (1992) — Issue #3097
  'flo-mounier',     // None So Vile era (1996) — Issue #3097
  'eloy-casagrande', // Machine Messiah era (2017) — Issue #3097
  'alex-bent',       // The Sin and the Sentence era (2017) — Issue #3187
  'matt-garstka',    // The Joy of Motion era (2014) — Issue #3187
  'matt-halpern',    // Select Difficulty era (2016) — Issue #3187
  'bill-ward',       // Black Sabbath debut era (1970) — Issue #3252
  'shannon-larkin',  // Faceless era (2002) — Issue #3252
  'john-otto',       // Significant Other era (1999) — Issue #2918
  'dirk-verbeuren',  // Dystopia era (2016) — Issue #2918
  'martin-axenrot',  // Watershed era (2008) — Issue #2918
  'mario-duplantier', // Terra Incognita era (2001) — Issue #2974
  'hellhammer',      // De Mysteriis Dom Sathanas era (1994) — Issue #2974
  'ben-koller',      // Jane Doe era (2001) — Issue #2974
];

// Issue #1473: Individual /battles/<slug> pages — derive slugs from CURATED_MATCHUPS
// so the sitemap stays in sync as matchups are added or changed.
const drummerIdToSlugMap = {};
for (const d of drummers) {
  drummerIdToSlugMap[d.id] = generateSlug(d.name);
}
const battleSlugs = CURATED_MATCHUPS.map(m => {
  const s1 = drummerIdToSlugMap[m.drummer1Id];
  const s2 = drummerIdToSlugMap[m.drummer2Id];
  return s1 && s2 ? `${s1}-vs-${s2}` : null;
}).filter(Boolean);

// Issue #770 / #1125: Drummer Gear Category Pages — long-tail keyword pages at
// /drummer/<slug>/<category>. The renderer api/gear/[slug]/[category].js serves
// a real page iff `drummer.gear[category]` is populated (else 404). We mirror
// that exact gate here and emit a URL for EVERY drummer × category that has real
// gear data, extending coverage from 16 hardcoded "priority" drummers to the
// full roster — while guaranteeing every declared URL resolves to a substantive
// page (no thin/404 pages). This also drops the old hardcoded `pedals` URLs:
// no drummer carries a `gear.pedals` field, so those 404'd under the renderer.
const GEAR_CATEGORIES = ['cymbals', 'drums', 'pedals', 'hardware', 'snare', 'sticks'];
// Same presence check the renderer uses to decide a category section exists.
function drummerHasCategoryGear(drummer, category) {
  return Boolean(drummer.gear && drummer.gear[category]);
}
const drummerGearCategoryPages = [];
for (const d of DRUMMER_GEAR_DATA) {
  for (const category of GEAR_CATEGORIES) {
    if (drummerHasCategoryGear(d, category)) {
      drummerGearCategoryPages.push({ drummerSlug: generateSlug(d.name), category });
    }
  }
}

// Issue #1021 (split 3/4 of #1017): LLM-facing Markdown surface.
// Static files live in public/llms/*.md and public/llms/drummers/<slug>.md.
// Listing them in the sitemap makes them crawlable, not just discoverable
// via prose links in llms.txt. Per-drummer slugs mirror the committed files
// in public/llms/drummers/ (61 profiles).
const llmsDrummerSlugs = [
  'abe-cunningham', 'alex-bent', 'aquiles-priester', 'arin-ilejay',
  'art-cruz', 'ben-koller', 'bill-ward', 'blake-richardson',
  'brann-dailor', 'charlie-benante', 'chris-adler', 'chris-turner',
  'daniel-erlandsson', 'danny-carey', 'daray', 'dave-lombardo',
  'derek-roddy', 'dirk-verbeuren', 'eloy-casagrande', 'flo-mounier',
  'frost', 'gavin-harrison', 'gene-hoglan', 'george-kollias',
  'hannes-grossmann', 'hellhammer', 'igor-cavalera', 'inferno',
  'isaac-lamb', 'jaska-raatikainen', 'jason-bittner', 'jay-weinberg',
  'jocke-wallgren', 'joey-jordison', 'john-otto', 'kevin-talley',
  'lars-ulrich', 'mario-duplantier', 'martin-lopez', 'matt-garstka',
  'matt-greiner', 'matt-halpern', 'mike-mangini', 'mike-portnoy',
  'mikkey-dee', 'morgan-gren', 'navene-koperweis', 'nick-augusto',
  'nicko-mcbrain', 'paul-mazurkiewicz', 'pete-sandoval', 'ray-luzier',
  'raymond-herrera', 'richard-christy', 'ryan-van-poederooyen', 'scott-travis',
  'shannon-larkin', 'tim-yeung', 'tomas-haake', 'travis-orbin',
  'vinnie-paul',
];

const BASE_URL = 'https://metalforge.io';

// Issue #1072: stop stamping <lastmod>=today on every URL every crawl.
// Google discards a site-wide lastmod it observes to be inaccurate, so a
// churning all-URLs-same-date-every-fetch value forfeits the crawl-freshness
// signal. Use a single STABLE release date for pages without a verifiable
// per-URL date; bump it only on material content releases (never wire it back
// to new Date()). Article URLs override this with their real ALBUM_ARTICLES
// dateModified via the per-entry `lastmod` field below.
const SITE_LASTMOD = '2026-06-26';

// Real per-URL date if the entry carries a verifiable one, else the stable
// site-wide release date.
function lastmodFor(url) {
  return url.lastmod || SITE_LASTMOD;
}

function generateSlug(name) {
  return name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
}

function xmlEscape(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Issue #1274: slug→band lookup for drummer image sitemap entries.
const drummerBandBySlug = {};
for (const d of DRUMMER_GEAR_DATA) {
  drummerBandBySlug[generateSlug(d.name)] = d.band || null;
}

// Issue #997: gear/series "drummers-using" page URLs.
// Mirrors slugifySeries + the dedupe rule in
// packages/frontend/data/gearSeriesPages.js so these <loc>s match the
// routes #996 actually serves. Only series with ≥2 drummers earn a page,
// and the first series to claim a given slug wins it (keeps URLs unique).
function slugifyGearSeries(str) {
  return String(str)
    .toLowerCase()
    .replace(/['"]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function getGearSeriesUrls() {
  const seen = new Set();
  const urls = [];
  for (const [brand, seriesObj] of Object.entries(GEAR_INDEX)) {
    const brandSlug = slugifyGearSeries(brand);
    for (const [series, drummers] of Object.entries(seriesObj)) {
      if (!Array.isArray(drummers) || drummers.length < 2) continue;
      const seriesSlug = slugifyGearSeries(series);
      const key = `${brandSlug}/${seriesSlug}`;
      if (seen.has(key)) continue; // first series wins a given slug
      seen.add(key);
      urls.push(`/gear/${brandSlug}/${seriesSlug}/drummers-using`);
    }
  }
  return urls;
}

// Issue: pre-render at build time. The full URL list + XML serialization is
// extracted here so scripts/generate-sitemap.mjs can emit a static
// dist/sitemap.xml at build time (no Vercel cold-start on every Googlebot
// fetch), while the serverless handler below stays a thin fallback.
export function buildSitemapXml() {
  const urls = [
    { loc: '/', priority: '1.0', changefreq: 'weekly' },
    // Issue #1053: #2 organic page (GA4) — drummer database hub, links to all 62 profiles
    { loc: '/drummers', priority: '0.9', changefreq: 'weekly' },
    // Issue #1053: #3 organic page (GA4) — "Which Metal Drummer Are You?" match quiz
    { loc: '/quiz', priority: '0.9', changefreq: 'weekly' },
    { loc: '/kit-quiz', priority: '0.9', changefreq: 'weekly' },
    { loc: '/guess-the-kit', priority: '0.95', changefreq: 'weekly' }, // Issue #706: Photo Quiz
    { loc: '/kit-builder', priority: '0.9', changefreq: 'weekly' },
    { loc: '/gear', priority: '0.9', changefreq: 'weekly' },
    // Issue #1823: Budget-tier gear shopping hub — high commercial intent
    { loc: '/gear-by-budget', priority: '0.9', changefreq: 'weekly' },
    { loc: '/quotes', priority: '0.9', changefreq: 'weekly' },
    { loc: '/facts', priority: '0.8', changefreq: 'monthly' }, // Issue #452: Quick Facts (FAQPage schema) — #1051 de-orphan
    { loc: '/lists', priority: '0.9', changefreq: 'weekly' },
    { loc: '/birthdays', priority: '0.9', changefreq: 'weekly' },
    // Issue #723: Metal Drummer Evolution Timeline (1970-2024)
    { loc: '/history', priority: '0.9', changefreq: 'monthly' },
    { loc: '/techniques', priority: '0.9', changefreq: 'weekly' },
    // Issue #1042: top-level signature licks index hub
    { loc: '/licks', priority: '0.9', changefreq: 'weekly' },
    // Issue #660: Gear News page with RSS
    { loc: '/gear-news', priority: '0.9', changefreq: 'daily' },
    // Issue #689: Drummer Battle voting feature
    { loc: '/battles', priority: '0.9', changefreq: 'weekly' },
    // Issue #1822: Drummer spotlight features hub
    { loc: '/spotlights', priority: '0.85', changefreq: 'weekly' },
    // Issue #1473: Individual /battles/<slug> pages (8 curated matchups)
    ...battleSlugs.map(slug => ({ loc: `/battles/${slug}`, priority: '0.85', changefreq: 'monthly' })),
    // Issue #695: Gear Statistics data hub
    { loc: '/stats', priority: '0.9', changefreq: 'weekly' },
    { loc: '/stats/gear-insights', priority: '0.9', changefreq: 'weekly' },
    // Issue #685: "How to Sound Like" guides hub
    { loc: '/guides', priority: '0.9', changefreq: 'weekly' },
    ...soundLikeGuides.map(g => ({ loc: `/guides/${g.slug}`, priority: '0.9', changefreq: 'monthly' })),
    // Issue #1801: Beginner guide hub page
    { loc: '/beginner-guide', priority: '0.85', changefreq: 'monthly' },
    // Issue #702: Beginner gear guides
    ...beginnerGuides.map(g => ({ loc: `/guides/${g.slug}`, priority: '0.95', changefreq: 'monthly' })),
    // Issue #1794: Genre gear guides (commercial-intent purchase queries)
    ...Object.values(GENRE_GEAR_GUIDES).map(g => ({ loc: `/guides/${g.slug}`, priority: '0.95', changefreq: 'monthly' })),
    // Issue #1804: Shareable gear cards gallery
    { loc: '/cards', priority: '0.6', changefreq: 'monthly' },
    // Issue #1579: BPM Tap Calculator + Metal Songs BPM Database
    { loc: '/bpm', priority: '0.95', changefreq: 'weekly' },
    { loc: '/bpm-tap', priority: '0.9', changefreq: 'monthly' },
    // Issue #729: Tools Hub landing page
    { loc: '/tools', priority: '0.95', changefreq: 'weekly' },
    // Issue #704: Tools pages (viral tools)
    ...toolPages.map(t => ({ loc: `/tools/${t.slug}`, priority: '0.95', changefreq: 'weekly' })),
    // Issue #721, #732: Gear Comparison Tool + Top 20 SEO comparisons
    { loc: '/tools/compare', priority: '0.95', changefreq: 'weekly' },
    ...top20GearComparisons.map(c => ({ 
      loc: `/tools/compare/${c.d1}-vs-${c.d2}`, 
      priority: '0.9', 
      changefreq: 'weekly' 
    })),
    ...gearCategories.map(c => ({ loc: `/gear/${c.slug}`, priority: '0.9', changefreq: 'weekly' })),
    ...top10Lists.map(l => ({ loc: `/lists/${l.slug}`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #1821: Articles hub (CollectionPage schema exists in api/meta/[...path].js)
    { loc: '/articles', priority: '0.9', changefreq: 'weekly' },
    // Issue #642: Article pages for SEO-optimized content
    ...articles.map(a => ({ loc: `/articles/${a.slug}`, priority: '0.9', changefreq: 'weekly' })),
    // Issue #663: Album gear breakdown and drummer kit articles
    // Issue #1072: emit each article's real dateModified (falls back to SITE_LASTMOD).
    ...albumArticles.map(a => ({ loc: `/articles/${a.slug}`, lastmod: ALBUM_ARTICLES[a.slug]?.dateModified, priority: '0.9', changefreq: 'monthly' })),
    ...drummers.map(d => {
      const slug = generateSlug(d.name);
      const band = drummerBandBySlug[slug] || null;
      return {
        loc: `/drummer/${slug}`,
        priority: '0.8',
        changefreq: 'monthly',
        image: {
          loc: `${BASE_URL}/api/card/${slug}?format=og`,
          title: `${d.name} drum kit setup${band ? ' — ' + band : ''}`,
          caption: `Complete drum gear setup of ${d.name}${band ? ' from ' + band : ''}`,
        },
      };
    }),
    ...gearItems.map(g => ({ loc: `/gear/item/${g.slug}`, priority: '0.7', changefreq: 'monthly' })),
    // Issue #1799: Genre hub (/genres) + 8 genre landing pages (/genre/<slug>)
    { loc: '/genres', priority: '0.9', changefreq: 'weekly' },
    ...getAllGenreSlugs().map(slug => ({ loc: `/genre/${slug}`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #1171: /bands index hub + all 19 band pages at the correct plural path.
    { loc: '/bands', priority: '0.9', changefreq: 'weekly' },
    ...bandPages.map(slug => ({ loc: `/bands/${slug}`, priority: '0.8', changefreq: 'monthly' })),
    ...techniques.map(t => ({ loc: `/techniques/${t.slug}`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #870, #994: Technique → drummers SEO pages (/technique/<slug>/drummers)
    // Same priority/changefreq pattern as drummer pages.
    ...getAllTechniqueSlugs().map(slug => ({ loc: `/technique/${slug}/drummers`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #656: Gear brand landing pages
    { loc: '/brands', priority: '0.9', changefreq: 'weekly' },
    ...gearBrands.map(b => ({ loc: `/brands/${b.slug}`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #345: Gear comparison pages
    { loc: '/compare', priority: '0.9', changefreq: 'weekly' },
    ...gearComparisons.map(c => ({ loc: `/compare/${c.slug}`, priority: '0.8', changefreq: 'monthly' })),
    // Issue #558, #691: Drummer vs Drummer comparison pages (SEO play)
    { loc: '/vs', priority: '0.9', changefreq: 'weekly' },
    ...drummerComparisons.map(c => ({ loc: `/vs/${c.slug}`, priority: '0.7', changefreq: 'monthly' })),
    // Issue #739: Signature Gear Spotlight pages
    ...signatureGearPages.map(sg => ({ loc: `/drummers/${sg.drummerSlug}/signature/${sg.gearSlug}`, priority: '0.85', changefreq: 'monthly' })),
    // Issue #749: Signature Licks Database pages
    ...drummerLicksHubs.map(d => ({ loc: `/drummers/${d.drummerSlug}/licks`, priority: '0.9', changefreq: 'weekly' })),
    ...signatureLicksPages.map(sl => ({ loc: `/drummers/${sl.drummerSlug}/licks/${sl.lickSlug}`, priority: '0.85', changefreq: 'monthly' })),
    // Issue #770: SEO Blitz - Drummer Gear Category Pages (long-tail keywords)
    ...drummerGearCategoryPages.map(dgc => ({ loc: `/drummer/${dgc.drummerSlug}/${dgc.category}`, priority: '0.85', changefreq: 'monthly' })),
    // Issue #802: Endorsement Tracker pages
    { loc: '/endorsement-news', priority: '0.9', changefreq: 'weekly' },
    ...endorsementDrummers.map(slug => ({ loc: `/drummers/${slug}/endorsements`, priority: '0.85', changefreq: 'monthly' })),
    // Issue #813: Gear Price History Tracker pages
    ...gearPriceHistoryDrummers.map(slug => ({ loc: `/drummers/${slug}/gear-history`, priority: '0.9', changefreq: 'monthly' })),
    // Issue #1475: Drummer gear evolution pages (3 drummers: lars-ulrich, joey-jordison, dave-lombardo)
    ...Object.keys(DRUMMER_EVOLUTION).map(slug => ({ loc: `/drummers/${slug}/evolution`, priority: '0.82', changefreq: 'monthly' })),
    // Issue #1805: per-drummer gear evolution LLM markdown files
    ...Object.keys(DRUMMER_EVOLUTION).map(slug => ({ loc: `/llms/evolution/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #871/#997: gear/series "drummers-using" SEO pages (≥2 drummers each)
    ...getGearSeriesUrls().map(loc => ({ loc, priority: '0.8', changefreq: 'monthly' })),
    // Issue #2403: kit-level "drummers-using" pages (12 purchase-intent scaffold slugs).
    ...Object.keys(DRUMMERS_BY_KIT).map(key => ({ loc: `/gear/${key}/drummers-using`, priority: '0.85', changefreq: 'monthly' })),
    // Issue #1021 (split 3/4 of #1017): LLM-facing Markdown surface (public/llms/*.md).
    { loc: '/llms/index.md', priority: '0.6', changefreq: 'monthly' },
    { loc: '/llms/faq.md', priority: '0.6', changefreq: 'monthly' },
    { loc: '/llms/gear-guide.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1185: brand-first LLM citation surface for "which drummers use X brand" queries.
    { loc: '/llms/gear-by-brand.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1045: signature-lick database as ingestible markdown for AI crawlers.
    { loc: '/llms/licks.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1126: drumming-techniques reference as ingestible markdown.
    { loc: '/llms/techniques.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1173: bands + drummer-history reference as ingestible markdown.
    { loc: '/llms/bands.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1806: per-band LLM markdown files for AI citation of band drummer/gear queries.
    ...Object.keys(BAND_DATA).map(slug => ({
      loc: `/llms/bands/${slug}.md`,
      priority: '0.5',
      changefreq: 'monthly',
    })),
    // Issue #1309: gear price timeline data for Lars Ulrich, Joey Jordison, Dave Lombardo.
    { loc: '/llms/gear-history.md', priority: '0.5', changefreq: 'monthly' },
    // Issue #1782: per-drummer gear history LLM markdown
    ...gearPriceHistoryDrummers.map(slug => ({ loc: `/llms/gear-history/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #1561: drummer birth dates as LLM markdown for birthday/calendar AI queries.
    { loc: '/llms/birthdays.md', priority: '0.5', changefreq: 'monthly' },
    // Issue #1190: drummer comparison pages as ingestible markdown.
    { loc: '/llms/comparisons.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1222: top-10 ranked lists as ingestible markdown for AI citation.
    { loc: '/llms/lists.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1223: quick facts page as ingestible markdown for AI citation.
    { loc: '/llms/facts.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1246: quiz LLM citation surface — #3 organic page, zero prior AI discoverability.
    { loc: '/llms/quiz.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1560: quotes LLM citation surface — 36 attributed quotes from 12 metal drummers.
    { loc: '/llms/quotes.md', priority: '0.5', changefreq: 'monthly' },
    // Issue #1330: gear stats LLM citation surface — brand-popularity data for AI queries.
    { loc: '/llms/stats.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1401: gear brand insights LLM citation surface — named drummer citations with % data.
    { loc: '/llms/gear-insights.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1586: gear-news + endorsement-news LLM citation surfaces (temporal/news dimension).
    { loc: '/llms/gear-news.md', priority: '0.6', changefreq: 'daily' },
    { loc: '/llms/endorsement-news.md', priority: '0.6', changefreq: 'weekly' },
    // Issue #1416: endorsement hub LLM citation surface — cross-brand index of 15 drummers.
    { loc: '/llms/endorsements.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1435: per-drummer endorsement detail pages — one file per endorsement-tracked drummer.
    ...endorsementDrummers.map(slug => ({ loc: `/llms/endorsements/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #1781: per-brand LLM markdown — sitemap entries for 8 files shipped in #1415
    ...gearBrands.map(b => ({ loc: `/llms/brands/${b.slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #1273: tools section LLM citation surface — gear-search, dream-set-builder, kit-builder, gear-comparison, tier-list.
    { loc: '/llms/tools/gear-search.md', priority: '0.6', changefreq: 'monthly' },
    { loc: '/llms/tools/dream-set-builder.md', priority: '0.6', changefreq: 'monthly' },
    { loc: '/llms/tools/kit-builder.md', priority: '0.6', changefreq: 'monthly' },
    { loc: '/llms/tools/gear-comparison.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1780: per-comparison brand LLM files — 7 files shipped in #1514, absent from sitemap.
    ...gearComparisons.map(c => ({ loc: `/llms/gear-comparison/${c.slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #2404: drummers-using LLM files for top-3 flagship kit pages (Tama Star Classic Maple, DW Collector's Maple, Pearl Reference Pure).
    { loc: '/llms/gear-comparison/drummers-using-tama-star-classic-maple.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-dw-collectors-maple.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-pearl-reference-pure.md', priority: '0.5', changefreq: 'monthly' },
    // Issue #2405: drummers-using LLM files for mid-tier kit pages (Gretsch USA Custom, Sonor SQ2, Mapex Armory).
    { loc: '/llms/gear-comparison/drummers-using-gretsch-usa-custom.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-sonor-sq2.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-mapex-armory.md', priority: '0.5', changefreq: 'monthly' },
    // Issue #2406: drummers-using LLM files for final 6 kit pages (Ludwig Classic Maple, Yamaha Recording Custom,
    // Tama Superstar Classic, DW Performance Maple, Pearl Masters Maple, Sonor Vintage).
    { loc: '/llms/gear-comparison/drummers-using-ludwig-classic-maple.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-yamaha-recording-custom.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-tama-superstar-classic.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-dw-performance-maple.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-pearl-masters-maple.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/gear-comparison/drummers-using-sonor-vintage.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/tools/tier-list.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1351: name-generator LLM citation surface — metal drummer alias generator.
    { loc: '/llms/tools/name-generator.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1582: BPM + metal songs tempo database LLM citation surface.
    { loc: '/llms/bpm.md', priority: '0.6', changefreq: 'monthly' },
    // Issue #1329: how-to-sound-like + beginner guides LLM citation surface.
    { loc: '/llms/guides.md', priority: '0.4', changefreq: 'monthly' },
    // Issue #1450: per-guide deep-dive Markdown files for AI citation (10 sound-like guides).
    ...soundLikeGuides.map(g => ({ loc: `/llms/guides/${g.slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #1562: beginner/budget gear guide LLM citation surfaces.
    { loc: '/llms/guides/beginner-metal-drummer-setup.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/guides/budget-metal-drum-setup-500.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/guides/budget-metal-drum-setup-1000.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/guides/budget-metal-drum-setup-2000.md', priority: '0.5', changefreq: 'monthly' },
    // Per-drummer Markdown profiles — low priority, full crawl coverage.
    ...llmsDrummerSlugs.map(slug => ({ loc: `/llms/drummers/${slug}.md`, priority: '0.4', changefreq: 'monthly' })),
    // Issue #1058: per-article Markdown breakdowns (public/llms/articles/<slug>.md).
    // Slugs sourced from ALBUM_ARTICLES so they stay 1:1 with the committed files.
    // Issue #1072: same real dateModified as the article HTML page (1:1 data).
    ...Object.keys(ALBUM_ARTICLES).map(slug => ({ loc: `/llms/articles/${slug}.md`, lastmod: ALBUM_ARTICLES[slug]?.dateModified, priority: '0.4', changefreq: 'monthly' })),
    // Issue #2311: lick-guide LLM articles (not album articles — no /articles/ frontend page).
    { loc: '/llms/articles/matt-greiner-licks.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/articles/joey-jordison-licks.md', priority: '0.5', changefreq: 'monthly' },
    // Issue #2433: Batch 7 lick-guide LLM files (jay-weinberg, nicko-mcbrain, pete-sandoval).
    { loc: '/llms/licks/jay-weinberg-licks.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/licks/nicko-mcbrain-licks.md', priority: '0.5', changefreq: 'monthly' },
    { loc: '/llms/licks/pete-sandoval-licks.md', priority: '0.5', changefreq: 'monthly' },
    // Issue #1201: per-technique deep-dive Markdown files for AI citation.
    // One file per technique slug mirrors the per-drummer pattern above.
    ...getAllTechniqueSlugs().map(slug => ({ loc: `/llms/technique/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #1218 / #1244: per-drummer lick Markdown files for AI citation (all 51 drummers).
    // Issue #1219: added frost + daray (black metal batch).
    ...([
      'joey-jordison', 'lars-ulrich', 'dave-lombardo', 'george-kollias', 'tomas-haake',
      'matt-greiner', 'gene-hoglan', 'pete-sandoval', 'derek-roddy', 'brann-dailor',
      'mike-portnoy', 'matt-garstka', 'inferno', 'hellhammer', 'bill-ward',
      'charlie-benante', 'mario-duplantier', 'chris-adler', 'ben-koller', 'flo-mounier',
      'abe-cunningham', 'alex-bent', 'aquiles-priester', 'arin-ilejay', 'art-cruz',
      'blake-richardson', 'daniel-erlandsson', 'danny-carey', 'dirk-verbeuren', 'eloy-casagrande',
      'gavin-harrison', 'hannes-grossmann', 'igor-cavalera', 'jaska-raatikainen', 'jason-bittner',
      'jay-weinberg', 'martin-lopez', 'matt-halpern', 'mike-mangini', 'mikkey-dee',
      'navene-koperweis', 'nicko-mcbrain', 'paul-bostaph', 'paul-mazurkiewicz', 'ray-luzier',
      'raymond-herrera', 'richard-christy', 'scott-travis', 'shannon-larkin', 'travis-orbin',
      'vinnie-paul', 'frost', 'daray',
      // Issue #1248: Chris Turner + Isaac Lamb (100% lick coverage).
      'chris-turner', 'isaac-lamb',
      // Issue #1702: Batch 3 — remaining 8 drummers added after 100% lick milestone.
      'jocke-wallgren', 'john-otto', 'jon-dette', 'kevin-talley',
      'morgan-agren', 'nick-augusto', 'ryan-van-poederooyen', 'tim-yeung',
    ].map(slug => ({ loc: `/llms/licks/${slug}.md`, priority: '0.5', changefreq: 'monthly' }))),
    // Issue #1271: per-series LLM Markdown files for AI citation.
    // Slugs derived from GEAR_INDEX (same slugifyGearSeries logic used for HTML pages)
    // so /llms/gear-series/<brand>-<series>.md URLs stay 1:1 with committed files.
    ...Object.entries(GEAR_INDEX).flatMap(([brand, seriesObj]) =>
      Object.entries(seriesObj)
        .filter(([, ds]) => Array.isArray(ds) && ds.length >= 2)
        .map(([series]) => ({
          loc: `/llms/gear-series/${slugifyGearSeries(brand)}-${slugifyGearSeries(series)}.md`,
          priority: '0.5',
          changefreq: 'monthly',
        }))
    ),
    // Issue #1276: per-pair drummer comparison Markdown files for AI citation.
    // Slugs sourced from drummerComparisons data so /llms/vs/<slug>.md URLs
    // stay 1:1 with the files generated by scripts/generate-llms-vs.cjs.
    ...getAllDrummerComparisonSlugs().map(slug => ({
      loc: `/llms/vs/${slug}.md`,
      priority: '0.5',
      changefreq: 'monthly',
    })),
    // Issue #1795: high-value drummer comparison LLM files not in drummerComparisons data.
    // Hardcoded to match the 8 files shipped in public/llms/vs/ by this issue.
    // Issue #2101: 3 additional pairs added (art-cruz-vs-chris-adler, aquiles-priester-vs-jaska-raatikainen, matt-garstka-vs-mike-mangini).
    ...([
      'tomas-haake-vs-george-kollias',
      'brann-dailor-vs-danny-carey',
      'pete-sandoval-vs-flo-mounier',
      'mike-portnoy-vs-mike-mangini',
      'lars-ulrich-vs-charlie-benante',
      'vinnie-paul-vs-dave-lombardo',
      'travis-orbin-vs-matt-halpern',
      'pete-sandoval-vs-george-kollias',
      'art-cruz-vs-chris-adler',
      'aquiles-priester-vs-jaska-raatikainen',
      'matt-garstka-vs-mike-mangini',
    ].map(slug => ({
      loc: `/llms/vs/${slug}.md`,
      priority: '0.5',
      changefreq: 'monthly',
    }))),
    // Issue #1703: per-matchup battle LLM Markdown files for AI citation (8 files).
    // Hardcoded to match the 8 files shipped in public/llms/battles/.
    ...([
      'brann-dailor-vs-chris-adler',
      'danny-carey-vs-mike-portnoy',
      'gene-hoglan-vs-george-kollias',
      'inferno-vs-hellhammer',
      'joey-jordison-vs-eloy-casagrande',
      'lars-ulrich-vs-dave-lombardo',
      'tomas-haake-vs-mario-duplantier',
      'vinnie-paul-vs-dave-lombardo',
    ].map(slug => ({
      loc: `/llms/battles/${slug}.md`,
      priority: '0.5',
      changefreq: 'monthly',
    }))),
    // Issue #1781: per-brand LLM Markdown files for AI citation (8 files shipped in #1415).
    ...gearBrands.map(b => ({ loc: `/llms/brands/${b.slug}.md`, priority: '0.5', changefreq: 'monthly' })),
    // Issue #1512: per-list LLM Markdown files for AI citation (8 top-10 lists).
    // Slugs sourced from the same top10Lists array used for /lists/<slug> HTML pages
    // so /llms/lists/<slug>.md URLs stay 1:1 with the files generated by
    // scripts/generate-llms-lists-per-slug.cjs.
    ...top10Lists.map(l => ({
      loc: `/llms/lists/${l.slug}.md`,
      priority: '0.5',
      changefreq: 'monthly',
    })),
    // Issue #1800: genre LLM citation surface — 8 genre pages
    ...getAllGenreSlugs().map(slug => ({ loc: `/llms/genres/${slug}.md`, priority: '0.5', changefreq: 'monthly' })),
  ];
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
${urls.map(url => `  <url>
    <loc>${xmlEscape(BASE_URL + url.loc)}</loc>
    <lastmod>${lastmodFor(url)}</lastmod>
    <changefreq>${url.changefreq}</changefreq>
    <priority>${url.priority}</priority>${url.image ? `
    <image:image>
      <image:loc>${xmlEscape(url.image.loc)}</image:loc>
      <image:title>${xmlEscape(url.image.title)}</image:title>
      <image:caption>${xmlEscape(url.image.caption)}</image:caption>
    </image:image>` : ''}
  </url>`).join('\n')}
</urlset>`;
  return sitemap;
}

export default function handler(req, res) {
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 'public, max-age=86400');
  res.status(200).send(buildSitemapXml());
}
